### ISSUE TITLE
40.0.0 regression: AutoConnect fails with Azure FTP servers

### ISSUE THREAD

**Issue by IGx89** [robinrodricks/FluentFTP#1046]
**FTP Server OS:** Windows

**FTP Server Type:** Azure

**Client Computer OS:** Windows

**FluentFTP Version:** 40.0.0 - latest (42.0.1)

**Framework:** .NET 6

AutoConnect doesn't work with Azure FTP servers. It worked in v39, but v40 broke it. The problem is due to ConnectModule.GetWorkingProfileFromHost returning a partial known profile (no host, credentials, etc.) which causes ConnectModule.LoadProfile to throw an ArgumentException due to profile.Host being null.

**Logs :**

```
# AutoConnect()

# AutoDetect(True, False)

# Dispose()
Status:   Disposing FtpClient object...
Unhandled exception. System.ArgumentException: Required parameter is null or blank. (Parameter 'profile.Host')
   at FluentFTP.Client.Modules.ConnectModule.LoadProfile(BaseFtpClient client, FtpProfile profile) in C:\Development\FluentFTP\FluentFTP\Client\Modules\ConnectModule.cs:line 442
   at FluentFTP.Client.BaseClient.BaseFtpClient.LoadProfile(FtpProfile profile) in C:\Development\FluentFTP\FluentFTP\Client\BaseClient\LoadProfile.cs:line 11
   at FluentFTP.Client.Modules.ConnectModule.ConfigureClient(BaseFtpClient client, FtpEncryptionMode encryption, SslProtocols protocol, FtpProfile knownProfile) in C:\Development\FluentFTP\FluentFTP\Client\Modules\ConnectModule.cs:line 314
   at FluentFTP.Client.Modules.ConnectModule.AutoDetectAsync(AsyncFtpClient client, Boolean firstOnly, Boolean cloneConnection, CancellationToken token) in C:\Development\FluentFTP\FluentFTP\Client\Modules\ConnectModule.cs:line 215
   at FluentFTP.AsyncFtpClient.AutoDetect(Boolean firstOnly, Boolean cloneConnection, CancellationToken token) in C:\Development\FluentFTP\FluentFTP\Client\AsyncClient\AutoDetect.cs:line 26
   at FluentFTP.AsyncFtpClient.AutoConnect(CancellationToken token) in C:\Development\FluentFTP\FluentFTP\Client\AsyncClient\AutoConnect.cs:line 19
```

**Comment by IGx89** [comment]
Sure, though it's pretty basic (Last part of FtpHost is `.ftp.p.azurewebsites.windows.net`):

```
using var ftpClient = new FtpClient(o.FtpHost, o.FtpUser, o.FtpPassword);
await ftpClient.AutoConnectAsync();
```
A similar regression happened in #901, though the root cause this time appears different (caused by refactoring).

**Comment by FanDjango** [comment]
Yeah, looking for it... thanks. And thanks for the #901 pointer, interesting reading... Ah, ok, I can see the change that provokes this. I will work on it tomorrow.

**Comment by FanDjango** [comment]
Can you test branches on my fork for this problem or must you use a Nuget Beta?

**Comment by IGx89** [comment]
A branch/fork works fine for me :)

**Comment by FanDjango** [comment]
Ok, then we'll clear this up that way and then Robin can wrap it up in the next release. Sleeping now, tomorrow I'll put together a quick fix as a branch and you will find it when your morning comes up. In the end, a better solution will need to be found, because  I will just take back part of the V40 refactor.

**Comment by FanDjango** [comment]
Oh, and I saw this in #901:

> Basically ConnectTimeout was not being honored before, so maybe you were able to connect even with a low timeout. Azure FTP is known to need higher timeouts.

As I have just merged a PR for making timeouts on SYN-ACK-SYN connect sequences finally by honoured correctly, I would ask you to comment on the question of whether

```
Timeout = 2000
```

is viable.

I would recommend perhaps to not specify a connection timeout at all and to leave that up to the system.

Please see: [this](https://github.com/robinrodricks/FluentFTP/wiki/FTP-Connection#how-do-i-change-the-connection-timeout-on-windows)

**Comment by IGx89** [comment]
Thanks! No rush, I can safely stay on v39.4.0 for another year if necessary :). But happy to help test

**Comment by FanDjango** [comment]
This is the one: https://github.com/FanDjango/FluentFTP/tree/BackoutAzure

**Comment by IGx89** [comment]
That works!

**Comment by FanDjango** [comment]
Thanks. The fix will be in the next release.
