### ISSUE TITLE
Upload fails due to socket timeout after period of inactivity

### ISSUE THREAD

**Issue by MurmelNash** [robinrodricks/FluentFTP#1082]
**FTP Server OS:** Unix

**FTP Server Type:** Vsftpd

**Client Computer OS:** Windows

**FluentFTP Version:** 42.1.0

**Framework:** .NET 6 

Exceeds the time between to uploads 5 minutes the AsyncFtpClient throws due to a socket timeout a System.NullReferenceException/FtpException on the next activity.
The behavior occurs with several different FTP server. The synchronous FtpClient works fine.
The SocketKeepAlive property of the FtpConfig does not effect the behavior.

Does that work as designed?
Is there any recommended possibility to check the connection state and reconnect in advance?

Code to reproduce: 

```
 var client = new AsyncFtpClient("ftp1", new NetworkCredential("user1", "password123"));
 await client.AutoConnect();
 
 Console.WriteLine("connected");
 
 var fileData = Encoding.UTF8.GetBytes("Test message");
 
 Console.WriteLine("upload 1");
 
 await client.UploadBytes(fileData, "file/test1.txt", createRemoteDir: true);
 
 await Task.Delay(TimeSpan.FromMinutes(5));
 
 Console.WriteLine("delay expired");
 
 Console.WriteLine("upload 2");
 
 // second upload throws exception
 await client.UploadBytes(fileData, "file/test2.txt", createRemoteDir: true);
 
 Console.WriteLine("done");

```

**Logs :**
```
 connected
 upload 1
 delay expired
 upload 2
 Unhandled exception. FluentFTP.FtpException: Error while uploading the file to the server. See InnerException for more info.
  ---> System.NullReferenceException: Object reference not set to an instance of an object.
    at FluentFTP.AsyncFtpClient.Execute(String command, CancellationToken token)
    at FluentFTP.AsyncFtpClient.GetFileSizeInternal(String path, Int64 defaultValue, CancellationToken token, FtpSizeReply sizeReply)
    at FluentFTP.AsyncFtpClient.FileExists(String path, CancellationToken token)
    at FluentFTP.AsyncFtpClient.UploadFileInternalAsync(Stream fileData, String localPath, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress, CancellationToken token, FtpProgress metaProgress)
    --- End of inner exception stack trace ---
    at FluentFTP.AsyncFtpClient.UploadFileInternalAsync(Stream fileData, String localPath, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress, CancellationToken token, FtpProgress metaProgress)
    at FluentFTP.AsyncFtpClient.UploadBytes(Byte[] fileData, String remotePath, FtpRemoteExists existsMode, Boolean createRemoteDir, IProgress`1 progress, CancellationToken token)
    at Program.<Main>$(String[] args) in C:\Data\src\Demo\FluentFtpBug\Program.cs:line 124
    at Program.<Main>(String[] args)
``` 

**Logs from FluentFTP:**

```
# AutoConnect()

# AutoDetect(True, False)

# ConnectAsync()
Status:   FluentFTP 42.1.0.0
Status:   Connecting to IP #1= ***:21
Status:   Waiting for a response
Response: 220 (vsFTPd 3.0.3)
Status:   Detected FTP server: VsFTPd
Command:  AUTH TLS
Status:   Waiting for response to: AUTH TLS
Response: 530 Please login with USER and PASS.
Command:  USER ***
Status:   Waiting for response to: USER ***
Response: 331 Please specify the password.
Command:  PASS ***
Status:   Waiting for response to: PASS ***
Response: 230 Login successful.
Command:  FEAT
Status:   Waiting for response to: FEAT
Response: 211-Features:
Response: EPRT
Response: EPSV
Response: MDTM
Response: PASV
Response: REST STREAM
Response: SIZE
Response: TVFS
Response: 211 End
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Status:   Waiting for response to: OPTS UTF8 ON
Response: 200 Always in UTF8 mode.
Command:  SYST
Status:   Waiting for response to: SYST
Response: 215 UNIX Type: L8
Status:   Listing parser set to: Unix
Command:  PWD
Status:   Waiting for response to: PWD
Response: 257 "/" is the current directory
connected
upload 1

# UploadBytes("file/test1.txt", Overwrite, True)

# FileExists("file/test1.txt")
Command:  SIZE /file/test1.txt
Status:   Waiting for response to: SIZE /file/test1.txt
Response: 213 12

# DeleteFile("file/test1.txt")
Command:  DELE file/test1.txt
Status:   Waiting for response to: DELE file/test1.txt
Response: 250 Delete operation successful.

# OpenWrite("file/test1.txt", Binary)
Command:  TYPE I
Status:   Waiting for response to: TYPE I
Response: 200 Switching to Binary mode.

# OpenPassiveDataStreamAsync(PASV, "STOR file/test1.txt", 0)
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (127,0,0,1,106,47).
Status:   Connecting to IP #1= ***:27183
Command:  STOR file/test1.txt
Status:   Waiting for response to: STOR file/test1.txt
Response: 150 Ok to send data.
Status:   Uploaded 12 bytes
Status:   Disposing FtpSocketStream(data connection)
Status:   Waiting for response to: *UPLOAD*
Response: 226 Transfer complete.
delay expired
upload 2

# UploadBytes("file/test2.txt", Overwrite, True)

# FileExists("file/test2.txt")
Status:   Socket has stale data - prior to command execution
Status:   The stale data was:
Stale:    421 Timeout.
Status:   Reconnect due to stale data
Status:   Disposing FtpSocketStream(control connection)
Command:  SIZE /file/test2.txt
Unhandled exception. FluentFTP.FtpException: Error while uploading the file to the server. See InnerException for more info.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at FluentFTP.AsyncFtpClient.Execute(String command, CancellationToken token)
   at FluentFTP.AsyncFtpClient.GetFileSizeInternal(String path, Int64 defaultValue, CancellationToken token, FtpSizeReply sizeReply)
   at FluentFTP.AsyncFtpClient.FileExists(String path, CancellationToken token)
   at FluentFTP.AsyncFtpClient.UploadFileInternalAsync(Stream fileData, String localPath, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress, CancellationToken token, FtpProgress metaProgress)
   --- End of inner exception stack trace ---
   at FluentFTP.AsyncFtpClient.UploadFileInternalAsync(Stream fileData, String localPath, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress, CancellationToken token, FtpProgress metaProgress)
   at FluentFTP.AsyncFtpClient.UploadBytes(Byte[] fileData, String remotePath, FtpRemoteExists existsMode, Boolean createRemoteDir, IProgress`1 progress, CancellationToken token)
   at Program.<Main>$(String[] args) in C:\Data\src\Demo\FluentFtpBug\Program.cs:line 126
   at Program.<Main>(String[] args)
```

**Comment by FanDjango** [comment]
> The synchronous FtpClient works fine.

Would it be possible to show the log also for the sync case? I'd like to compare.

In those case where your code would want to check, you could use `IsConnected`, could you not?

V42.1.0 should reconnect successfully, **so we are looking for a bug here**. I'll try to reproduce this here, also.

'KeepAlive' is generally a difficult topic, see the Wiki article on [`NOOP`](https://github.com/robinrodricks/FluentFTP/wiki/Noop), especially the link to "[Keep Alive Techniques in general](http://www.proftpd.org/docs/howto/KeepAlives.html).

We don't currently support sending `NOOP` commands when idle - only when transfers are running. Shouldn't really be a problem, as the automatic reconnect should do the job ok.

**Comment by FanDjango** [comment]
Successfully reproduced, working on fix.

**Comment by FanDjango** [comment]
Please check the current master - I have merged a fix for your problem.

**Comment by MurmelNash** [comment]
Thanks for the quick reply and the provided fix. 
I can confirm that the fix solves the problem. The logs depict now the expected reconnect followed by the successful second upload.
Great :-)
