### ISSUE TITLE
Does FluentFTP Work in Blazor WASM?

### ISSUE THREAD

**Issue by AFranklin520** [robinrodricks/FluentFTP#1233]
Hello, I am trying to connect to my FTP server remotely with a Blazor WASM app. The following error appears in the browser:

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: System.Security.Cryptography.X509Certificates is not supported on this platform.
System.PlatformNotSupportedException: System.Security.Cryptography.X509Certificates is not supported on this platform.
   at System.Security.Cryptography.X509Certificates.X509CertificateCollection..ctor()
   at FluentFTP.FtpConfig..ctor()
   at FluentFTP.Client.BaseClient.BaseFtpClient..ctor(FtpConfig config)
   at FluentFTP.FtpClient..ctor(String host, String user, String pass, Int32 port, FtpConfig config, IFtpLogger logger)

Is there any work around to this yet or can you tell me how/whether what I want to do is possible, please?
Thanks!

**Comment by robinrodricks** [comment]
We have no plans to support Blazor/WASM.
