### ISSUE TITLE
DirectoryExists fails due to no CWD command

### ISSUE THREAD

**Issue by loftyinclination** [robinrodricks/FluentFTP#1268]
**FTP Server OS:** Embedded

**FTP Server Type:** Unknown
**Client Computer OS:** Windows

**FluentFTP Version:** 46.0.2

**Framework:** .NET 6

Attempting to download a directory from a unix server, and the operation is failing because the server does not have a CWD command?

**Logs :**

```

2023-05-15 17:37:51.979 +01:00 [INF] >         Connect(False)
2023-05-15 17:37:51.985 +01:00 [DBG] FluentFTP 46.0.2.0
2023-05-15 17:37:52.001 +01:00 [INF] Connecting to IP #1= ***:51208
2023-05-15 17:37:52.058 +01:00 [DBG] Waiting for a response
2023-05-15 17:37:52.088 +01:00 [INF] Response: 220 (vsFTPd 3.0.2) [738654.693d]
2023-05-15 17:37:52.108 +01:00 [INF] Status:   Detected FTP server: VsFTPd
2023-05-15 17:37:52.119 +01:00 [INF] Command:  USER ***
2023-05-15 17:37:52.126 +01:00 [DBG] Waiting for response to: USER ***
2023-05-15 17:37:52.155 +01:00 [INF] Response: 230 Login successful. [31ms]
2023-05-15 17:37:52.165 +01:00 [INF] Command:  FEAT
2023-05-15 17:37:52.166 +01:00 [DBG] Waiting for response to: FEAT
2023-05-15 17:37:52.200 +01:00 [DBG] Response: 211-Features:
Response: EPRT
Response: EPSV
Response: MDTM
Response: PASV
Response: REST STREAM
Response: SIZE
Response: TVFS
2023-05-15 17:37:52.200 +01:00 [INF] Response: 211 End [34ms]
2023-05-15 17:37:52.219 +01:00 [INF] Text encoding: System.Text.ASCIIEncoding+ASCIIEncodingSealed
2023-05-15 17:37:52.219 +01:00 [INF] Command:  SYST
2023-05-15 17:37:52.219 +01:00 [DBG] Waiting for response to: SYST
2023-05-15 17:37:52.247 +01:00 [INF] Response: 215 UNIX Type: L8 [27ms]
2023-05-15 17:37:52.257 +01:00 [DBG] Listing parser set to: Unix
2023-05-15 17:37:52.260 +01:00 [INF] Command:  PWD
2023-05-15 17:37:52.260 +01:00 [DBG] Waiting for response to: PWD
2023-05-15 17:37:52.294 +01:00 [INF] Response: 257 "/" [33ms]
2023-05-15 17:37:52.305 +01:00 [INF] >         DownloadDirectory("C:\User\test\Downloads\", "/var/ftp/usrflash/", Update, Skip, None, null)
2023-05-15 17:37:52.308 +01:00 [INF] >         DirectoryExists("/var/ftp/usrflash")
2023-05-15 17:37:52.315 +01:00 [INF] Command:  CWD /var/ftp/usrflash
2023-05-15 17:37:52.315 +01:00 [DBG] Waiting for response to: CWD /var/ftp/usrflash
2023-05-15 17:37:52.343 +01:00 [INF] Response: 550 Failed to change directory. [27ms]
2023-05-15 17:37:52.348 +01:00 [ERR] Server: Error when trying to download directory: /var/ftp/usrflash.
FluentFTP.Exceptions.FtpMissingObjectException: Cannot download non-existant directory: /var/ftp/usrflash/
   at FluentFTP.AsyncFtpClient.DownloadDirectory(String localFolder, String remoteFolder, FtpFolderSyncMode mode, FtpLocalExists existsMode, FtpVerify verifyOptions, List`1 rules, IProgress`1 progress, CancellationToken token)
   at FtpService.DownloadDirectoryAsync(String remoteFolder, String localFolder, CancellationToken cancellationToken) in .\FtpService.cs:line 221
```

**Comment by robinrodricks** [comment]
So then find us an alternate command and we will see what we can do.

**Comment by loftyinclination** [comment]
Is there a reason that just cd doesnt work?

**Comment by FanDjango** [comment]
Who says "CWD" does not work? 

`CWD /var/ftp/usrflash` fails. No one said it doesn't work. Proof it can't CWD? Try a setworkingdierectory to "/" to check, first.

**Comment by loftyinclination** [comment]
Yeah, fair enough -- miscommunication on my end. according to our engineer; "the ftp credentials set root to /var/ftp/ already, so paths need to be local to that"

Sorry for the confusion!

**Comment by FanDjango** [comment]
No problem. 

We use CWD 's inability to go somewhere, to check it the "somewhere" exists. 

That is a tricky way to check if a directory download is possible.

We are just perpetually worried that maybe the "message needs to be improved".
