### ISSUE TITLE
Unable to list content from directory with space

### ISSUE THREAD

**Issue by jfrondeau** [robinrodricks/FluentFTP#1269]
**FTP Server OS:** Unix

**FTP Server Type:**  Don't know

**Client Computer OS:** Windows

**FluentFTP Version: 46.0.2

**Framework:** .NET 7

Unable to List directory that include space in name. Exception is throw. 
Tried to encode space in the directory name  with "+" or "%20". That way no exeption is throw, but listing is empty. 

Listing is not empty when using WinSCP ftp client.

```
try
{
    var client = new FtpClient(ftpConfig.Url, ftpConfig.Username, ftpConfig.Password);
    client.Config.LogToConsole = true;
    client.AutoConnect();

    var listes = client.GetListing();

    var exist = client.DirectoryExists(ftpConfig.RemoteDirectoryName);
    if(exist)
    {
        logger.LogInformation("Directory '{dir}' exist", ftpConfig.RemoteDirectoryName);
        listes = client.GetListing(ftpConfig.RemoteDirectoryName);
    }
}
catch (Exception ex)
{
    logger.LogError(ex, "Oups");
}
```

**Logs :**

```

# AutoConnect()

# AutoDetect(True, False)

# Connect(False)
Status:   FluentFTP 46.0.2.0
Status:   Connecting to IP #1= ***:21
Status:   Waiting for a response
Response: 220 redacted X2 WS_FTP Server 8.7.3(11459306) [738655,652d]
Status:   Detected FTP server: WSFTP
Command:  AUTH TLS
Status:   Waiting for response to: AUTH TLS
Response: 504 unknown security mechanism [21ms]
Command:  USER ***
Status:   Waiting for response to: USER ***
Response: 331 Enter password [37ms]
Command:  PASS ***
Status:   Waiting for response to: PASS ***
Response: 230 User logged in [54ms]
Command:  FEAT
Status:   Waiting for response to: FEAT
Response: 211-Extensions supported
Response: SIZE
Response: XMD5
Response: XSHA1
Response: XSHA256
Response: XSHA512
Response: XQUOTA
Response: LANG EN, ES, FR, GE
Response: MDTM
Response: MLST size*;type*;perm*;create*;modify*;
Response: REST STREAM
Response: TVFS
Response: UTF8
Response: AUTH SSL;TLS-P;
Response: PBSZ
Response: PROT C;P;
Response: 211 end [22ms]
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Status:   Waiting for response to: OPTS UTF8 ON
Response: 200 Command OPTS succeed [28ms]
Command:  SYST
Status:   Waiting for response to: SYST
Response: 215 UNIX [22ms]
Status:   Listing parser set to: Machine
Command:  PWD
Status:   Waiting for response to: PWD
Response: 257 "/users/redacted" is current directory [21ms]

# GetListing(null, Auto)
Command:  TYPE I
Status:   Waiting for response to: TYPE I
Response: 200 Transfer mode set to BINARY [19ms]

# OpenDataStream("MLSD /users/redacted", 0)

# OpenPassiveDataStream(PASV, "MLSD /users/redacted", 0)
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (198,33,104,52,23,167). [22ms]
Status:   Connecting to IP #1= ***:6055
Command:  MLSD /users/redacted
Status:   Waiting for response to: MLSD /users/redacted
Response: 150 Transferring directory [37ms]
+---------------------------------------+
Listing:  size=0;type=cdir;create=20221121095031;modify=20221121095031; .
Listing:  size=0;type=pdir;create=20220318112457;modify=20230512170724; ..
Listing:  size=0;type=dir;create=20151031000250;modify=20230505142647; address data-donnees adresses
-----------------------------------------
Status:   Closing/Disposing FtpSocketStream(data connection)

# CloseDataStream()
Status:   Waiting for response to: MLSD /users/redacted
Response: 226 Transfer completed [154ms]
Status:   Closing/Disposing FtpSocketStream(data connection)

# DirectoryExists("address data-donnees adresses")
Command:  CWD address data-donnees adresses
Status:   Waiting for response to: CWD address data-donnees adresses
Response: 250 Command CWD succeed [41ms]
Command:  PWD
Status:   Waiting for response to: PWD
Response: 257 "/users/redacted/address data-donnees adresses" is current directory [21ms]
Command:  CWD /users/redacted
Status:   Waiting for response to: CWD /users/redacted
Response: 250 Command CWD succeed [31ms]
Command:  PWD
Status:   Waiting for response to: PWD
Response: 257 "/users/redacted" is current directory [21ms]
info: Api.CodePostaux.FtpService[0]
      Directory address data-donnees adresses exist

# GetListing("address data-donnees adresses", Auto)

# OpenDataStream("MLSD /users/redacted/address data-donnees adresses", 0)

# OpenPassiveDataStream(PASV, "MLSD /users/redacted/address data-donnees adresses", 0)
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (198,33,104,52,23,170). [21ms]
Status:   Connecting to IP #1= ***:6058
Command:  MLSD /users/redacted/address data-donnees adresses
Status:   Waiting for response to: MLSD /users/redacted/address data-donnees adresses
Response: 501 Invalid number of arguments MLSD /users/redacted/address data-donnees adresses [29ms]
Status:   Closing/Disposing FtpSocketStream(data connection)

# CloseDataStream()
fail: Api.CodePostaux.FtpService[0]
      Oups
      FluentFTP.Exceptions.FtpCommandException: Code: 501 Message: Invalid number of arguments MLSD /users/redacted/address data-donnees adresses
         at FluentFTP.FtpClient.GetListingInternal(String listcmd, FtpListOption options, Boolean retry)
         at FluentFTP.FtpClient.GetListing(String path, FtpListOption options)
         at FluentFTP.FtpClient.GetListing(String path)
         at Api.CodePostaux.FtpService.GetFileList()

```

**Comment by FanDjango** [comment]
The server is WS FTP (I think IPSWITCH is the company).

Anyway:

```
501 Invalid number of arguments MLSD /users/redacted/address data-donnees adresses [29ms]
```
Server implementation of the MLSD command does **not support blanks**.

If you use 
```cs
"\"address data-donnees adresses\""
```
can you provide a log?

Also, you can choose to not use MLSD but LIST instead by trying out FtpListOpion.LIST, perhaps.

**Comment by jfrondeau** [comment]
Not working either. I tryed to CWD into directory, wich worked, but callind GetListing() without parameter throw exception. T
Here is update code and log. 

```
try
            {
                var client = new FtpClient(ftpConfig.Url, ftpConfig.Username, ftpConfig.Password);
                client.Config.LogToConsole = true;
                client.AutoConnect();

                var listes = client.GetListing();

                if (client.DirectoryExists($"\"{ftpConfig.RemoteDirectoryName}\""))
                {
                    logger.LogInformation("Directory '{dir}' exist", ftpConfig.RemoteDirectoryName);
                }

                //var t1 = client.GetListing(ftpConfig.RemoteDirectoryName);
                var t2 = client.GetListing($"\"{ftpConfig.RemoteDirectoryName}\"");
                var t3 = client.GetListing($"\\\"{ftpConfig.RemoteDirectoryName}\"");
                var t4 = client.GetListing(WebUtility.UrlEncode(ftpConfig.RemoteDirectoryName));
                var t5 = client.GetListing(HttpUtility.UrlPathEncode(ftpConfig.RemoteDirectoryName));
                var t6 = client.GetNameListing($"\"{ftpConfig.RemoteDirectoryName}\"");
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Oups");
            }
```

Logs:

```
# AutoConnect()

# AutoDetect(True, False)

# Connect(False)
Status:   FluentFTP 46.0.2.0
Status:   Connecting to IP #1= ***:21
Status:   Waiting for a response
Response: 220 redated X2 WS_FTP Server 8.7.3(57861244) [738655,733d]
Status:   Detected FTP server: WSFTP
Command:  AUTH TLS
Status:   Waiting for response to: AUTH TLS
Response: 504 unknown security mechanism [26ms]
Command:  USER ***
Status:   Waiting for response to: USER ***
Response: 331 Enter password [29ms]
Command:  PASS ***
Status:   Waiting for response to: PASS ***
Response: 230 User logged in [54ms]
Command:  FEAT
Status:   Waiting for response to: FEAT
Response: 211-Extensions supported
Response: SIZE
Response: XMD5
Response: XSHA1
Response: XSHA256
Response: XSHA512
Response: XQUOTA
Response: LANG EN, ES, FR, GE
Response: MDTM
Response: MLST size*;type*;perm*;create*;modify*;
Response: REST STREAM
Response: TVFS
Response: UTF8
Response: AUTH SSL;TLS-P;
Response: PBSZ
Response: PROT C;P;
Response: 211 end [24ms]
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Status:   Waiting for response to: OPTS UTF8 ON
Response: 200 Command OPTS succeed [18ms]
Command:  SYST
Status:   Waiting for response to: SYST
Response: 215 UNIX [20ms]
Status:   Listing parser set to: Machine
Command:  PWD
Status:   Waiting for response to: PWD
Response: 257 "/users/redacted" is current directory [20ms]

# GetListing(null, Auto)
Command:  TYPE I
Status:   Waiting for response to: TYPE I
Response: 200 Transfer mode set to BINARY [20ms]

# OpenDataStream("MLSD /users/redacted", 0)

# OpenPassiveDataStream(PASV, "MLSD /users/redacted", 0)
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (198,33,104,52,20,54). [24ms]
Status:   Connecting to IP #1= ***:5174
Command:  MLSD /users/redacted
Status:   Waiting for response to: MLSD /users/redacted
Response: 150 Transferring directory [36ms]
+---------------------------------------+
Listing:  size=0;type=cdir;create=20221121095031;modify=20221121095031; .
Listing:  size=0;type=pdir;create=20220318112457;modify=20230512170724; ..
Listing:  size=0;type=dir;create=20151031000250;modify=20230505142647; address data-donnees adresses
-----------------------------------------
Status:   Closing/Disposing FtpSocketStream(data connection)

# CloseDataStream()
Status:   Waiting for response to: MLSD /users/redacted
Response: 226 Transfer completed [157ms]
Status:   Closing/Disposing FtpSocketStream(data connection)

# DirectoryExists(""address data-donnees adresses"")
Command:  CWD "address data-donnees adresses"
Status:   Waiting for response to: CWD "address data-donnees adresses"
Response: 250 Command CWD succeed [34ms]
Command:  PWD
Status:   Waiting for response to: PWD
Response: 257 "/users/redacted/address data-donnees adresses" is current directory [64ms]
Command:  CWD /users/redacted
Status:   Waiting for response to: CWD /users/redacted
Response: 250 Command CWD succeed [39ms]
Command:  PWD
Status:   Waiting for response to: PWD
Response: 257 "/users/redacted" is current directory [22ms]
info: Api.CodePostaux.FtpService[0]
      Directory 'address data-donnees adresses' exist

# GetListing(""address data-donnees adresses"", Auto)

# OpenDataStream("MLSD /users/redacted/"address data-donnees adresses"", 0)

# OpenPassiveDataStream(PASV, "MLSD /users/redacted/"address data-donnees adresses"", 0)
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (198,33,104,52,20,55). [26ms]
Status:   Connecting to IP #1= ***:5175
Command:  MLSD /users/redacted/"address data-donnees adresses"
Status:   Waiting for response to: MLSD /users/redacted/"address data-donnees adresses"
Response: 150 Transferring directory [45ms]
+---------------------------------------+
-----------------------------------------
Status:   Closing/Disposing FtpSocketStream(data connection)

# CloseDataStream()
Status:   Waiting for response to: MLSD /users/redacted/"address data-donnees adresses"
Response: 226 Transfer completed [56ms]
Status:   Closing/Disposing FtpSocketStream(data connection)

# GetListing("/"address data-donnees adresses"", Auto)

# OpenDataStream("MLSD /"address data-donnees adresses"", 0)

# OpenPassiveDataStream(PASV, "MLSD /"address data-donnees adresses"", 0)
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (198,33,104,52,20,56). [22ms]
Status:   Connecting to IP #1= ***:5176
Command:  MLSD /"address data-donnees adresses"
Status:   Waiting for response to: MLSD /"address data-donnees adresses"
Response: 150 Transferring directory [37ms]
+---------------------------------------+
-----------------------------------------
Status:   Closing/Disposing FtpSocketStream(data connection)

# CloseDataStream()
Status:   Waiting for response to: MLSD /"address data-donnees adresses"
Response: 226 Transfer completed [44ms]
Status:   Closing/Disposing FtpSocketStream(data connection)

# GetListing("address+data-donnees+adresses", Auto)

# OpenDataStream("MLSD /users/redacted/address+data-donnees+adresses", 0)

# OpenPassiveDataStream(PASV, "MLSD /users/redacted/address+data-donnees+adresses", 0)
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (198,33,104,52,20,57). [27ms]
Status:   Connecting to IP #1= ***:5177
Command:  MLSD /users/redacted/address+data-donnees+adresses
Status:   Waiting for response to: MLSD /users/redacted/address+data-donnees+adresses
Response: 150 Transferring directory [52ms]
+---------------------------------------+
-----------------------------------------
Status:   Closing/Disposing FtpSocketStream(data connection)

# CloseDataStream()
Status:   Waiting for response to: MLSD /users/redacted/address+data-donnees+adresses
Response: 226 Transfer completed [59ms]
Status:   Closing/Disposing FtpSocketStream(data connection)

# GetListing("address%20data-donnees%20adresses", Auto)

# OpenDataStream("MLSD /users/redacted/address%20data-donnees%20adresses", 0)

# OpenPassiveDataStream(PASV, "MLSD /users/redacted/address%20data-donnees%20adresses", 0)
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (198,33,104,52,20,58). [24ms]
Status:   Connecting to IP #1= ***:5178
Command:  MLSD /users/redacted/address%20data-donnees%20adresses
Status:   Waiting for response to: MLSD /users/redacted/address%20data-donnees%20adresses
Response: 150 Transferring directory [46ms]
+---------------------------------------+
-----------------------------------------
Status:   Closing/Disposing FtpSocketStream(data connection)

# CloseDataStream()
Status:   Waiting for response to: MLSD /users/redacted/address%20data-donnees%20adresses
Response: 226 Transfer completed [56ms]
Status:   Closing/Disposing FtpSocketStream(data connection)

# GetNameListing(""address data-donnees adresses"")

# OpenDataStream("NLST /users/redacted/"address data-donnees adresses"", 0)

# OpenPassiveDataStream(PASV, "NLST /users/redacted/"address data-donnees adresses"", 0)
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (198,33,104,52,20,59). [27ms]
Status:   Connecting to IP #1= ***:5179
Command:  NLST /users/redacted/"address data-donnees adresses"
Status:   Waiting for response to: NLST /users/redacted/"address data-donnees adresses"
Response: 150 Transferring directory [48ms]
+---------------------------------------+
Status:   Closing/Disposing FtpSocketStream(data connection)

# CloseDataStream()
Status:   Waiting for response to: NLST /users/redacted/"address data-donnees adresses"
Response: 226 Transfer completed [63ms]
+---------------------------------------+
Status:   Closing/Disposing FtpSocketStream(data connection)
Command:  CWD /users/redacted/address data-donnees adresses
Status:   Waiting for response to: CWD /users/redacted/address data-donnees adresses
Response: 250 Command CWD succeed [40ms]
Command:  PWD
Status:   Waiting for response to: PWD
Response: 257 "/users/redacted/address data-donnees adresses" is current directory [21ms]

# GetListing(null, Auto)

# OpenDataStream("MLSD /users/redacted/address data-donnees adresses", 0)

# OpenPassiveDataStream(PASV, "MLSD /users/redacted/address data-donnees adresses", 0)
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (198,33,104,52,20,60). [19ms]
Status:   Connecting to IP #1= ***:5180
Command:  MLSD /users/redacted/address data-donnees adresses
Status:   Waiting for response to: MLSD /users/redacted/address data-donnees adresses
Response: 501 Invalid number of arguments MLSD /users/redacted/address data-donnees adresses [30ms]
Status:   Closing/Disposing FtpSocketStream(data connection)

# CloseDataStream()
fail: Api.CodePostaux.FtpService[0]
      Oups
      FluentFTP.Exceptions.FtpCommandException: Code: 501 Message: Invalid number of arguments MLSD /users/redacted/address data-donnees adresses
         at FluentFTP.FtpClient.GetListingInternal(String listcmd, FtpListOption options, Boolean retry)
         at FluentFTP.FtpClient.GetListing(String path, FtpListOption options)
         at FluentFTP.FtpClient.GetListing()
         at Api.CodePostaux.FtpService.GetFileList() in C:\SVN\Api.CodePostaux\src\Api\FtpService.cs:line 54
```

**Comment by FanDjango** [comment]
```cs
...SetWorkingDirectory("/users");
...SetWorkingDirectory("redacted");
...SetWorkingDirectory("\"address data-donnees address\"");
```
or
```cs
...SetWorkingDirectory("\"/users/redacted/address data-donnees address\"");
```
Goal: Get to the place where you want to do the listing.

Then:
```cs
...GetListing("", FtpListOption.Nopath);   // consider adding FtpListOption.List if MLSD still misbehaves
```
Goal: cause the list to take place with no wrong pathname quoting.

Alternative (from root directory):

```cs
...GetListing(""\"/users/redacted/address data-donnees address\""); // again perhaps FtpListOption.List
```
Goal: cause correct quoting.

Sorry I can't test it right now from this hotel room, no machine available. But I am pretty sure there is a way in this fashion.

**Comment by FanDjango** [comment]
For the "CWD - GetListing("") method, the FtpListOption.NoPath **est essentiel**

For the direct method, correct quoting is possible to achieve also.

**Comment by FanDjango** [comment]
Thanks for the good documentation and problem description.

**Comment by FanDjango** [comment]
> address%20data-donnees%20adresses

This one is **actually a very good idea/try**. **Some** FTP server will understand that way of escaping (because that's what it is) strings, borrowed from HTTP URI representation way. Sadly, WS FTP does not look like he is happy :-)

**Comment by jfrondeau** [comment]
Using WebRequest is working for the same ftp server. Don't need to escape space. Setting the url like I do make .Net login then change directory (from [MS doc](https://learn.microsoft.com/en-us/dotnet/api/system.net.ftpwebrequest?devlangs=csharp&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(System.Net.FtpWebRequest)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=net-7.0#remarks) )

> The URI may be relative or absolute. If the URI is of the form "ftp://contoso.com/%2fpath" (%2f is an escaped '/'), then the URI is absolute, and the current directory is /path. If, however, the URI is of the form "ftp://contoso.com/path", first the .NET Framework logs into the FTP server (using the user name and password set by the [Credentials](https://learn.microsoft.com/en-us/dotnet/api/system.net.ftpwebrequest.credentials?view=net-7.0) property), then the current directory is set to <UserLoginDirectory>/path. 

Code:
```
string url = $"ftp://{ftpConfig.Url}{ftpConfig.RemoteDirectoryName}";
logger.LogInformation("Url is '{}'", url);

FtpWebRequest request = (FtpWebRequest)WebRequest.Create(url);
request.Credentials = new NetworkCredential(ftpConfig.Username, ftpConfig.Password);
request.Method = WebRequestMethods.Ftp.ListDirectoryDetails;

using FtpWebResponse listResponse = (FtpWebResponse)request.GetResponse();
using Stream listStream = listResponse.GetResponseStream();
using StreamReader listReader = new StreamReader(listStream);

while (!listReader.EndOfStream)
{
    var ligne = listReader.ReadLine();
    logger.LogInformation(ligne);
}
```
Logs:
```
info: Api.CodePostaux.FtpService[0]
      Url is 'ftp://redacted/address data-donnees adresses'
info: Api.CodePostaux.FtpService[0]
      dr-x------  2 user   System            0 May 05 14:26 .
info: Api.CodePostaux.FtpService[0]
      dr-x------  2 user   System            0 Feb 14  2022 ..
info: Api.CodePostaux.FtpService[0]
      -r-x------  1 user   System        65543 Nov 23  2022 2023 - Calendrier de production donnees.pdf
info: Api.CodePostaux.FtpService[0]
      -r-x------  1 user   System        64118 Nov 23  2022 2023 - Data Production Schedule.pdf
info: Api.CodePostaux.FtpService[0]
      -r-x------  1 user   System     29704748 Apr 07  2023 230407ad.zip
info: Api.CodePostaux.FtpService[0]
      -r-x------  1 user   System     29760211 May 05 14:26 230505ad.zip
info: Api.CodePostaux.FtpService[0]
      -r-x------  1 user   System       273003 Feb 12  2020 PCAD_SPEC_E_2019.pdf
info: Api.CodePostaux.FtpService[0]
      -r-x------  1 user   System       294741 Feb 12  2020 PCAD_SPEC_F_2019.pdf
```

**Comment by FanDjango** [comment]
Yes, but in this case you don't see the actual server FTP commands that WebRequest is now making for you - he is translating the URI and then he is sending a MLSD command, whose contents he is not showing to you. You could see it in a WireShark trace. FluenFTP **does it more directly**, not with URIs. 

If the server understands the %20, some do, that is fine. But many don't.

WebRequest takes your URI and then it translates it to the right commands to FTP.

**Comment by FanDjango** [comment]
So, I am back in the office and can test for you:

Using this code:
```cs
				client.AutoConnect();

				client.SetWorkingDirectory("/home/mike/[].folder/dia grams");
				var item1 = client.GetListing("", FtpListOption.NoPath | FtpListOption.ForceList);

				var item2 = client.GetListing("\"/home/mike/[].folder/dia grams\"", FtpListOption.NoPath | FtpListOption.ForceList);

				var item3 = client.GetListing("/home/mike/[].folder/dia grams", FtpListOption.ForceList);

				client.Disconnect();
```

I get:

Note: This is ProFTPd. It accepts but does not need quotes around the **entire** parms of the commands.

**FtpListOption.NoPath** and, sometimes, **FtpListOption.ForceList** are your friends.

```
>         SetWorkingDirectory("/home/mike/[].folder/dia grams")
Command:  CWD /home/mike/[].folder/dia grams
Status:   Waiting for response to: CWD /home/mike/[].folder/dia grams
Response: 250 CWD command successful [<1ms]
Command:  PWD
Status:   Waiting for response to: PWD
Response: 257 "/home/mike/[].folder/dia grams" is the current directory [<1ms]
>         GetListing("", ForceList, NoPath)
Command:  TYPE I
Status:   Waiting for response to: TYPE I
Response: 200 Type set to I [<1ms]
>         OpenDataStream("LIST", 0)
>         OpenPassiveDataStream(PASV, "LIST", 0)
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (192,168,1,109,142,39). [1ms]
Status:   PASV advertised a non-routable IPAD. Using original connect dnsname/IPAD
Status:   Connecting to IP #1= ***:36391
Command:  LIST
Status:   Waiting for response to: LIST
Response: 150 Opening BINARY mode data connection for file list [<1ms]
Status:   FTPS authentication successful, lib = FluentFTP.GnuTLS.GnuTlsStream, cipher suite = (TLS1.3)-(ECDHE-PSK-SECP256R1)-(AES-256-GCM) [7ms]
+---------------------------------------+
Listing:  drwxr-xr-x   2 mike     mike         4096 Sep 19  2022 old
-----------------------------------------
Status:   Closing/Disposing FtpSocketStream(data connection)
>         CloseDataStream()
Status:   Waiting for response to: LIST
Response: 226 Transfer complete [17ms]
Status:   Closing/Disposing FtpSocketStream(data connection)
Status:   Detected format Unix
>         GetListing(""/home/mike/[].folder/dia grams"", ForceList, NoPath)
>         OpenDataStream("LIST", 0)
>         OpenPassiveDataStream(PASV, "LIST", 0)
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (192,168,1,109,175,225). [<1ms]
Status:   PASV advertised a non-routable IPAD. Using original connect dnsname/IPAD
Status:   Connecting to IP #1= ***:45025
Command:  LIST
Status:   Waiting for response to: LIST
Response: 150 Opening BINARY mode data connection for file list [<1ms]
Status:   FTPS authentication successful, lib = FluentFTP.GnuTLS.GnuTlsStream, cipher suite = (TLS1.3)-(ECDHE-PSK-SECP256R1)-(AES-256-GCM) [14ms]
+---------------------------------------+
Listing:  drwxr-xr-x   2 mike     mike         4096 Sep 19  2022 old
-----------------------------------------
Status:   Closing/Disposing FtpSocketStream(data connection)
>         CloseDataStream()
Status:   Waiting for response to: LIST
Response: 226 Transfer complete [23ms]
Status:   Closing/Disposing FtpSocketStream(data connection)
>         GetListing("/home/mike/[].folder/dia grams", ForceList)
>         OpenDataStream("LIST /home/mike/[].folder/dia grams", 0)
>         OpenPassiveDataStream(PASV, "LIST /home/mike/[].folder/dia grams", 0)
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (192,168,1,109,151,89). [<1ms]
Status:   PASV advertised a non-routable IPAD. Using original connect dnsname/IPAD
Status:   Connecting to IP #1= ***:38745
Command:  LIST /home/mike/[].folder/dia grams
Status:   Waiting for response to: LIST /home/mike/[].folder/dia grams
Response: 150 Opening BINARY mode data connection for file list [<1ms]
Status:   FTPS authentication successful, lib = FluentFTP.GnuTLS.GnuTlsStream, cipher suite = (TLS1.3)-(ECDHE-PSK-SECP256R1)-(AES-256-GCM) [10ms]
+---------------------------------------+
Listing:  drwxr-xr-x   2 mike     mike         4096 Sep 19  2022 old
-----------------------------------------
Status:   Closing/Disposing FtpSocketStream(data connection)
>         CloseDataStream()
Status:   Waiting for response to: LIST /home/mike/[].folder/dia grams
Response: 226 Transfer complete [21ms]
Status:   Closing/Disposing FtpSocketStream(data connection)
Command:  QUIT
Status:   Waiting for response to: QUIT
Response: 221 Goodbye. [<1ms]
Status:   Closing/Disposing FtpSocketStream(control connection)
>         Dispose()
Status:   Disposing FtpClient object...
Status:   Closing/Disposing FtpSocketStream(control connection)
```

Even without the right quotes, ProFTPd **also works without** FtpListOption.ForceList", but WS_FTPd **does not**.

```
Command:  MLSD /home/mike/[].folder/dia grams
Status:   Waiting for response to: MLSD /home/mike/[].folder/dia grams
Response: 150 Opening BINARY mode data connection for MLSD [1ms]
Status:   FTPS authentication successful, lib = FluentFTP.GnuTLS.GnuTlsStream, cipher suite = (TLS1.3)-(ECDHE-PSK-SECP256R1)-(AES-256-GCM) [9ms]
+---------------------------------------+
Listing:  modify=20220919150659;perm=flcdmpe;type=pdir;unique=801U6003;UNIX.group=1000;UNIX.groupname=mike;UNIX.mode=0755;UNIX.owner=1000;UNIX.ownername=mike; ..
Listing:  modify=20220919150705;perm=flcdmpe;type=cdir;unique=801U210;UNIX.group=1000;UNIX.groupname=mike;UNIX.mode=0755;UNIX.owner=1000;UNIX.ownername=mike; .
Listing:  modify=20220919150733;perm=flcdmpe;type=dir;unique=801U42F;UNIX.group=1000;UNIX.groupname=mike;UNIX.mode=0755;UNIX.owner=1000;UNIX.ownername=mike; old
-----------------------------------------
```

**Comment by jfrondeau** [comment]
Sorry for the delay of my response.
Your exemple code is working for me. Get GetListing work with space in the directory name, even without using optionnal parameter. That is working when you SetWorkingDirectory before.

If I try from the root wihout SetWorkingDirectory, GetListing is not working, even with options set,
Can you try to client.GetListing("\"/home/mike/[].folder/dia grams\"", FtpListOption.NoPath | FtpListOption.ForceList); without using SetWorkingDirectory before?
And then try to do the same thing with a subdirectory that do not have space?

Thank you for your time.
