### ISSUE TITLE
FluentFTP.GnuTLS: Crash when multiple threads use GnuTlsStream

### ISSUE THREAD

**Issue by FanDjango** [robinrodricks/FluentFTP#1273]
Refer to #1272

Using it in parallel still leads to following exception though (on Dispose it seems)
```
Exit code is -1073741819 (Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at FluentFTP.GnuTLS.Core.GnuTls.GnuTlsCertificateFreeCredentials(IntPtr)
   at FluentFTP.GnuTLS.Core.CertificateCredentials.Dispose()
   at FluentFTP.GnuTLS.GnuTlsInternalStream.Dispose()
   at FluentFTP.GnuTLS.GnuTlsStream.Dispose()
   at FluentFTP.FtpSocketStream.Dispose(Boolean)
   at FluentFTP.FtpSocketStream.Close()
   at System.IO.Stream.Dispose()
   at FluentFTP.Client.BaseClient.BaseFtpClient.Dispose()
// rest omitted
```

**Comment by FanDjango** [comment]
FYI, my parallellisation test just looks something like this:

```
[Test]
public async Task Then_we_should_be_able_to_connect_and_list_files_in_parallel()
      {
          var factory = services.GetRequiredService<ICreateCasFtpClients>();

          await Task.WhenAll(Enumerable.Repeat(1, NumberOfAttempts).Select(async _ =>
          {
              using (var client = factory.Create(new FtpCredentials
              {
                  Host = "xxx",
                  User = "xxx",
                  Password = "xxx",
                  Protocol = FtpProtocol.Ftps,
                  ValidateCertificate = false,
                  UseGnuTlsForFtps = true,
                  GnuTlsDisableAlpn = true
              }))
              {

                await client.ConnectAsync();

                var result = await client.ListDirectoryAsync("/download");
                result.Should().NotBeNull();
              }
          }));
      }
```

**Comment by FanDjango** [comment]
Posted on behalf of @rob-hendrickx-c4t

Note that, as you can see in above snippet, every client is only used by 1 thread. But as you mentioned in the original issue, the fact that this stuff is shared statically probably is the root cause of it. So until that part is fixed, I assume the implementation is not safe for concurrent code. 

Do you happen to have a rough estimate on how long it could take before that is fixed (I fully understand it's not something that will be fixed straight away necessarily, and want to repeat that I'm amazed how fast the earlier fixes were handled)

**Comment by FanDjango** [comment]
Ok, I have looked into this.

Firstly, the entire inner structure of FluentFTP.GnuTLS is actually synchronous, as we state in the Wiki. I am overjoyed to see that it actually works well when internally "awaited" on via a `AsyncFtpClient(...)`.

So using FluentFTP.GnuTLS in an inherently async environment is not detrimental in itself. Users just need to beware of possible thread lockouts on operations that have timeouts.

GnuTLS **does** support async internally, it is just **so** much more involved (many more interop callbacks to marshal), it didn't seem worth a huge effort. Maybe someone will sit down and start coding, given the stuff that is already there as a starting point?

Why do I mention this? Well, it was the first worry when I saw your async multi thread setup.

I duplicated it and have identified a number of places where it currently fails. 

For example: I needed to serialize access to the log queue mechanism. There is only one global log queue.

But one of the other "places" is a **big** issue:

The base library wants an initial global init to setup its internal structures. After that it can be used in a thread safe fashion, for as long as you like. It then would like a global de-init to be able to dispose of its inner structures in a clean up.

Implementing this for a multi threaded use in an FTP client would mean exposing a global init (and deinit) for the user to call **before** he begins the actual use of the library as in creating ftp clients , using them and disposing them - de-init when he knows he is finished with the library.

These calls have no equivalent in an SslStream environment. FluentFTP (as the caller of FluentFTP.GnuTLS) has no knowledge of when to deinit the library. 

Currently this deinit is done when the control connection is terminated.

This whole Init/Deinit is sort of unclean and a hassle.

I have experimented just now with calling the global init on first use and completely neglecting to de-init - thereby I have successfully run 50 simultaneous threads doing a connect-disconnect with no errors.

That's a really good sign - it tells me there might be only a little bit left to tweak and bingo, problem solved.

Because when adding a GetListing call, it went "Boom" again, so this init/de-init hack would not yet be a viable (albeit "unclean") solution.

I ran into snags in the session resume logic and disposing of the credential data areas, so the whole thing would need some more work and debugging.

I really can't give you an estimate.

Linux, ASYNC (Phew, it works) **and** multi-threaded operations was sort of beyond the scope of the initial attempt to go beyond just SslStream as an option. And now look how far we have come.

I will spend some time with this to give you a better estimate, but currently I feel that there won't be a solution this week.

**Comment by FanDjango** [comment]
Ok, made a small breakthrough on this.

**If you accept** calling a _finalizer_ after the "everything" is finished, I think I have made the necessary changes to get thread-safety. 

I will work on this tomorrow and I would like to produce a branch for you (instead of a Nuget), that you could test in your environment,

I have got the Create_Client_Connect-GetListing-Disconnect_Dispose_Client litany running here with 50 enums_tasks in parallel and no hitch. Wonderful intertwined logging... Yippeee!

The only question remains: Probably will introduce a config option to decide wether the lib will dispose  and de-init on termination of the control connection or to defer until the _finalizer_ is invoked by the user. This also means, code is no longer **totally** the same between SslStream and GnuTlsStream - by the difference of one line of additional code to call the _finalizer_.

Might also need to introduce a thread-id in the logging format.

Please standby, out of the office tomorrow morning.

**Comment by rob-hendrickx-c4t** [comment]
@FanDjango Thanks for getting back so quickly.

I don't have a problem with doing something like that, I just wonder what you mean exactly with "everything is finished". Maybe to give some context for the majority of our usage of FluentFTP:
We have some function apps that on one hand upload files from time to time (triggered by a user action), and on the other hand periodically list & download files from FTP (roughly every 30 seconds). Since there's constant activity, do we even need to call the finalizer in that case? Or should it still be used after every "batch of operations" is handled?

Generally speaking, why & when does this need to happen, for which reason exactly?

For the time being, I'll see if I can temporarily use locking to prevent the issue from happening in our case (but making it more sequential again)

**Comment by FanDjango** [comment]
You've definitely got a point there - no need to finalize if you're ongoing.

I've another 400km, be home in about 2-3 hours depending on traffic, dinner and then let's see about making a test version for you...

I think we'll have this working by Friday.

**Comment by FanDjango** [comment]
@rob-hendrickx-c4t 
Ok, after some testing I actually feel quite confident to release this as 1.0.14. Have a go at it and see if it looks good for you.
Note the new config parameter to use: 
```cs
		/// <summary>
		/// Normally, the GnuTLS library is de-initialised after dispose of the control
		/// connection. If you plan to use the GnuTLS library functions in a multithreaded
		/// environment, you need to disable this behaviour by setting this to false. The
		/// library will NOT be de-initialised.
		/// </summary>
		public bool DeInitGnuTls { get; set; } = true;
```

**Comment by rob-hendrickx-c4t** [comment]
Hi @FanDjango 

I can confirm everything now works as expected, much appreciated!! Feel free to close the issue :)

**Comment by FanDjango** [comment]
Ok, closed. Thanks for the exemplary feedback and issue documentation, also for the timely tests and cooperation. It was a pleasure taking this input and improving the library.
