### ISSUE TITLE
A call to SSPI failed, System.Security.Authentication.AuthenticationException

### ISSUE THREAD

**Issue by zubo100** [robinrodricks/FluentFTP#1282]
**FTP Server OS:** Unix

**FTP Server Type:** Unknown

**Client Computer OS:** Windows 

**FluentFTP Version:** 45.2.0

**Framework:** .NET 2 / 6

Exception during transfer while using FTPS. Transfer sporadicaly throws the following exception show below. While transfering a higher number of files (in this case it was 94) 44 files were successfully transfered, before the exception was thrown. On the same day the trasnfer was retried again, and all 94 files were transfered correctly. Unfortunately I do not have a detailed verbose log available. 

**Logs :**

```

Unerwarteter Fehler: A call to SSPI failed, see inner exception. . StackTrace: System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The message or signature supplied for verification has been altered
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at FluentFTP.FtpSocketStream.ActivateEncryption(String targetHost, X509CertificateCollection clientCerts, SslProtocols sslProtocols)
   at FluentFTP.FtpClient.Connect(Boolean reConnect)

```
Could you please take a look at this. Any help or advice would be very much appreciated. If you need any more details, please just let me know, I will try provide as much information as I can, even though my access to the logs and servers is limited. 

Thank you!

**Comment by FanDjango** [comment]
Google:
"A call to SSPI failed, see inner exception"
and
"The message or signature supplied for verification has been altered"
doesn't offer much information.
The little I could find was that on a flaky connection with possible bursts of high latency, or a server that doesn't get the cpu, at critical moments in an encryption negotiation, this message will appear due to unexpected changes in parts of negotiation.

I would feel happier if you were using a more up-to-date version of FluentFTP.

You might also investigate if this behaviour improves if you migrate to adding/using FluentFTP.GnuTLS as an alternative to MS SslStream.
