### ISSUE TITLE
Copy Directory implemenation causing an error

### ISSUE THREAD

**Issue by Venkatakrishna-bvk** [robinrodricks/FluentFTP#1310]
Could you please provide Copy directory method implementation to copy from folder1 to folder2 in same ftp remote server.
When tried to copy folder in remote server paths it worked for few files and later encounter with errors such as below
i.e timeout trying to read data from socket 
And also getting an error sometimes : unable to read the data from  transport connection and an existing connection forcibly closed by remote host when having multiple files from folder 

I kindly request your assistance in providing a resolution for this matter.

**I tried to implement like below code:**
**copy directory implementation:**
```cs
 _ftpClient is IAsyncFtpClient .
await ConnectAsync()
await CopyFilesRecursivelyAsync(sourceRemotePath, destRemoatePath, CancellationToken cancellationToken = default)


private async Task CopyFilesRecursivelyAsync(string sourcePath, string destinationPath, CancellationToken cancellationToken = default)
	   {
		  var files = await _ftpClient.GetListing(sourcePath,  token: cancellationToken).ConfigureAwait(false);
		  foreach (var file in files)
		  {
			 if (file.Type == FtpObjectType.File)
			 {
				// Copy  file from the source remote server to the destination remote server
				var destinationFilePath = Path.Combine(destinationPath, file.Name);
				using (var sourceStream = await _ftpClient.OpenRead(file.FullName))
				using (var destinationStream = await _ftpClient.OpenWrite(destinationFilePath)) // tried with uploadstream as well
				{
				    await sourceStream.CopyToAsync(destinationStream);  // error after sometime timeout issue
				}
			 }
			 else if (file.Type == FtpObjectType.Directory)
			 {
				// Create the directory on the destination server
				var destinationDirPath = Path.Combine(destinationPath, file.Name);
 			        if (!await IsDirectoryExistsAsync(destinationDirPath).ConfigureAwait(false))
				    await CreateDirectoryAsync(destinationDirPath).ConfigureAwait(false); ;

 				await CopyFilesRecursivelyAsync(file.FullName, destinationDirPath).ConfigureAwait(false);
			 }
		  }
	   }
```

**Comment by robinrodricks** [comment]
Good idea.

**Comment by Venkatakrishna-bvk** [comment]
I have also tried with two ftpClients i.e source and destination remote client servers 
Below code works fine for around 50 files (each 60kb approx) of total 150 files and failed remaining files.
Error encounterd is "**### Timed out trying to read data from the socket stream**")
please let me know which property to increase timeout to avoid this error. 
I kindly request your assistance in providing a resolution for this matter.


**Implemented code with two ftpclients:**

using IAsyncFtpClient ftpClient1 = new AsyncFtpClient(ftpServer, username, password);
using IAsyncFtpClient ftpClient2 = new AsyncFtpClient(ftpServer, username, password);
		  if (!ftpClient1.IsConnected)
		  {
			 await ftpClient1.Connect();
//Also setting setworking directory
		  }
		  if (!ftpClient2.IsConnected)
		  {
			 await ftpClient2.Connect();
//Also setting setworking directory
		  }
 await CopyFilesRecursivelyAsync(ftpClient1, ftpClient2,remoteSourceDirPath, remoteDestDirPath).ConfigureAwait(false);


private async Task CopyFilesRecursivelyAsync(IAsyncFtpClient asyncFtpClient1, IAsyncFtpClient asyncFtpClient2, string sourcePath, string destinationPath)
    {
	   var files = await asyncFtpClient1.GetListing(sourcePath).ConfigureAwait(false);
	   foreach (var file in files)
	   {
		  if (file.Type == FtpObjectType.File)
		  {
			 // Copy  file from the source remote server to the destination remote server
		### 	 **var destinationFilePath = Path.Combine(destinationPath, file.Name);
			 await using (var sourceStream = await asyncFtpClient1.OpenRead(file.FullName).ConfigureAwait(false))
			 {
				await asyncFtpClient2.UploadStream(sourceStream, destinationFilePath, existsMode: FtpRemoteExists.Overwrite, createRemoteDir: true).ConfigureAwait(false);
			 };**
                 
		  }
		  else if (file.Type == FtpObjectType.Directory)
		  {
			 // Create the directory on the destination server
			 var destinationDirPath = Path.Combine(destinationPath, file.Name);
			 if (!await asyncFtpClient1.DirectoryExists(destinationDirPath).ConfigureAwait(false))
				await asyncFtpClient1.CreateDirectory(destinationDirPath).ConfigureAwait(false); ;
			 await CopyFilesRecursivelyAsync(asyncFtpClient1, asyncFtpClient2,file.FullName, destinationDirPath).ConfigureAwait(false);
		  }
	   }
    }

**Comment by FanDjango** [comment]
> And also getting an error sometimes : unable to read the data from transport connection and an existing connection forcibly closed by remote host when having multiple files from folder

Please provide a verbose log of this error.

**Comment by Venkatakrishna-bvk** [comment]
Error Logs: Hoping it might help below logs

FluentFTP.Exceptions.FtpException: Error while uploading the file to the server. See InnerException for more info.
---> System.AggregateException: Additional error occured while trying to resume uploading the file 'ftpfolder/dev/invoices-staging/bvk/copy3/20230704_28_SCC CSV file.8/Invoice4198.pdf' **at position 0 (Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..)** **(Malformed PASV response: 0)**
**---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.**
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveAsync(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.NetworkStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at FluentFTP.FtpSocketStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at FluentFTP.FtpSocketStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token)
   at FluentFTP.FtpDataStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at FluentFTP.FtpDataStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token)
   at FluentFTP.AsyncFtpClient.UploadFileInternalAsync(Stream fileData, String localPath, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress, CancellationToken token, FtpProgress metaProgress)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at FluentFTP.AsyncFtpClient.OpenWrite(String path, FtpDataType type, Int64 fileLen, CancellationToken token)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at FluentFTP.AsyncFtpClient.OpenDataStreamAsync(String command, Int64 restart, CancellationToken token)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at FluentFTP.AsyncFtpClient.OpenPassiveDataStreamAsync(FtpDataConnectionType type, String command, Int64 restart, CancellationToken token)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at FluentFTP.AsyncFtpClient.Execute(String command, CancellationToken token)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at FluentFTP.AsyncFtpClient.GetReplyAsyncInternal(CancellationToken token, String command)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at FluentFTP.AsyncFtpClient.GetReplyAsyncInternal(CancellationToken token, String command, Boolean exhaustNoop, Int32 timeOut)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at FluentFTP.FtpSocketStream.ReadLineAsync(Encoding encoding, CancellationToken token)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at FluentFTP.FtpSocketStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync, Boolean requiresExecutionContextFlow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs _)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
--- End of stack trace from previous location ---

 

   --- End of inner exception stack trace ---
   at FluentFTP.FtpSocketStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token)
   at FluentFTP.FtpDataStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token)
   at FluentFTP.AsyncFtpClient.UploadFileInternalAsync(Stream fileData, String localPath, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress, CancellationToken token, FtpProgress metaProgress)
   --- End of inner exception stack trace ---
   at FluentFTP.AsyncFtpClient.ResumeUploadAsync(String remotePath, Stream upStream, Int64 remotePosition, IOException ex, CancellationToken token)
   at FluentFTP.AsyncFtpClient.UploadFileInternalAsync(Stream fileData, String localPath, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress, CancellationToken token, FtpProgress metaProgress)
---> (Inner Exception #1) FluentFTP.Exceptions.FtpException: **Malformed PASV response: 0**
   at FluentFTP.Client.BaseClient.BaseFtpClient.GetPassivePort(FtpDataConnectionType type, FtpReply reply, String& host, Int32& port)
   at FluentFTP.AsyncFtpClient.OpenPassiveDataStreamAsync(FtpDataConnectionType type, String command, Int64 restart, CancellationToken token)
   at FluentFTP.AsyncFtpClient.OpenDataStreamAsync(String command, Int64 restart, CancellationToken token)
   at FluentFTP.AsyncFtpClient.OpenAppend(String path, FtpDataType type, Int64 fileLen, CancellationToken token)
   at FluentFTP.AsyncFtpClient.ResumeUploadAsync(String remotePath, Stream upStream, Int64 remotePosition, IOException ex, CancellationToken token)<---

**Comment by Venkatakrishna-bvk** [comment]
we are using ftpserver with this WS_FTP PRO (IP SWITCH)
<img width="313" alt="image" src="https://github.com/robinrodricks/FluentFTP/assets/30506328/7346c949-ecf0-4daf-90a1-1e53aa22e02d">

**Comment by FanDjango** [comment]
Great! Thanks.

Look at the log - right very near the beginning:

```
...
...
Command:  STOR WebsiteTestFiles/dev/Invoices-staging/bvk/copy3/20230704_28_VK CSV file.8/Invoice4196958.pdf
Status:   Waiting for response to: STOR WebsiteTestFiles/dev/Invoices-staging/bvk/copy3/20230704_28_VK CSV file.8/Invoice4196958.pdf
Response: 150 Uploading in BINARY file WebsiteTestFiles/dev/Invoices-staging/bvk/copy3/20230704_28_VK CSV file.8/Invoice4196958.pdf [69ms]
Status:   Uploaded 82872 bytes
Status:   Closing/Disposing FtpSocketStream(data connection)
Status:   Waiting for response to: STOR WebsiteTestFiles/dev/Invoices-staging/bvk/copy3/20230704_28_VK CSV file.8/Invoice4196958.pdf
Response: 226 Transfer completed [252ms]
Status:   Closing/Disposing FtpSocketStream(data connection)

# OpenRead("/non-prod-ftp/WebsiteTestFiles/dev/Invoices-staging/bvk/copy1/20230704_28_VK CSV file.8/Invoice4197082.pdf", Binary, 0, 0)

# GetFileSize("/non-prod-ftp/WebsiteTestFiles/dev/Invoices-staging/bvk/copy1/20230704_28_VK CSV file.8/Invoice4197082.pdf", -1)
Status:   Socket has stale data - prior to command execution
Status:   The stale data was:
Stale:    226 Transfer completed
Warning:  Reconnect needed due to stale data present on control connection
Status:   Command stashed: SIZE /non-prod-ftp/WebsiteTestFiles/dev/Invoices-staging/bvk/copy1/20230704_28_VK CSV file.8/Invoice4197082.pdf
Status:   Closing/Disposing FtpSocketStream(control connection)

# Connect(True)
Warning:  Reconnect (Count: 193)
Status:   FluentFTP 47.0.0.0(.NET 6.0)
Status:   Connecting to IP #1= ***:21
Status:   Waiting for a response
Response: 220 ftp.server.biz X2 
...
...
```

Ok, the log is not from the beginning. I can see the following things that worry me:
`Status:   Socket has stale data - prior to command execution`

This happens often, so many reconnects (many, this one is number 193) later on in the log.

I think I see a possible problem here but need to research it.

There is a `226 Transfer completed` from the previous `RETR` command that is not being waited for correctly.

I will check this for a while. I wonder what is causing this. Perhaps I will have special "tests" for you to perform in order to find out about this - I hope you will be able to do that.

**Note:** Of course an API for copying a directory would be a nice enhancement. But your implementation should also work and not fail with this error.

**Comment by FanDjango** [comment]
See also #1242 Same problem, same solution

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango ,
Thank you for your prompt response.
As suggested, I will remove the obsolete OpenRead and try using the download code provided below.

```
 await using (var sourceStream = await asyncFtpClient1.OpenRead(file.FullName).ConfigureAwait(false))
			 {
				await asyncFtpClient2.UploadStream(sourceStream, destinationFilePath, existsMode: FtpRemoteExists.Overwrite, createRemoteDir: true).ConfigureAwait(false);
			 };
```

**Comment by FanDjango** [comment]
You must **also** replace the OpenRead with DownloadStream, it is also obsolete.
