### ISSUE TITLE
ACTIVE mode FTP is raising Exception of Timeout but working in FileZilla and WinSCP

### ISSUE THREAD

**Issue by PKYADAV** [robinrodricks/FluentFTP#1495]
**FTP Server OS:** Ubuntu

**Client Computer OS:** Ubuntu

**FluentFTP Version:** 49.0.2

**Framework:** .NET 6

Hi Team,

Trying to upload FTP but getting timeout exception:

FTP Logs:

**Logs :**
```
2024-02-24 13:58:48.633 +05:30 [ERR] Error while uploading the file to the server. See InnerException for more info.
FluentFTP.Exceptions.FtpException: Error while uploading the file to the server. See InnerException for more info.
---> System.TimeoutException: Timed out trying to connect!
at FluentFTP.FtpSocketStream.ConnectAsync(String host, Int32 port, FtpIpVersion ipVersions, CancellationToken token)
at FluentFTP.AsyncFtpClient.OpenPassiveDataStreamAsync(FtpDataConnectionType type, String command, Int64 restart, CancellationToken token)
at FluentFTP.AsyncFtpClient.OpenDataStreamAsync(String command, Int64 restart, CancellationToken token)
at FluentFTP.AsyncFtpClient.GetNameListing(String path, CancellationToken token)
at FluentFTP.AsyncFtpClient.FileExists(String path, CancellationToken token)
at FluentFTP.AsyncFtpClient.UploadFileInternalAsync(Stream fileData, Strin2024-02-24 13:59:26.438 +05:30 [ERR] Error while uploading the file to the server. See InnerException for more info.
FluentFTP.Exceptions.FtpException: Error while uploading the file to the server. See InnerException for more info.
---> System.TimeoutException: Timed out trying to read data from the socket stream!
at FluentFTP.FtpSocketStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token)
at FluentFTP.FtpSocketStream.ReadLineAsync(Encoding encoding, CancellationToken token)
at FluentFTP.Client.BaseClient.BaseFtpClient.FluentFTP.IInternalFtpClient.GetReplyInternal(CancellationToken token, String command, Boolean exhaustNoop, Int32 timeOut, Boolean useSema)
at FluentFTP.AsyncFtpClient.Execute(String command, CancellationToken token)
at FluentFTP.AsyncFtpClient.OpenActiveDataStreamAsync(FtpDataConnectionType type, String command, Int64 restart, CancellationToken token)
at FluentFTP.AsyncFtpClient.OpenActiveDataStreamAsync(FtpDataConnectionType type, String command, Int64 restart, CancellationToken token)
at FluentFTP.AsyncFtpClient.OpenDataStreamAsync(String command, Int64 restart, CancellationToken token)
at FluentFTP.AsyncFtpClient.OpenWriteInternal(String path, FtpDataType type, Int64 fileLen, Boolean ignoreStaleData, CancellationToken token)
at FluentFTP.AsyncFtpClient.UploadFileInternalAsync(Stream fileData, String localPath, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress, CancellationToken token, FtpProgress metaProgress)
--- End of inner exception stack trace ---
```

```
2024-02-24 14:04:28.668 +05:30 [INF] > Connect(False)
2024-02-24 14:04:28.676 +05:30 [DBG] FluentFTP 49.0.1.0(.NET 6.0)
2024-02-24 14:04:28.676 +05:30 [INF] Connecting to IP https://github.com/ThreeMammals/Ocelot/issues/1= ***:21
2024-02-24 14:04:28.679 +05:30 [DBG] Waiting for a response
2024-02-24 14:04:28.684 +05:30 [INF] Response: 220 Welcome to FTP service. [738939.357d]
2024-02-24 14:04:28.684 +05:30 [INF] Command: USER ***
2024-02-24 14:04:28.684 +05:30 [DBG] Waiting for response to: USER ***
2024-02-24 14:04:28.687 +05:30 [INF] Response: 331 Please specify the password. [2ms]
2024-02-24 14:04:28.687 +05:30 [INF] Command: PASS ***
2024-02-24 14:04:28.687 +05:30 [DBG] Waiting for response to: PASS ***
2024-02-24 14:04:28.733 +05:30 [INF] Response: 230 Login successful. [46ms]
2024-02-24 14:04:28.733 +05:30 [INF] Command: FEAT
2024-02-24 14:04:28.733 +05:30 [DBG] Waiting for response to: FEAT
2024-02-24 14:04:28.737 +05:30 [DBG] Response: 211-Features:
Response: EPRT
Response: EPSV
Response: MDTM
Response: PASV
Response: REST STREAM
Response: SIZE
Response: TVFS
2024-02-24 14:04:28.737 +05:30 [INF] Response: 211 End [3ms]
2024-02-24 14:04:28.737 +05:30 [INF] Text encoding: System.Text.ASCIIEncoding+ASCIIEncodingSealed
2024-02-24 14:04:28.737 +05:30 [INF] Command: SYST
2024-02-24 14:04:28.737 +05:30 [DBG] Waiting for response to: SYST
2024-02-24 14:04:28.740 +05:30 [INF] Response: 215 UNIX Type: L8 [3ms]
2024-02-24 14:04:28.740 +05:30 [DBG] Active ServerHandler is: None
2024-02-24 14:04:28.740 +05:30 [DBG] Listing parser set to: Unix
2024-02-24 14:04:28.740 +05:30 [INF] Command: PWD
2024-02-24 14:04:28.740 +05:30 [DBG] Waiting for response to: PWD
2024-02-24 14:04:28.744 +05:30 [INF] Response: 257 "/" is the current directory [3ms]
2024-02-24 14:04:28.744 +05:30 [INF] > UploadFile("/srv/nidoworkz/nidoimages/167f32cc-4208-4c47-b25a-66829dc5bf50/Vol_500378308208_20240224140001.png", "Vol_500378308208_20240024020002.png", Overwrite, True, Retry)
2024-02-24 14:04:28.744 +05:30 [INF] > FileExists("Vol_500378308208_20240024020002.png")
2024-02-24 14:04:28.744 +05:30 [INF] Command: SIZE /Vol_500378308208_20240024020002.png
2024-02-24 14:04:28.744 +05:30 [DBG] Waiting for response to: SIZE /Vol_500378308208_20240024020002.png
2024-02-24 14:04:28.747 +05:30 [INF] Response: 550 Could not get file size. [3ms]
2024-02-24 14:04:28.747 +05:30 [INF] > DirectoryExists(".")
2024-02-24 14:04:28.748 +05:30 [INF] > OpenWrite("Vol_500378308208_20240024020002.png", Binary, -1, False)
2024-02-24 14:04:28.748 +05:30 [INF] Command: TYPE I
2024-02-24 14:04:28.748 +05:30 [DBG] Waiting for response to: TYPE I
2024-02-24 14:04:28.751 +05:30 [INF] Response: 200 Switching to Binary mode. [3ms]
2024-02-24 14:04:28.751 +05:30 [INF] > OpenDataStreamAsync("STOR Vol_500378308208_20240024020002.png", 0)
2024-02-24 14:04:28.751 +05:30 [INF] > OpenActiveDataStreamAsync(AutoActive, "STOR Vol_500378308208_20240024020002.png", 0)
2024-02-24 14:04:28.751 +05:30 [INF] Command: EPRT |1|192.168.0.201|41479|
2024-02-24 14:04:28.751 +05:30 [DBG] Waiting for response to: EPRT |1|192.168.0.201|41479|
2024-02-24 14:04:28.755 +05:30 [INF] Response: 500 Illegal EPRT command. [3ms]
2024-02-24 14:04:28.755 +05:30 [DBG] Closing/Disposing FtpSocketStream(data connection)
2024-02-24 14:04:28.755 +05:30 [INF] > OpenActiveDataStreamAsync(PORT, "STOR Vol_500378308208_20240024020002.png", 0)
2024-02-24 14:04:28.755 +05:30 [INF] Command: PORT 192,168,0,201,180,193
2024-02-24 14:04:28.755 +05:30 [DBG] Waiting for response to: PORT 192,168,0,201,180,193

```

**Comment by FanDjango** [comment]
You are using ACTIVE mode? I see no source code from you, so....
Ok, but it seems EPRT is choosing an unroutable address (192.168.xxx.xxx) instead of your external one. This provokes a 500 Illegal EPRT command error.
Configure the client to use autopassive or passive instead, perhaps.

**Comment by PKYADAV** [comment]
Hi @FanDjango, Sorry for the delay in response. Please find below source code for your ready reference:

`
var serilogLogger = new LoggerConfiguration()
        .MinimumLevel.Debug()
        .WriteTo.File(_ftpLogPath, rollingInterval: RollingInterval.Day, rollOnFileSizeLimit: true, fileSizeLimitBytes: 5242880, retainedFileCountLimit: 5)
        .CreateLogger();

var microsoftLogger = new SerilogLoggerFactory(serilogLogger)
        .CreateLogger("FTP");

client.Logger = new FtpLogAdapter(microsoftLogger);

_logger.LogDebug($"Connecting to FTP Server:{item?.Server} Port:{item?.Port}");
client.Config.DataConnectionType = FtpDataConnectionType.AutoActive;

var ftpConnect = client.Connect(cancellationToken);

await Task.WhenAny(ftpConnect, Task.Delay(_timeout, cancellationToken));

if (!ftpConnect.IsCompleted)
{
    _logger.LogInformation($"Timeout Occured for FTP Server:{item?.Server} Port:{item?.Port}");
    return;
}

if (item?.IsSSL == true)
{
    _logger.LogInformation($"Enabling Setting for SSL for FTP Server:{item?.Server} Port:{item?.Port}");
    client.Config.EncryptionMode = FtpEncryptionMode.Explicit;
    client.Config.ValidateAnyCertificate = true;
}


_logger.LogDebug($"Uploading to FTP Server:{item?.Server} Port:{item?.Port}, LocalPath:{item?.LocalPath}, ServerPath:{serverPath}");
try
{
    var response = await client.UploadFile(item?.LocalPath, serverPath, token: cancellationToken);
    if (response.IsSuccess())
    {
        Success = true;
        _logger.LogDebug($"FTP Request Result:{response} for FTP Server:{item?.Server} Port:{item?.Port} for ID:{item?.Id}");
    }
    else
    {
        retryCounter++;
        _logger.LogDebug($"FTP Request Result:{response} for FTP Server:{item?.Server} Port:{item?.Port} for ID:{item?.Id}");
    }
}
catch (Exception tx)
{
    retryCounter++;
    _logger.LogError(tx, message: tx.Message);
}
finally
{
    client?.Dispose();
}
`

**Comment by FanDjango** [comment]
Super, thanks. 

`client.Config.DataConnectionType = FtpDataConnectionType.AutoActive;`

Can't use that with a non routable source address.

Do you actually read the log?

```
2024-02-27 16:46:11.955 +05:30 [INF] Command:  EPRT |1|192.168.0.201|38175|
2024-02-27 16:46:11.955 +05:30 [DBG] Waiting for response to: EPRT |1|192.168.0.201|38175|
2024-02-27 16:46:11.957 +05:30 [INF] Response: 200 EPRT command successful. Consider using EPSV. [1ms]
```

So use ``client.Config.DataConnectionType = FtpDataConnectionType.AutoPassive;` as I noted previously, and report back after trying that.

**Comment by PKYADAV** [comment]
Hi @FanDjango, below is log for both fail under 425 and success for same file:

Failed Upload Log:
`
2024-03-04 00:00:41.684 +05:30 [DBG] FluentFTP 49.0.2.0(.NET 6.0)
2024-03-04 00:00:41.684 +05:30 [INF] Connecting to IP #1= ***:21
2024-03-04 00:00:41.688 +05:30 [DBG] Waiting for a response
2024-03-04 00:00:41.692 +05:30 [INF] Response: 220 Welcome to FTP service. [738947.771d]
2024-03-04 00:00:41.692 +05:30 [INF] Command:  USER ***
2024-03-04 00:00:41.692 +05:30 [DBG] Waiting for response to: USER ***
2024-03-04 00:00:41.695 +05:30 [INF] Response: 331 Please specify the password. [2ms]
2024-03-04 00:00:41.695 +05:30 [INF] Command:  PASS ***
2024-03-04 00:00:41.695 +05:30 [DBG] Waiting for response to: PASS ***
2024-03-04 00:00:41.744 +05:30 [INF] Response: 230 Login successful. [48ms]
2024-03-04 00:00:41.744 +05:30 [INF] Command:  FEAT
2024-03-04 00:00:41.744 +05:30 [DBG] Waiting for response to: FEAT
2024-03-04 00:00:41.747 +05:30 [DBG] Response: 211-Features:
Response: EPRT
Response: EPSV
Response: MDTM
Response: PASV
Response: REST STREAM
Response: SIZE
Response: TVFS
2024-03-04 00:00:41.747 +05:30 [INF] Response: 211 End [2ms]
2024-03-04 00:00:41.747 +05:30 [INF] Text encoding: System.Text.ASCIIEncoding+ASCIIEncodingSealed
2024-03-04 00:00:41.747 +05:30 [INF] Command:  SYST
2024-03-04 00:00:41.747 +05:30 [DBG] Waiting for response to: SYST
2024-03-04 00:00:41.751 +05:30 [INF] Response: 215 UNIX Type: L8 [3ms]
2024-03-04 00:00:41.751 +05:30 [DBG] Active ServerHandler is: None
2024-03-04 00:00:41.751 +05:30 [DBG] Listing parser set to: Unix
2024-03-04 00:00:41.751 +05:30 [INF] Command:  PWD
2024-03-04 00:00:41.751 +05:30 [DBG] Waiting for response to: PWD
2024-03-04 00:00:41.754 +05:30 [INF] Response: 257 "/" is the current directory [3ms]
2024-03-04 00:00:41.754 +05:30 [INF] >         UploadFile("/srv/nidoworkz/nidoimages/167f32cc-4208-4c47-b25a-66829dc5bf50/Vol_500368987862_20240303103135.png", "Vol_500368987862_20243103103135.png", Overwrite, False, None)
2024-03-04 00:00:41.755 +05:30 [INF] >         FileExists("Vol_500368987862_20243103103135.png")
2024-03-04 00:00:41.755 +05:30 [INF] Command:  SIZE /Vol_500368987862_20243103103135.png
2024-03-04 00:00:41.755 +05:30 [DBG] Waiting for response to: SIZE /Vol_500368987862_20243103103135.png
2024-03-04 00:00:41.758 +05:30 [INF] Response: 550 Could not get file size. [3ms]
2024-03-04 00:00:41.758 +05:30 [INF] >         OpenWrite("Vol_500368987862_20243103103135.png", Binary, -1, False)
2024-03-04 00:00:41.758 +05:30 [INF] Command:  TYPE I
2024-03-04 00:00:41.758 +05:30 [DBG] Waiting for response to: TYPE I
2024-03-04 00:00:41.762 +05:30 [INF] Response: 200 Switching to Binary mode. [3ms]
2024-03-04 00:00:41.762 +05:30 [INF] >         OpenDataStreamAsync("STOR Vol_500368987862_20243103103135.png", 0)
2024-03-04 00:00:41.762 +05:30 [INF] >         OpenActiveDataStreamAsync(AutoActive, "STOR Vol_500368987862_20243103103135.png", 0)
2024-03-04 00:00:41.762 +05:30 [INF] Command:  EPRT |1|192.168.3.201|40039|
2024-03-04 00:00:41.762 +05:30 [DBG] Waiting for response to: EPRT |1|192.168.3.201|40039|
2024-03-04 00:00:41.765 +05:30 [INF] Response: 500 Illegal EPRT command. [3ms]
2024-03-04 00:00:41.765 +05:30 [DBG] Closing/Disposing FtpSocketStream(data connection)
2024-03-04 00:00:41.765 +05:30 [INF] >         OpenActiveDataStreamAsync(PORT, "STOR Vol_500368987862_20243103103135.png", 0)
2024-03-04 00:00:41.765 +05:30 [INF] Command:  PORT 192,168,3,201,142,49
2024-03-04 00:00:41.765 +05:30 [DBG] Waiting for response to: PORT 192,168,3,201,142,49
2024-03-04 00:00:41.769 +05:30 [INF] Response: 200 PORT command successful. Consider using PASV. [3ms]
2024-03-04 00:00:41.769 +05:30 [INF] Command:  STOR Vol_500368987862_20243103103135.png
2024-03-04 00:00:41.769 +05:30 [DBG] Waiting for response to: STOR Vol_500368987862_20243103103135.png
2024-03-04 00:01:41.833 +05:30 [INF] Response: 425 Failed to establish connection. [1.001m]
2024-03-04 00:01:41.834 +05:30 [DBG] Closing/Disposing FtpSocketStream(data connection)
2024-03-04 00:01:41.834 +05:30 [INF] >         CloseDataStream()
2024-03-04 00:01:44.193 +05:30 [INF] >         Dispose()
2024-03-04 00:01:44.193 +05:30 [DBG] Disposing FtpClient object...
2024-03-04 00:01:44.193 +05:30 [DBG] Closing/Disposing FtpSocketStream(control connection)

`
Success Upload Log

`
2024-03-04 00:01:41.859 +05:30 [INF] Response: 220 Welcome to FTP service. [738947.772d]
2024-03-04 00:01:41.859 +05:30 [INF] Command:  USER ***
2024-03-04 00:01:41.859 +05:30 [DBG] Waiting for response to: USER ***
2024-03-04 00:01:41.862 +05:30 [INF] Response: 331 Please specify the password. [3ms]
2024-03-04 00:01:41.862 +05:30 [INF] Command:  PASS ***
2024-03-04 00:01:41.862 +05:30 [DBG] Waiting for response to: PASS ***
2024-03-04 00:01:41.910 +05:30 [INF] Response: 230 Login successful. [48ms]
2024-03-04 00:01:41.910 +05:30 [INF] Command:  FEAT
2024-03-04 00:01:41.910 +05:30 [DBG] Waiting for response to: FEAT
2024-03-04 00:01:41.914 +05:30 [DBG] Response: 211-Features:
Response: EPRT
Response: EPSV
Response: MDTM
Response: PASV
Response: REST STREAM
Response: SIZE
Response: TVFS
2024-03-04 00:01:41.914 +05:30 [INF] Response: 211 End [3ms]
2024-03-04 00:01:41.914 +05:30 [INF] Text encoding: System.Text.ASCIIEncoding+ASCIIEncodingSealed
2024-03-04 00:01:41.914 +05:30 [INF] Command:  SYST
2024-03-04 00:01:41.914 +05:30 [DBG] Waiting for response to: SYST
2024-03-04 00:01:41.918 +05:30 [INF] Response: 215 UNIX Type: L8 [3ms]
2024-03-04 00:01:41.918 +05:30 [DBG] Active ServerHandler is: None
2024-03-04 00:01:41.918 +05:30 [DBG] Listing parser set to: Unix
2024-03-04 00:01:41.918 +05:30 [INF] Command:  PWD
2024-03-04 00:01:41.918 +05:30 [DBG] Waiting for response to: PWD
2024-03-04 00:01:41.921 +05:30 [INF] Response: 257 "/" is the current directory [3ms]
2024-03-04 00:01:41.922 +05:30 [INF] >         UploadFile("/srv/nidoworkz/nidoimages/167f32cc-4208-4c47-b25a-66829dc5bf50/Vol_500368987862_20240303103135.png", "Vol_500368987862_20243103103135.png", Overwrite, False, None)
2024-03-04 00:01:41.922 +05:30 [INF] >         FileExists("Vol_500368987862_20243103103135.png")
2024-03-04 00:01:41.922 +05:30 [INF] Command:  SIZE /Vol_500368987862_20243103103135.png
2024-03-04 00:01:41.922 +05:30 [DBG] Waiting for response to: SIZE /Vol_500368987862_20243103103135.png
2024-03-04 00:01:41.925 +05:30 [INF] Response: 213 0 [3ms]
2024-03-04 00:01:41.925 +05:30 [INF] >         DeleteFile("Vol_500368987862_20243103103135.png")
2024-03-04 00:01:41.925 +05:30 [INF] Command:  DELE Vol_500368987862_20243103103135.png
2024-03-04 00:01:41.925 +05:30 [DBG] Waiting for response to: DELE Vol_500368987862_20243103103135.png
2024-03-04 00:01:41.929 +05:30 [INF] Response: 250 Delete operation successful. [3ms]
2024-03-04 00:01:41.929 +05:30 [INF] >         OpenWrite("Vol_500368987862_20243103103135.png", Binary, -1, False)
2024-03-04 00:01:41.929 +05:30 [INF] Command:  TYPE I
2024-03-04 00:01:41.929 +05:30 [DBG] Waiting for response to: TYPE I
2024-03-04 00:01:41.932 +05:30 [INF] Response: 200 Switching to Binary mode. [3ms]
2024-03-04 00:01:41.932 +05:30 [INF] >         OpenDataStreamAsync("STOR Vol_500368987862_20243103103135.png", 0)
2024-03-04 00:01:41.932 +05:30 [INF] >         OpenActiveDataStreamAsync(AutoActive, "STOR Vol_500368987862_20243103103135.png", 0)
2024-03-04 00:01:41.932 +05:30 [INF] Command:  EPRT |1|192.168.3.201|39523|
2024-03-04 00:01:41.932 +05:30 [DBG] Waiting for response to: EPRT |1|192.168.3.201|39523|
2024-03-04 00:01:41.936 +05:30 [INF] Response: 500 Illegal EPRT command. [3ms]
2024-03-04 00:01:41.936 +05:30 [DBG] Closing/Disposing FtpSocketStream(data connection)
2024-03-04 00:01:41.936 +05:30 [INF] >         OpenActiveDataStreamAsync(PORT, "STOR Vol_500368987862_20243103103135.png", 0)
2024-03-04 00:01:41.936 +05:30 [INF] Command:  PORT 192,168,3,201,181,241
2024-03-04 00:01:41.936 +05:30 [DBG] Waiting for response to: PORT 192,168,3,201,181,241
2024-03-04 00:01:41.940 +05:30 [INF] Response: 200 PORT command successful. Consider using PASV. [3ms]
2024-03-04 00:01:41.940 +05:30 [INF] Command:  STOR Vol_500368987862_20243103103135.png
2024-03-04 00:01:41.940 +05:30 [DBG] Waiting for response to: STOR Vol_500368987862_20243103103135.png
2024-03-04 00:01:41.947 +05:30 [INF] Response: 150 Ok to send data. [7ms]
2024-03-04 00:01:42.080 +05:30 [DBG] Uploaded 553237 bytes
2024-03-04 00:01:42.080 +05:30 [DBG] Closing/Disposing FtpSocketStream(data connection)
2024-03-04 00:01:42.080 +05:30 [DBG] Waiting for response to: STOR Vol_500368987862_20243103103135.png
2024-03-04 00:01:42.185 +05:30 [INF] Response: 226 Transfer complete. [245ms]
2024-03-04 00:01:42.185 +05:30 [INF] >         Dispose()
2024-03-04 00:01:42.185 +05:30 [DBG] Disposing FtpClient object...
2024-03-04 00:01:42.186 +05:30 [DBG] Closing/Disposing FtpSocketStream(control connection)
`

**Comment by FanDjango** [comment]
Nice!

One thing that I notice: In these two logs, all of a sudden, EPRT is illegal and we **must** use PORT? In your first log, original one up at the top, EPRT was successful. Also, your local subnet changed from 192.168.0.x to 192.168.3.x..

That confuses things a little bit, so I will just look at these two **new** logs, the success and the failure.

The possible error reason that I can think of here, is that **not all ports** that FluentFTP is given by the operating system, when he open a listener, are usable for connections. You very probably need to restrict these to a port range. 

As an experiment, use **exactly** the port number of the successful transfer (181,241) by specifying it (in the correct syntax) in the `client.Config.ActivePorts...`, and also specify "PORT" instead of "AutoActive", so that EPRT is **not used**. See if that one will succeed again, and again, without failing.

Also investigate, as I mentioned earlier, if you have specified a port range to be used for active mode in FileZilla or in WinSCP. You need to use the **same** port range for FluentFTP and use "PORT" instead of "AutoActive".
