### ISSUE TITLE
Download with Progress throws exception

### ISSUE THREAD

**Issue by crobibero** [robinrodricks/FluentFTP#1525]
Moved from https://github.com/robinrodricks/FluentFTP.GnuTLS/issues/131

**FTP Server OS:** Unix

**FTP Server Type:** Pure-FTPd 

**Client Computer OS:** Windows

**FluentFTP Version:** https://github.com/robinrodricks/FluentFTP/commit/fb2ee75f08929685bf5cfd9447d5343c3ffc7fc6 (master)

**Framework:** .NET  8 

With the following code an exception is thrown. It is not thrown with progress disabled.
```c#
var downloadProgress = new Progress<FtpProgress>(p =>
{
    var progress = (int)p.Progress;
    if (progress % 10 == 0)
    {
        _logger.LogInformation(
            "Progress: {Progress:F1}% ETA: {Eta}",
            p.Progress,
            p.ETA);
    }
});

var client = new AsyncFtpClient(host, username, password);
client.Config.CustomStream = typeof(GnuTlsStream);
await client.AutoConnect(cancellationToken).ConfigureAwait(false);
var downloadStatus = await client.DownloadFile(
        fileDestinationPath,
        normalizedFilePath,
        verifyOptions: FtpVerify.OnlyChecksum | FtpVerify.Retry | FtpVerify.Delete,
        progress: downloadProgress,
        token: cancellationToken)
    .ConfigureAwait(false);
```

**Logs :**
```exception
FluentFTP.Exceptions.FtpException: Error while downloading the file from the server. See InnerException for more info.
 ---> System.ArgumentException: GnuTlsInternalStream.Read: maxCount must be greater than zero
   at FluentFTP.GnuTLS.GnuTlsInternalStream.Read(Byte[] buffer, Int32 offset, Int32 maxCount)
   at System.IO.Stream.<>c.<BeginReadInternal>b__38_0(Object <p0>)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at FluentFTP.FtpSocketStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token)
   at FluentFTP.FtpDataStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token)
   at FluentFTP.AsyncFtpClient.DownloadFileInternalAsync(String localPath, String remotePath, Stream outStream, Int64 restartPosition, IProgress`1 progress, CancellationToken token, FtpProgress metaProgress, Int64 knownFileSize, Boolean isAppend, Int64 stopPosition)
   --- End of inner exception stack trace ---
   at FluentFTP.AsyncFtpClient.DownloadFileInternalAsync(String localPath, String remotePath, Stream outStream, Int64 restartPosition, IProgress`1 progress, CancellationToken token, FtpProgress metaProgress, Int64 knownFileSize, Boolean isAppend, Int64 stopPosition)
   at FluentFTP.AsyncFtpClient.DownloadFileToFileAsync(String localPath, String remotePath, FtpLocalExists existsMode, FtpVerify verifyOptions, IProgress`1 progress, CancellationToken token, FtpProgress metaProgress)
   at FluentFTP.AsyncFtpClient.DownloadFile(String localPath, String remotePath, FtpLocalExists existsMode, FtpVerify verifyOptions, IProgress`1 progress, CancellationToken token)

```

**Comment by FanDjango** [comment]
Thanks for opening this here. What exactly is the code base you are using, as the current master has tried to address this topic?

Also I would appreciate the complete log. If you read the other issues, you will notice that the connect FEAT command response and other things that precede the actual download play an important role in how the problem develops.

**Comment by FanDjango** [comment]
Code base: Current master, sorry I used ambiguous terms.

Thanks for the log, I will study them...

First glance tells me it is still related to the progress problems I linked you to - I will need some time to check this, please stand by.

**Comment by crobibero** [comment]
I linked the commit that I used to make sure I had the latest one: https://github.com/robinrodricks/FluentFTP/commit/fb2ee75f08929685bf5cfd9447d5343c3ffc7fc6

**Comment by FanDjango** [comment]
This was automatically closed by GitHub because of the wording I used in the commit text... so I reopened.

Please test with the newest master - this should now be ok.

**Comment by crobibero** [comment]
I can confirm that I am no longer getting this exception with e84c034d27bf43091a999fc70a4b6786f5ba9b16 applied

**Comment by FanDjango** [comment]
Great! Thanks for your efforts.
