### ISSUE TITLE
FtpException thrown downloading file with 49.0.2 works in 49.0.1

### ISSUE THREAD

**Issue by AaronY-RWS** [robinrodricks/FluentFTP#1537]
**FTP Server OS:** Windows 10 Pro x64

**FTP Server Type:** Filezilla Server v0.9.60

**Client Computer OS:** Windows 11 Business x64

**FluentFTP Version:** 49.0.2

**Framework:** .NET 8

Getting an exception trying to download a file using the **DownloadFile** method.
Same code works with version 49.0.1 and earlier _(also included 49.0.1 log for comparison.)_
Found after upgrading FluentFTP from 46.0.2 to 49.0.2

**FTP Folder permissions:** Files.Read, Files.Write, Files.Delete, Files.Append

**Exception:**
```
FluentFTP.Exceptions.FtpException
  HResult=0x80131500
  Message=Error while downloading the file from the server. See InnerException for more info.
  Source=FluentFTP
  StackTrace:
   at FluentFTP.FtpClient.DownloadFileInternal(String localPath, String remotePath, Stream outStream, Int64 restartPosition, Action`1 progress, FtpProgress metaProgress, Int64 knownFileSize, Boolean isAppend, Int64 stopPosition)
   at FluentFTP.FtpClient.DownloadFileToFile(String localPath, String remotePath, FtpLocalExists existsMode, FtpVerify verifyOptions, Action`1 progress, FtpProgress metaProgress)
   at FluentFTP.FtpClient.DownloadFile(String localPath, String remotePath, FtpLocalExists existsMode, FtpVerify verifyOptions, Action`1 progress)
```
**Inner Exception 1:**
```
ArgumentOutOfRangeException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection. (Parameter 'count')

   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.IO.Stream.ValidateBufferArguments(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at FluentFTP.FtpSocketStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at FluentFTP.FtpDataStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at FluentFTP.FtpClient.DownloadFileInternal(String localPath, String remotePath, Stream outStream, Int64 restartPosition, Action`1 progress, FtpProgress metaProgress, Int64 knownFileSize, Boolean isAppend, Int64 stopPosition)
```

**Logs :**

**Logs for 49.0.2:**
```

2024-04-10 10:08:30.690 -05:00 [INF] >         Connect(False)
2024-04-10 10:08:30.714 -05:00 [DBG] FluentFTP 49.0.2.0(.NET 6.0)
2024-04-10 10:08:30.718 -05:00 [INF] Connecting to IP #1= ***:21
2024-04-10 10:08:30.767 -05:00 [DBG] Waiting for a response
2024-04-10 10:08:30.824 -05:00 [DBG] Response: 220-FileZilla Server 0.9.60 beta
Response: 220-written by Tim Kosse (tim.kosse@filezilla-project.org)
2024-04-10 10:08:30.824 -05:00 [INF] Response: 220 Please visit https://filezilla-project.org/ [738985.631d]
2024-04-10 10:08:30.827 -05:00 [INF] Status:   Detected FTP server: FileZilla
2024-04-10 10:08:30.831 -05:00 [INF] Command:  USER ***
2024-04-10 10:08:30.831 -05:00 [DBG] Waiting for response to: USER ***
2024-04-10 10:08:30.877 -05:00 [INF] Response: 331 Password required for *** [45ms]
2024-04-10 10:08:30.878 -05:00 [INF] Command:  PASS ***
2024-04-10 10:08:30.878 -05:00 [DBG] Waiting for response to: PASS ***
2024-04-10 10:08:30.922 -05:00 [INF] Response: 230 Logged on [44ms]
2024-04-10 10:08:30.924 -05:00 [INF] Command:  FEAT
2024-04-10 10:08:30.924 -05:00 [DBG] Waiting for response to: FEAT
2024-04-10 10:08:30.969 -05:00 [DBG] Response: 211-Features:
Response: MDTM
Response: REST STREAM
Response: SIZE
Response: MLST type*;size*;modify*;
Response: MLSD
Response: AUTH SSL
Response: AUTH TLS
Response: PROT
Response: PBSZ
Response: UTF8
Response: CLNT
Response: MFMT
Response: EPSV
Response: EPRT
2024-04-10 10:08:30.969 -05:00 [INF] Response: 211 End [45ms]
2024-04-10 10:08:30.976 -05:00 [INF] Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
2024-04-10 10:08:30.976 -05:00 [INF] Command:  OPTS UTF8 ON
2024-04-10 10:08:30.976 -05:00 [DBG] Waiting for response to: OPTS UTF8 ON
2024-04-10 10:08:31.021 -05:00 [INF] Response: 202 UTF8 mode is always enabled. No need to send this command. [44ms]
2024-04-10 10:08:31.021 -05:00 [INF] Command:  SYST
2024-04-10 10:08:31.021 -05:00 [DBG] Waiting for response to: SYST
2024-04-10 10:08:31.065 -05:00 [INF] Response: 215 UNIX emulated by FileZilla [44ms]
2024-04-10 10:08:31.070 -05:00 [DBG] Active ServerHandler is: FileZilla
2024-04-10 10:08:31.071 -05:00 [DBG] Listing parser set to: Machine
2024-04-10 10:08:31.072 -05:00 [INF] Command:  PWD
2024-04-10 10:08:31.072 -05:00 [DBG] Waiting for response to: PWD
2024-04-10 10:08:31.116 -05:00 [INF] Response: 257 "/" is current directory. [44ms]
2024-04-10 10:08:31.121 -05:00 [INF] >         GetFileSize("/uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz")
2024-04-10 10:08:31.122 -05:00 [INF] Command:  SIZE /uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz
2024-04-10 10:08:31.122 -05:00 [DBG] Waiting for response to: SIZE /uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz
2024-04-10 10:08:31.167 -05:00 [INF] Response: 550 Permission denied [45ms]
2024-04-10 10:08:31.178 -05:00 [INF] >         DownloadFile("\\files.fileserver.com\data\Folder\Subfolder\89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz", "/uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz", Resume, None)
2024-04-10 10:08:31.310 -05:00 [INF] >         GetFileSize("/uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz")
2024-04-10 10:08:31.310 -05:00 [INF] Command:  SIZE /uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz
2024-04-10 10:08:31.310 -05:00 [DBG] Waiting for response to: SIZE /uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz
2024-04-10 10:08:31.358 -05:00 [INF] Response: 550 Permission denied [48ms]
2024-04-10 10:08:31.454 -05:00 [INF] >         GetFileSize("/uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz")
2024-04-10 10:08:31.454 -05:00 [INF] Command:  SIZE /uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz
2024-04-10 10:08:31.454 -05:00 [DBG] Waiting for response to: SIZE /uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz
2024-04-10 10:08:31.499 -05:00 [INF] Response: 550 Permission denied [44ms]
2024-04-10 10:08:31.500 -05:00 [INF] >         OpenRead("/uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz", Binary, 0, -1, False)
2024-04-10 10:08:31.500 -05:00 [INF] Command:  TYPE I
2024-04-10 10:08:31.500 -05:00 [DBG] Waiting for response to: TYPE I
2024-04-10 10:08:31.544 -05:00 [INF] Response: 200 Type set to I [44ms]
2024-04-10 10:08:31.545 -05:00 [INF] >         OpenDataStream("RETR /uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz", 0)
2024-04-10 10:08:31.551 -05:00 [INF] >         OpenPassiveDataStream(AutoPassive, "RETR /uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz", 0)
2024-04-10 10:08:31.551 -05:00 [INF] Command:  EPSV
2024-04-10 10:08:31.551 -05:00 [DBG] Waiting for response to: EPSV
2024-04-10 10:08:31.595 -05:00 [INF] Response: 229 Entering Extended Passive Mode (|||42594|) [44ms]
2024-04-10 10:08:31.601 -05:00 [INF] Connecting to IP #1= ***:42594
2024-04-10 10:08:31.646 -05:00 [INF] Command:  RETR /uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz
2024-04-10 10:08:31.646 -05:00 [DBG] Waiting for response to: RETR /uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz
2024-04-10 10:08:31.691 -05:00 [INF] Response: 150 Opening data channel for file download from server of "/uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz" [44ms]
2024-04-10 10:08:31.741 -05:00 [DBG] Closing/Disposing FtpSocketStream(data connection)
2024-04-10 10:08:32.968 -05:00 [INF] >         Dispose()
2024-04-10 10:08:32.968 -05:00 [DBG] Disposing FtpClient object...
2024-04-10 10:08:32.968 -05:00 [INF] >         Disconnect()
2024-04-10 10:08:32.969 -05:00 [INF] Control connection has stale data - prior to command execution of "QUIT"
2024-04-10 10:08:32.969 -05:00 [DBG] The stale data was (length = 96): 
2024-04-10 10:08:32.970 -05:00 [DBG] Stale:    426 Connection closed; aborted transfer of "/uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz"
2024-04-10 10:08:32.970 -05:00 [WRN] Reconnect needed due to stale data present on control connection
2024-04-10 10:08:32.970 -05:00 [INF] Command stashed: QUIT
2024-04-10 10:08:32.970 -05:00 [DBG] Closing/Disposing FtpSocketStream(control connection)
2024-04-10 10:08:32.970 -05:00 [INF] Not sending QUIT because the connection has already been closed.


```

**Logs for 49.0.1 :**

```
2024-04-10 10:42:09.889 -05:00 [INF] >         Connect(False)
2024-04-10 10:42:09.916 -05:00 [DBG] FluentFTP 49.0.1.0(.NET 6.0)
2024-04-10 10:42:09.920 -05:00 [INF] Connecting to IP #1= ***:21
2024-04-10 10:42:09.976 -05:00 [DBG] Waiting for a response
2024-04-10 10:42:10.025 -05:00 [DBG] Response: 220-FileZilla Server 0.9.60 beta
Response: 220-written by Tim Kosse (tim.kosse@filezilla-project.org)
2024-04-10 10:42:10.026 -05:00 [INF] Response: 220 Please visit https://filezilla-project.org/ [738985.654d]
2024-04-10 10:42:10.028 -05:00 [INF] Status:   Detected FTP server: FileZilla
2024-04-10 10:42:10.034 -05:00 [INF] Command:  USER ***
2024-04-10 10:42:10.034 -05:00 [DBG] Waiting for response to: USER ***
2024-04-10 10:42:10.080 -05:00 [INF] Response: 331 Password required for *** [45ms]
2024-04-10 10:42:10.083 -05:00 [INF] Command:  PASS ***
2024-04-10 10:42:10.083 -05:00 [DBG] Waiting for response to: PASS ***
2024-04-10 10:42:10.128 -05:00 [INF] Response: 230 Logged on [44ms]
2024-04-10 10:42:10.133 -05:00 [INF] Command:  FEAT
2024-04-10 10:42:10.133 -05:00 [DBG] Waiting for response to: FEAT
2024-04-10 10:42:10.178 -05:00 [DBG] Response: 211-Features:
Response: MDTM
Response: REST STREAM
Response: SIZE
Response: MLST type*;size*;modify*;
Response: MLSD
Response: AUTH SSL
Response: AUTH TLS
Response: PROT
Response: PBSZ
Response: UTF8
Response: CLNT
Response: MFMT
Response: EPSV
Response: EPRT
2024-04-10 10:42:10.179 -05:00 [INF] Response: 211 End [45ms]
2024-04-10 10:42:10.192 -05:00 [INF] Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
2024-04-10 10:42:10.192 -05:00 [INF] Command:  OPTS UTF8 ON
2024-04-10 10:42:10.192 -05:00 [DBG] Waiting for response to: OPTS UTF8 ON
2024-04-10 10:42:10.240 -05:00 [INF] Response: 202 UTF8 mode is always enabled. No need to send this command. [47ms]
2024-04-10 10:42:10.240 -05:00 [INF] Command:  SYST
2024-04-10 10:42:10.240 -05:00 [DBG] Waiting for response to: SYST
2024-04-10 10:42:10.286 -05:00 [INF] Response: 215 UNIX emulated by FileZilla [45ms]
2024-04-10 10:42:10.291 -05:00 [DBG] Active ServerHandler is: FileZilla
2024-04-10 10:42:10.292 -05:00 [DBG] Listing parser set to: Machine
2024-04-10 10:42:10.293 -05:00 [INF] Command:  PWD
2024-04-10 10:42:10.293 -05:00 [DBG] Waiting for response to: PWD
2024-04-10 10:42:10.338 -05:00 [INF] Response: 257 "/" is current directory. [44ms]
2024-04-10 10:42:10.340 -05:00 [INF] >         GetFileSize("/uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz")
2024-04-10 10:42:10.341 -05:00 [INF] Command:  SIZE /uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz
2024-04-10 10:42:10.341 -05:00 [DBG] Waiting for response to: SIZE /uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz
2024-04-10 10:42:10.386 -05:00 [INF] Response: 550 Permission denied [45ms]
2024-04-10 10:42:10.394 -05:00 [INF] >         DownloadFile("\\files.filserver.com\data\Folder\Subfolder\89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz", "/uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz", Resume, None)
2024-04-10 10:42:10.395 -05:00 [INF] >         GetFileSize("/uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz")
2024-04-10 10:42:10.395 -05:00 [INF] Command:  SIZE /uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz
2024-04-10 10:42:10.395 -05:00 [DBG] Waiting for response to: SIZE /uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz
2024-04-10 10:42:10.440 -05:00 [INF] Response: 550 Permission denied [44ms]
2024-04-10 10:42:10.452 -05:00 [INF] >         GetFileSize("/uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz")
2024-04-10 10:42:10.452 -05:00 [INF] Command:  SIZE /uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz
2024-04-10 10:42:10.452 -05:00 [DBG] Waiting for response to: SIZE /uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz
2024-04-10 10:42:10.498 -05:00 [INF] Response: 550 Permission denied [46ms]
2024-04-10 10:42:10.500 -05:00 [INF] >         OpenRead("/uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz", Binary, 0, -1, False)
2024-04-10 10:42:10.500 -05:00 [INF] Command:  TYPE I
2024-04-10 10:42:10.500 -05:00 [DBG] Waiting for response to: TYPE I
2024-04-10 10:42:10.546 -05:00 [INF] Response: 200 Type set to I [45ms]
2024-04-10 10:42:10.548 -05:00 [INF] >         OpenDataStream("RETR /uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz", 0)
2024-04-10 10:42:10.557 -05:00 [INF] >         OpenPassiveDataStream(AutoPassive, "RETR /uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz", 0)
2024-04-10 10:42:10.557 -05:00 [INF] Command:  EPSV
2024-04-10 10:42:10.557 -05:00 [DBG] Waiting for response to: EPSV
2024-04-10 10:42:10.603 -05:00 [INF] Response: 229 Entering Extended Passive Mode (|||42753|) [46ms]
2024-04-10 10:42:10.611 -05:00 [INF] Connecting to IP #1= ***:42753
2024-04-10 10:42:10.658 -05:00 [INF] Command:  RETR /uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz
2024-04-10 10:42:10.658 -05:00 [DBG] Waiting for response to: RETR /uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz
2024-04-10 10:42:10.703 -05:00 [INF] Response: 150 Opening data channel for file download from server of "/uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz" [44ms]
2024-04-10 10:42:18.677 -05:00 [DBG] Downloaded 10016216 bytes
2024-04-10 10:42:18.682 -05:00 [DBG] Closing/Disposing FtpSocketStream(data connection)
2024-04-10 10:42:18.839 -05:00 [DBG] Waiting for response to: RETR /uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz
2024-04-10 10:42:18.840 -05:00 [INF] Response: 226 Successfully transferred "/uploads/89d10d6d-65a1-45ec-b66e-5ae0adbbee15.cpz" [8.181s]
2024-04-10 10:42:18.840 -05:00 [INF] >         Disconnect()
2024-04-10 10:42:18.840 -05:00 [INF] Command:  QUIT
2024-04-10 10:42:18.841 -05:00 [DBG] Waiting for response to: QUIT
2024-04-10 10:42:18.885 -05:00 [INF] Response: 221 Goodbye [44ms]
2024-04-10 10:42:18.885 -05:00 [DBG] Closing/Disposing FtpSocketStream(control connection)
2024-04-10 10:42:18.886 -05:00 [INF] >         Dispose()
2024-04-10 10:42:18.886 -05:00 [DBG] Disposing FtpClient object...
2024-04-10 10:42:18.886 -05:00 [DBG] Closing/Disposing FtpSocketStream(control connection)

```

**Comment by FanDjango** [comment]
Thanks for this report and it's completeness.

FluentFTP 49.0.1 -> 49.0.2: there were some changes to the handling of "Progress reporting" - these, after release of 49.0.2 were fixed and are due for release soon. So, if your code is using "Progress", you might want to test (just as a temporary measure) to **not** use a progress callback in your code.

If it does not resolve the problem: We need to analyze your problem in more depth.

If it does resolve the problem: I would be very interested in you accessing the current master on GitHub and testing that.

Once again, if that resolves the problem, then this information would be valuable to confirm all is well.

Otherwise, we are back to square one, and need to do more analysis.

Note: Handling of stale data and what to do / how to report failed transfers is also improved in current master, which will help debugging.

What I do not understand, but you may be able to shed light on: You report the exception, but in the log I cannot see exactly at what point of the sequence the exception occurred. I surmise it occurred right after

> 2024-04-10 10:08:31.741 -05:00 [DBG] Closing/Disposing FtpSocketStream(data connection)

Am I correct?

**Comment by FanDjango** [comment]
If you look at the recent issues:

#1518 and #1519 more or less covers this - in your log, I can see that the SIZE command is not allowed and thus the problem is quite clear. 

So I really think that the current master fixes your problem, it is just not released yet.

Workaround: Don't use progress **or** allow the SIZE command on the server.

**Comment by FanDjango** [comment]
V50.0.0 has been released. Any work on your issue should be re-analyzed against this new release instead of V49.0.2 (see previous post).

**Comment by AaronY-RWS** [comment]
V50.0.0 resolves the issue I reported (as did not using progress in v49.0.2.)

Thanks!
