### ISSUE TITLE
Allways getting Timed Out error while using Azure Funtions to connect an FTPs

### ISSUE THREAD

**Issue by CRomeroGarcia** [robinrodricks/FluentFTP#1581]
**FTP Server OS:** Unknown
**FTP Server Type:**  Unknown
**Client Computer OS:** Windows on Azure App Service Plan
**FluentFTP Version:** 49.0.2
**Framework:** .NET 6 

Hi! I'm currently trying to establish a connection to a client's FTP server. To do this, I make the request from an Azure Functions resource. Unfortunately all the calls I try to make always come up with the same problem: **Timed out trying to connect!**

I have tried using a normal FTPClient, an AsycFTPClient, increasing the connection timeout in the client configuration, using the AutoConnect() or the AutoDetect() and nothing. Allways the same message: TimeOut! Allways 21 secs...

I'm attaching the code in case someone can tell me if I'm making a mistake. Thank you!
```
    public class EchoCyC
    {
        [FunctionName("EchoCyC")]
        public static async Task<IActionResult> Run([HttpTrigger(AuthorizationLevel.Function, "get", Route = null)] HttpRequest req,
        ILogger log)
        {
            log.LogInformation("Azure Function trigger EchoCyC");

            string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
            dynamic data = JsonConvert.DeserializeObject(requestBody);

            // Retrieve FTP server parameters from request query
            string ftphost = req.Query["ftphost"];
            string ftpusername = req.Query["ftpusername"];
            string ftppassword = req.Query["ftppassword"];

            if (string.IsNullOrEmpty(ftphost) || string.IsNullOrEmpty(ftpusername) || string.IsNullOrEmpty(ftppassword))
            {
                log.LogWarning("Invalid FTP server details provided.");
                return new BadRequestObjectResult("Please provide valid FTP server details in the request body (Server host ('ftphost') - 
                Username ('ftpusername') - Password('ftppassword'))");
            }

            try
            {
                log.LogInformation("Attempting to connect to the FTP server...");

                // Connect to the FTP server
                var ftptoken = new CancellationTokenSource(TimeSpan.FromMinutes(2)).Token;
                using (var ftpClient = new CustomFtpClient(ftphost, ftpusername, ftppassword, ftptoken))
                {   
                    await ftpClient.Initialize;
                    if (!ftpClient.Initiated)
                    {
                        log.LogError("Failed to initialize FTP client.");
                        return (ActionResult)new ObjectResult($"Error occurred while connecting to FTP server: {ftpClient}")
                        {
                            StatusCode = StatusCodes.Status500InternalServerError
                        };
                    }
                    else
                    {
                        return (ActionResult)new OkObjectResult("Connection established with the FTP server");
                    }
                }
            }
            catch (Exception ex)
            {
                log.LogError(ex, "Error occurred while connecting to FTP server.");
                return (ActionResult)new ObjectResult($"An error has occurred while connecting to FTP server: {ex.Message}")
                {
                    StatusCode = StatusCodes.Status500InternalServerError
                };
            }
        }
    }
`}`
```
```
    public class CustomFtpClient : AsyncFtpClient
    {
        public bool Initiated { get; private set; }

        public Task Initialize { get; }

        public CustomFtpClient(string host, string username, string password, CancellationToken token) : base()
        {
            Initialize = CreateInstanceAsync(host, username, password, token);
        }

        //private AsyncFtpClient Client { get; }

        private async Task CreateInstanceAsync(string host, string username, string password, CancellationToken token)
        {
            this.LoadProfile(new FtpProfile
            {
                Host = host,
                Credentials = new NetworkCredential(username, password),
                Encryption = FtpEncryptionMode.Auto,
                Protocols = SslProtocols.Tls11 | SslProtocols.Tls12,
                DataConnection = FtpDataConnectionType.PASV,
                Encoding = System.Text.Encoding.UTF8,
            });

            //this.Port = 222;
            this.Config.ConnectTimeout = 300000;
            this.Config.DataConnectionConnectTimeout = 300000;
            this.Config.DataConnectionReadTimeout = 300000;
            this.Config.ValidateAnyCertificate = true;

            await this.Connect(token);
            Initiated = true;
        }
    }
```

**Logs :**

```
Connecting to log stream...
2024-05-24T10:51:02  Welcome, you are now connected to log-streaming service. The default timeout is 2 hours. Change the timeout with the App Setting SCM_LOGSTREAM_TIMEOUT (in seconds). 
2024-05-24T10:51:06.624 [Information] Executing 'EchoCyC' (Reason='This function was programmatically called via the host APIs.', Id=dbffee7a-1efe-4b1f-917e-6eebff639812)
2024-05-24T10:51:06.625 [Information] Azure Function trigger EchoCyC
2024-05-24T10:51:06.625 [Information] Attempting to connect to the FTP server...
2024-05-24T10:51:06.624 [Information] Executing 'EchoCyC' (Reason='This function was programmatically called via the host APIs.', Id=dbffee7a-1efe-4b1f-917e-6eebff639812)
2024-05-24T10:51:06.625 [Information] Azure Function trigger EchoCyC
2024-05-24T10:51:06.625 [Information] Attempting to connect to the FTP server...
2024-05-24T10:51:27.679 [Error] Error occurred while connecting to FTP server.
System.TimeoutException : Timed out trying to connect!
   at async FluentFTP.FtpSocketStream.ConnectAsync(String host,Int32 port,FtpIpVersion ipVersions,CancellationToken token)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async FluentFTP.AsyncFtpClient.ConnectAsync(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async FluentFTP.AsyncFtpClient.Connect(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async FluentFTP.AsyncFtpClient.Connect(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async BetSolar.AppFDeloiteCCaucion.CustomFtpClient.CreateInstanceAsync(String host,String username,String password,CancellationToken token) at C:\PROYECTOS\DEV\BETSOLAR\BetSolar\AppFDeloiteCCaucion\src\CustomFtpClient.cs : 42
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async BetSolar.AppFDeloiteCCaucion.EchoCyC.Run(HttpRequest req,ILogger log) at C:\PROYECTOS\DEV\BETSOLAR\BetSolar\AppFDeloiteCCaucion\src\EchoCyC.cs : 44
2024-05-24T10:51:27.680 [Information] Executed 'EchoCyC' (Succeeded, Id=dbffee7a-1efe-4b1f-917e-6eebff639812, Duration=21061ms)
2024-05-24T10:51:27.679 [Error] Error occurred while connecting to FTP server.
System.TimeoutException : Timed out trying to connect!
   at async FluentFTP.FtpSocketStream.ConnectAsync(String host,Int32 port,FtpIpVersion ipVersions,CancellationToken token)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async FluentFTP.AsyncFtpClient.ConnectAsync(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async FluentFTP.AsyncFtpClient.Connect(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async FluentFTP.AsyncFtpClient.Connect(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async BetSolar.AppFDeloiteCCaucion.CustomFtpClient.CreateInstanceAsync(String host,String username,String password,CancellationToken token) at C:\PROYECTOS\DEV\BETSOLAR\BetSolar\AppFDeloiteCCaucion\src\CustomFtpClient.cs : 42
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async BetSolar.AppFDeloiteCCaucion.EchoCyC.Run(HttpRequest req,ILogger log) at C:\PROYECTOS\DEV\BETSOLAR\BetSolar\AppFDeloiteCCaucion\src\EchoCyC.cs : 44
```

**Comment by FanDjango** [comment]
It would be nice of you could produce a verbose log from FluentFTP, either using the logging interface it provides or even just the legacy logger.

Besides that, the timeout exception really more or less means that, well something timed out for the connect process.

You could do a sort of "negative" test by trying with a different IP, or by trying an IP one **cannot** connect to and checking that you different errors to sort of get a feel for what is going wrong. Beyond that, I have no idea what could be the problem - it is **your** environment, after all.

Barring any quick ideas, the last resort would be to wireshark trace the connect process between the client and the server.

**Comment by CRomeroGarcia** [comment]
Thanks for your reply @FanDjango! 

It turns out that the problem was that the client had a range of IPs enabled. If the connection to any of these IPs was not made, the server returned TimeOut. 

Thank you for your time. Best regards
