### ISSUE TITLE
FtpVerify.Retry | FtpRetry.Delete giving error even if CRC implementation is there on the server

### ISSUE THREAD

**Issue by myogendra** [robinrodricks/FluentFTP#162]
Hi,
Actually I am facing an issue while using below code 
```
 client.UploadDataType = FtpDataType.Binary;
client.RetryAttempts = 5;
bool fileUploaded =client.UploadFile(fileInfo.FullName, remoteRelativePath,FtpExists.Append, true, FtpVerify.Retry | FtpVerify.Delete);
```
It's giving errors which I have captured in trace logs
```
08/09/2017 17:41:39Error in Uploading file /UploadFolder/Upload1/1402.data There is no built in support for computing CRC hashes.
   at FluentFTP.FtpHash.Verify(Stream istream)
   at FluentFTP.FtpHash.Verify(String file)
   at FluentFTP.FtpClient.VerifyTransfer(String localPath, String remotePath)
   at FluentFTP.FtpClient.UploadFileFromFile(String localPath, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown, FtpVerify verifyOptions)
   at FluentFTP.FtpClient.UploadFile(String localPath, String remotePath, FtpExists existsMode, Boolean createRemoteDir, FtpVerify verifyOptions)
   at FTPClient.Uploader.<>c__DisplayClass7_1.<UploadFiles>b__1() in E:\FTPClient\FTPClient\FTPClient\Uploader.cs:line 110
09-08-2017 17:41:39  Transfer of file /UploadFolder/Upload1/Newfolder/1404.data started 
```
**Its able to compute hash as I have below code which is working, but I expect the retry logic should also work**
```
 var checkSum = client.GetChecksum(remoteRelativePath);
 if (fileUploaded && checkSum.IsValid)
{
    Trace.WriteLine(DateTime.Now + "  Transfer of file " +
                                                                    remoteRelativePath + " done" + Environment.NewLine);
}
```

I am attaching log files.
[log_file.txt](https://github.com/hgupta9/FluentFTP/files/1211374/log_file.txt)

Also, there is a problem in computing hash if file Ftp file path has spaces (I have a folder name with space), It was giving me syntax error in executing XCRC command

**Comment by helpme1c** [comment]
First. Dear developers, thank you for so great job!
I have this issue in my backup program with FTP server (https://www.serv-u.com/).
Can you tell near date of solution for this bug?

**Comment by robinrodricks** [comment]
Hash implementation has been fixed in recent versions.

If anyone has this issue again respond on this thread and I will reopen this.
