### ISSUE TITLE
The server mode SSL must use a certificate with the associated private key.

### ISSUE THREAD

**Issue by SwimUp** [robinrodricks/FluentFTP#1645]
**FTP Server OS:** Unix 

**Client Computer OS:** Ubuntu

**FluentFTP Version:** Latest

**Framework:** .NET 8 

Hello. I'm trying to connect server with TLS withy ubuntu docker container, but i'm getting "The server mode SSL must use a certificate with the associated private key."
I load p12 certificate like: 
`new X509Certificate2(Settings.Settings["require"]["certPath"], Settings.Settings["require"]["password"], X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.Exportable | X509KeyStorageFlags.PersistKeySet);`

If i log "HasPrivateKey" it's says "true:
Cert: True
Key: System.Security.Cryptography.DSAOpenSsl | System.Security.Cryptography.DSAOpenSsl

               FtpConfig ftpConfig = new FtpConfig()
               {
                   EncryptionMode = FtpEncryptionMode.Explicit,
                   DataConnectionType = FtpDataConnectionType.PASV,
                   ReadTimeout = (int)TimeSpan.FromMinutes(30).TotalMilliseconds,
                   ConnectTimeout = (int)TimeSpan.FromMinutes(30).TotalMilliseconds,
                   SslProtocols = System.Security.Authentication.SslProtocols.Tls12 | System.Security.Authentication.SslProtocols.Tls11 | System.Security.Authentication.SslProtocols.Tls | System.Security.Authentication.SslProtocols.Tls13,
                   LogToConsole = true
               };

               var certificate = new X509Certificate2(Settings.Settings["require"]["certPath"], Settings.Settings["require"]["password"], X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.Exportable | X509KeyStorageFlags.PersistKeySet);

               Console.WriteLine($"Cert: {certificate.HasPrivateKey}");
               Console.WriteLine($"Key: {certificate.PrivateKey} | {certificate.PrivateKey?.GetType()}");

               ftpConfig.ClientCertificates.Add(certificate);

               FtpClient ftpClient = new FtpClient(Settings.Settings["require"]["host"], Settings.Settings["require"]["username"], Settings.Settings["require"]["username"], int.Parse(Settings.Settings["require"]["port"]), ftpConfig);
               ftpClient.ValidateCertificate += FtpClient_ValidateCertificate;

               ftpClient.Connect();

**Logs :**

```

# Connect(False)
Status:   FluentFTP 51.1.0.0(.NET 6.0) FtpClient
Status:   Connecting(sync) FtpClient.FtpSocketStream(control) IP #1 = ***:8221
Status:   Waiting for a response
Response: 220 (IBM WebSphere DataPower) [739145.742d]
Command:  AUTH TLS
Status:   Waiting for response to: AUTH TLS
Response: 234 AUTH TLS OK starting TLS negotiation [1ms]
17.09.2024 20:48:52 GetRequireConsole $e5a31f84-ca71-4347-b84e-df2454594297$188$ System.NotSupportedException: The server mode SSL must use a certificate with the associated private key.   at System.Net.Security.SslStreamCertificateContext..ctor(X509Certificate2 target, ReadOnlyCollection`1 intermediates, SslCertificateTrust trust)   at System.Net.Security.SslStreamCertificateContext.Create(X509Certificate2 target, X509Certificate2Collection additionalCertificates, Boolean offline, SslCertificateTrust trust, Boolean noOcspFetch)   at System.Net.Security.SslStream.AcquireClientCredentials(Byte[]& thumbPrint, Boolean newCredentialsRequested)   at System.Net.Security.SslStream.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)   at System.Net.Security.SslStream.NextMessage(ReadOnlySpan`1 incomingBuffer, ProtocolToken& token)   at System.Net.Security.SslStream.ProcessTlsFrame(Int32 frameSize, ProtocolToken& message)   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)   at FluentFTP.FtpSocketStream.ActivateEncryption(String targetHost, X509CertificateCollection clientCerts, SslProtocols sslProtocols)   at FluentFTP.FtpClient.Connect(Boolean reConnect)   at FluentFTP.FtpClient.Connect()   at GetRequireConsole.Program.TryGetFiles() in /src/GetRequireConsole/Program.cs:line 167
2024-09-17 20:48:52,680 [1] ERROR GetRequireConsole.Program [TryGetFiles] — [5a919f8d-7430-44b9-bfbd-eb36f3b8da19]|Result:fail|Error: The server mode SSL must use a certificate with the associated private key.
   at System.Net.Security.SslStreamCertificateContext..ctor(X509Certificate2 target, ReadOnlyCollection`1 intermediates, SslCertificateTrust trust)
   at System.Net.Security.SslStreamCertificateContext.Create(X509Certificate2 target, X509Certificate2Collection additionalCertificates, Boolean offline, SslCertificateTrust trust, Boolean noOcspFetch)
   at System.Net.Security.SslStream.AcquireClientCredentials(Byte[]& thumbPrint, Boolean newCredentialsRequested)
   at System.Net.Security.SslStream.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
   at System.Net.Security.SslStream.NextMessage(ReadOnlySpan`1 incomingBuffer, ProtocolToken& token)
   at System.Net.Security.SslStream.ProcessTlsFrame(Int32 frameSize, ProtocolToken& message)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at FluentFTP.FtpSocketStream.ActivateEncryption(String targetHost, X509CertificateCollection clientCerts, SslProtocols sslProtocols)
   at FluentFTP.FtpClient.Connect(Boolean reConnect)
   at FluentFTP.FtpClient.Connect()


```

**Comment by FanDjango** [comment]
I googled "The server mode SSL must use a certificate with the associated private key" and got a number of hits - can you check those? 

This struck me as being interesting:

```
Are you failing on Windows only? If so, it's that SslStream doesn't support "ephemeral" private keys. You'd need to export the CreateFromPemFile result as Pkcs12/Pfx and import it again to participate in some of the "PFX magic" that SslStream depends on
```
[from here](https://stackoverflow.com/questions/31732365/the-server-mode-ssl-must-use-a-certificate-with-the-associated-private-key-dur)

**Comment by SwimUp** [comment]
> I googled "The server mode SSL must use a certificate with the associated private key" and got a number of hits - can you check those?
> 
> This struck me as being interesting:
> 
> ```
> Are you failing on Windows only? 
> If so, it's that SslStream doesn't support "ephemeral" private keys. 
> You'd need to export the CreateFromPemFile result as Pkcs12/Pfx and 
> import it again to participate in some of the "PFX magic" that 
> SslStream depends on
> ```
> 
> [from here](https://stackoverflow.com/questions/31732365/the-server-mode-ssl-must-use-a-certificate-with-the-associated-private-key-dur)

Thanks for Answer!
On Windows code above works fine. This error only on Linux, Ubuntu (docker container)

I exported pfx to pem: `openssl pkcs12 -in ftpmkr.p12 -out cert.pem -nodes`
then 
```
var originalCertificate = X509Certificate2.CreateFromPemFile("cert.pem");
var certificate = new X509Certificate2(originalCertificate.Export(X509ContentType.Pfx, Settings.Settings["require"]["password"]), Settings.Settings["require"]["password"]);

ftpConfig.ClientCertificates.Add(certificate);
```
but i got same error

```
# Connect(False)
Status:   FluentFTP 51.1.0.0(.NET 6.0) FtpClient
Status:   Connecting(sync) FtpClient.FtpSocketStream(control) IP #1 = ***:8221
Status:   Waiting for a response
Response: 220 (IBM WebSphere DataPower) [739146.301d]
Command:  AUTH TLS
Status:   Waiting for response to: AUTH TLS
Response: 234 AUTH TLS OK starting TLS negotiation [1ms]
18.09.2024 10:13:04 GetRequireConsole $e5a31f84-ca71-4347-b84e-df2454594297$188$ System.NotSupportedException: The server mode SSL must use a certificate with the associated private key.   at System.Net.Security.SslStreamCertificateContext..ctor(X509Certificate2 target, ReadOnlyCollection`1 intermediates, SslCertificateTrust trust)   at System.Net.Security.SslStreamCertificateContext.Create(X509Certificate2 target, X509Certificate2Collection additionalCertificates, Boolean offline, SslCertificateTrust trust, Boolean noOcspFetch)   at System.Net.Security.SslStream.AcquireClientCredentials(Byte[]& thumbPrint, Boolean newCredentialsRequested)   at System.Net.Security.SslStream.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)   at System.Net.Security.SslStream.NextMessage(ReadOnlySpan`1 incomingBuffer, ProtocolToken& token)   at System.Net.Security.SslStream.ProcessTlsFrame(Int32 frameSize, ProtocolToken& message)   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)   at FluentFTP.FtpSocketStream.ActivateEncryption(String targetHost, X509CertificateCollection clientCerts, SslProtocols sslProtocols)   at FluentFTP.FtpClient.Connect(Boolean reConnect)   at FluentFTP.FtpClient.Connect()   at GetRequireConsole.Program.TryGetFiles() in /src/GetRequireConsole/Program.cs:line 167
2024-09-18 10:13:04,399 [1] ERROR GetRequireConsole.Program [TryGetFiles] — [0c8936de-d96d-4025-878f-94138a191187]|Result:fail|Error: The server mode SSL must use a certificate with the associated private key.
   at System.Net.Security.SslStreamCertificateContext..ctor(X509Certificate2 target, ReadOnlyCollection`1 intermediates, SslCertificateTrust trust)
   at System.Net.Security.SslStreamCertificateContext.Create(X509Certificate2 target, X509Certificate2Collection additionalCertificates, Boolean offline, SslCertificateTrust trust, Boolean noOcspFetch)
   at System.Net.Security.SslStream.AcquireClientCredentials(Byte[]& thumbPrint, Boolean newCredentialsRequested)
   at System.Net.Security.SslStream.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
   at System.Net.Security.SslStream.NextMessage(ReadOnlySpan`1 incomingBuffer, ProtocolToken& token)
   at System.Net.Security.SslStream.ProcessTlsFrame(Int32 frameSize, ProtocolToken& message)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at FluentFTP.FtpSocketStream.ActivateEncryption(String targetHost, X509CertificateCollection clientCerts, SslProtocols sslProtocols)
   at FluentFTP.FtpClient.Connect(Boolean reConnect)
   at FluentFTP.FtpClient.Connect()

```
More logs:
```
Console.WriteLine($"certificate HasPrivateKey: {certificate.HasPrivateKey}");
Console.WriteLine($"certificate PrivateKey: {certificate.PrivateKey}");
Console.WriteLine($"certificate GetRSAPrivateKey: {certificate.GetRSAPrivateKey()}");
Console.WriteLine($"certificate GetDSAPrivateKey: {certificate.GetDSAPrivateKey()}");
Console.WriteLine($"certificate GetECDsaPrivateKey: {certificate.GetECDsaPrivateKey()}");
```
```
certificate HasPrivateKey: True
certificate PrivateKey: System.Security.Cryptography.DSACng
certificate GetRSAPrivateKey:
certificate GetDSAPrivateKey: System.Security.Cryptography.DSACng
certificate GetECDsaPrivateKey:

i also tried install openssl on linux. Error still appear, but logs different:
```
certificate HasPrivateKey: True
certificate PrivateKey: System.Security.Cryptography.DSAOpenSsl
certificate GetRSAPrivateKey:
certificate GetDSAPrivateKey: System.Security.Cryptography.DSAOpenSsl
certificate GetECDsaPrivateKey:
```
```
B

**Comment by SwimUp** [comment]
After some investigation i found how SslStreamCertificateContext searching Private keys in linux

![изображение](https://github.com/user-attachments/assets/7452d669-85a6-4693-808f-8ce296955ce6)

they check GetRSAPrivateKey, when GetECDsaPrivateKey, if both null --> exception "The server mode SSL must use a certificate with the associated private key."

in my case GetRSAPrivateKey/GetECDsaPrivateKey i null. My keys is GetDSAPrivateKey

**Comment by SwimUp** [comment]
I troed use GnuTLS, but got 
```
*GnuTlsHandShake(...) failed: (-12) GNUTLS_                                                      E_FATAL_ALERT_RECEIVED   at FluentFTP.GnuTLS.Core.GnuUtils.Check(String methodName,                                                       Int32 result, Int32[] resultsAllowed)   at FluentFTP.GnuTLS.Core.GnuTls.GnuTlsHandSh                                                      ake(Session session, Int32 ctimeout)   at FluentFTP.GnuTLS.GnuTlsInternalStream..cto                                                      r(String targetHostString, Socket socketDescriptor, CustomRemoteCertificateValidatio                                                      nCallback customRemoteCertificateValidation, X509CertificateCollection clientCertifi                                                      cates, String alpnString, GnuTlsInternalStream streamToResumeFrom, String prioritySt                                                      ring, String loadLibraryDllNamePrefix, Int32 handshakeTimeout, Int32 commTimeout, In                                                      t32 pollTimeout, GnuStreamLogCBFunc elog, Int32 logMaxLevel, GnuMessage logDebugInfo                                                      rmationMessages, Int32 logQueueMaxSize)   at FluentFTP.GnuTLS.GnuTlsStream.Init(Base                                                      FtpClient client, String targetHost, Socket socket, CustomRemoteCertificateValidatio                                                      nCallback customRemoteCertificateValidation, Boolean isControl, IFtpStream controlCo                                                      nnStream, IFtpStreamConfig untypedConfig)   at FluentFTP.FtpSocketStream.CreateCusto                                                      mStream(String targetHost)   at FluentFTP.FtpSocketStream.ActivateEncryption(String                                                       targetHost, X509CertificateCollection clientCerts, SslProtocols sslProtocols)   at F                                                      luentFTP.FtpClient.Connect(Boolean reConnect)   at FluentFTP.FtpClient.Connect()   a                                                      t GetRequireConsole.Program.TryGetFiles() in /src/GetRequireConsole/Program.cs:line                                                       213
2024-09-18 15:55:44,994 [1] ERROR GetRequireConsole.Program [TryGetFiles] — [4e91f32                                                      6-2424-4394-9e37-4ba92581638d]|Result:fail|Error: Error   : *GnuTlsHandShake(...) fa                                                      iled: (-12) GNUTLS_E_FATAL_ALERT_RECEIVED
   at FluentFTP.GnuTLS.Core.GnuUtils.Check(String methodName, Int32 result, Int32[]                                                       resultsAllowed)
   at FluentFTP.GnuTLS.Core.GnuTls.GnuTlsHandShake(Session session, Int32 ctimeout)
   at FluentFTP.GnuTLS.GnuTlsInternalStream..ctor(String targetHostString, Socket so                                                      cketDescriptor, CustomRemoteCertificateValidationCallback customRemoteCertificateVal                                                      idation, X509CertificateCollection clientCertificates, String alpnString, GnuTlsInte                                                      rnalStream streamToResumeFrom, String priorityString, String loadLibraryDllNamePrefi                                                      x, Int32 handshakeTimeout, Int32 commTimeout, Int32 pollTimeout, GnuStreamLogCBFunc                                                       elog, Int32 logMaxLevel, GnuMessage logDebugInformationMessages, Int32 logQueueMaxSi                                                      ze)
   at FluentFTP.GnuTLS.GnuTlsStream.Init(BaseFtpClient client, String targetHost, So                                                      cket socket, CustomRemoteCertificateValidationCallback customRemoteCertificateValida                                                      tion, Boolean isControl, IFtpStream controlConnStream, IFtpStreamConfig untypedConfi                                                      g)
   at FluentFTP.FtpSocketStream.CreateCustomStream(String targetHost)
   at FluentFTP.FtpSocketStream.ActivateEncryption(String targetHost, X509Certificat                                                      eCollection clientCerts, SslProtocols sslProtocols)
   at FluentFTP.FtpClient.Connect(Boolean reConnect)
   at FluentFTP.FtpClient.Connect()

```

**Comment by FanDjango** [comment]
I am afraid to say that the code for attaching SSL certificates to a connection request is not tested and functional in FluentFTP.GnuTLS until we find someone to collaborate on this. So attempting this with FluentFTP.GnuTLS is not possible. You need to stick with SslSteam instead.

We just put the certificate that you provide into the SslAuth request - this is the standard SslStream Authenticate request. Thus, FluentFTP is not really involved in any manipulation of the certificate - you need to "get it right" and then it will work.

Perhaps one way to expedite finding the right certificate build is to use a manual client (like FileZilla) first and provide the certificate to that, this might make for a faster testing turnaround time for your experiments.

**Comment by SwimUp** [comment]
> I am afraid to say that the code for attaching SSL certificates to a connection request is not tested and functional in FluentFTP.GnuTLS until we find someone to collaborate on this. So attempting this with FluentFTP.GnuTLS is not possible. You need to stick with SslStream instead.
> 
> We just put the certificate that you provide into the SslAuth request - this is the standard SslStream Authenticate request. Thus, FluentFTP is not really involved in any manipulation of the certificate - you need to "get it right" and then it will work.
> 
> Perhaps one way to expedite finding the right certificate build is to use a manual client (like FileZilla) first and provide the certificate to that, this might make for a faster testing turnaround time for your experiments.

Thanks for answer!
I will reissue the RSA certificate
