### ISSUE TITLE
Upload will attempt to set the stream position and throw an exception

### ISSUE THREAD

**Issue by kenkendk** [robinrodricks/FluentFTP#1694]
**FTP Server OS:** unknown

**FTP Server Type:** Likely ProFTPD 

**Client Computer OS:** unknown

**FluentFTP Version:** 50.1.0

**Framework:** .NET 8

The FTP client can try to modify the position of the stream which throws an exception

**Logs :**

Here is the stack trace. It appears that the `UploadStream` call will attempt to call `set_Position` which will cause an exception.
```

2024-12-21 15:12:41 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-b134c57ef47764456b582f694d3218cb1.dblock.zip.aes (49,22 MB)
2024-12-21 15:13:21 +01 - [Retry-Duplicati.Library.Main.Operation.Backup.BackendUploader-RetryPut]: Operation Put with file duplicati-b134c57ef47764456b582f694d3218cb1.dblock.zip.aes attempt 1 of 6 failed with message: Error while uploading the file to the server. See InnerException for more info.
FluentFTP.Exceptions.FtpException: Error while uploading the file to the server. See InnerException for more info.
 ---> System.AggregateException: Additional error occured while trying to resume uploading the file '/duplicati-b134c57ef47764456b582f694d3218cb1.dblock.zip.aes' at position 4849664 (Unable to write data to the transport connection: Eine vorhandene Verbindung wurde vom Remotehost geschlossen..) (You cannot modify the position of a FtpDataStream. This property is updated as data is read or written to the stream.)
 ---> System.IO.IOException: Unable to write data to the transport connection: Eine vorhandene Verbindung wurde vom Remotehost geschlossen..
 ---> System.Net.Sockets.SocketException (10054): Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Security.SslStream.<WriteSingleChunk>g__CompleteWriteAsync|157_1[TIOAdapter](ValueTask writeTask, Byte[] bufferToReturn)
   at System.Net.Security.SslStream.WriteAsyncChunked[TIOAdapter](ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at FluentFTP.FtpSocketStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token)
   at FluentFTP.FtpDataStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token)
   at FluentFTP.AsyncFtpClient.UploadFileInternalAsync(Stream fileData, String localPath, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress, CancellationToken token, FtpProgress metaProgress)
   --- End of inner exception stack trace ---
   at FluentFTP.AsyncFtpClient.ResumeUploadAsync(String remotePath, Stream upStream, Int64 remotePosition, IOException ex, CancellationToken token)
   at FluentFTP.AsyncFtpClient.UploadFileInternalAsync(Stream fileData, String localPath, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress, CancellationToken token, FtpProgress metaProgress)
 ---> (Inner Exception #1) System.InvalidOperationException: You cannot modify the position of a FtpDataStream. This property is updated as data is read or written to the stream.
   at FluentFTP.FtpDataStream.set_Position(Int64 value)
   at FluentFTP.AsyncFtpClient.ResumeUploadAsync(String remotePath, Stream upStream, Int64 remotePosition, IOException ex, CancellationToken token)<---

   --- End of inner exception stack trace ---
   at FluentFTP.AsyncFtpClient.UploadFileInternalAsync(Stream fileData, String localPath, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress, CancellationToken token, FtpProgress metaProgress)
   at FluentFTP.AsyncFtpClient.UploadStream(Stream fileStream, String remotePath, FtpRemoteExists existsMode, Boolean createRemoteDir, IProgress`1 progress, CancellationToken token)
   at Duplicati.Library.Backend.FTP.PutAsync(String remotename, Stream input, CancellationToken cancelToken)
   at Duplicati.Library.Main.Operation.Backup.BackendUploader.DoPut(FileEntryItem item, IBackend backend, CancellationToken cancelToken)
   at Duplicati.Library.Main.Operation.Backup.BackendUploader.<>c__DisplayClass20_0.<<UploadFileAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---

```

**Comment by FanDjango** [comment]
This one would need more info than solely the stack trace. Modifying the position is actually not allowed, thus the exception. It looks like (just from the stack trace) that we are in a retry situation, perhaps (????) and the position for the retry can not be requested or suchlike. In this case, perhaps a verbose log can tell us more?

**Comment by kenkendk** [comment]
I will try to get more information, but I am not getting the error, just relaying from a user.
It appears the underlying issue is that the server will close the control connection after being idle, despite an active transfer.
More details here:
https://forum.duplicati.com/t/ftp-upload-error-with-big-files/19749/3

Without looking at the FluentFTP source code, it looks like an error that the code will use an `FtpDataStream` and then attempt to set the position on that stream, as it will never work. 

From the stack trace, the retry happens entirely within FluentFTPs code, so I would imagine that this exception is thrown every time there is a retry after the source stream has been read? If the underlying stream is not seekable, I would argue that the retry should not be attempted at all, but an exception thrown from the original failure. If the source is seekable the exception should not be thrown.

**Comment by FanDjango** [comment]
>  If the underlying stream is not seekable, I would argue that the retry should not be attempted at all, but an exception thrown from the original failure. If the source is seekable the exception should not be thrown.

I agree.

IIRC there is currently no such check in the retry logic - I think it simply assumes a seekable (underlying) stream.

What kind of stream are you supplying to FluentFTP, that it is not seekable?

> It appears the underlying issue is that the server will close the control connection after being idle, despite an active transfer.

As an aside, maybe you would like to utilize the NOOP daemon to keep the control connection open on large (and thus long running) file transfers. Of course, that is not a FIX, but rather a possible workaround.

I myself now use the NOOP daemon as standard practice. FileZilla (as a client) does this too, no way to turn it off even.

This NOOP idea correlates with BIG FILES <==> PROBLEM OCCURS, especially after reading the issue you linked.

Adding the check for seekable YES/NO would be trivial, I'll put it on the TODO list.

**Comment by kenkendk** [comment]
> What kind of stream are you supplying to FluentFTP, that it is not seekable?

I *think* the stream is seekable; it is essentially a file, but wrapped in layers of timeout/throttle/progress/etc.
The exception looks like it is thrown by `FtpDataStream` which is a FluentFTP class, so I think there is more wrapping going on inside FluentFTP ?

> As an aside, maybe you would like to utilize the NOOP daemon to keep the control connection open on large (and thus long running) file transfers. Of course, that is not a FIX, but rather a possible workaround.

Yes, I forgot how crude the FTP protocol is. I will add the NOOP daemon to the code in an attempt to keep the connection alive.

**Comment by FanDjango** [comment]
Going back to the **actual** exception,

>  ---> System.AggregateException: Additional error occured while trying to resume uploading the file '/duplicati-b134c57ef47764456b582f694d3218cb1.dblock.zip.aes' at position 4849664 
(Unable to write data to the transport connection: Eine vorhandene Verbindung wurde vom Remotehost geschlossen..) 
(You cannot modify the position of a FtpDataStream. This property is updated as data is read or written to the stream.)

some more research shows up that `You cannot modify the position of a FtpDataStream` is internal to the `FtpDataStream` class and that this upload resume code needs to be looked at in some detail. **Can it ever have worked?**

**Comment by FanDjango** [comment]
I am specifically pointing at these statements:

```cs
					// create and return a new stream starting at the current remotePosition
					upStream = OpenAppendInternal(remotePath, Config.UploadDataType, 0, false);
					upStream.Position = remotePosition;
```
`upStream` is a `FtpDataStream` and you can't set a position on that. The exception and its message are coded in the `FtpDataStream.Position` getter/setter.

**Comment by FanDjango** [comment]
Oooops, I didn't mean to close this @kenkendk ! GitHub saw the text "Attempt to Fix #1684" and closed it for me. What a drag!

Reopened, sorry about that.

**Comment by kenkendk** [comment]
I would love to test it, but unfortunately, I do not have the problem on my own setups.
I think we will have to wait until the next FluentFTP release, and then see if the problem is solved.

**Comment by FanDjango** [comment]
Tested. It looks good now. So to keep things tidy I will close this now, it will be released eventually.
