### ISSUE TITLE
Failure writing network stream

### ISSUE THREAD

**Issue by iTeyo** [robinrodricks/FluentFTP#186]
Everything worked fine for me until I moved the programm to a friend of mine.

FluentFTP.FtpCommandException: Failure writing network stream.
     at FluentFTP.FtpClient.CloseDataStream(FtpDataStream stream)
     at FluentFTP.FtpDataStream.Close()
     at FluentFTP.FtpClient.GetListing(String path, FtpListOption options)
     at FTP_Programm.ftpcon.Connect()

We both connect to the same FTP Server outside of our home network

**Comment by hgupta9** [comment]
Please add complete logs (see FAQ) and specify OS and server software...

**Comment by robinrodricks** [comment]
Can you try with the latest build : https://www.nuget.org/packages/FluentFTP/19.0.0
