### ISSUE TITLE
Calling Upload fails when passed the Stream object returned from OpenRead call

### ISSUE THREAD

**Issue by bugged84** [robinrodricks/FluentFTP#207]
For example,

using (var sourceStream = client.OpenRead(sourcePath))
{
    client.Upload(sourceStream, destinationPath);
}

FluentFTP.FtpException : Error while uploading the file to the server. See InnerException for more info.
---- System.InvalidOperationException : You cannot modify the position of a FtpDataStream. This property is updated as data is read or written to the stream.
   at FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown)
   at FluentFTP.FtpClient.Upload(Stream fileStream, String remotePath, FtpExists existsMode, Boolean createRemoteDir)

**Comment by FanDjango** [comment]
This has been fixed long ago.
See #711, #859
