### ISSUE TITLE
client.FileExists and client.UploadFile throws FtpCommandException when files don't exist

### ISSUE THREAD

**Issue by haggerty-william** [robinrodricks/FluentFTP#238]
**FTP OS:** Windows

**FTP Server:** 

Serv-U FTP Server v15.1

**Ubuntu 16.04 LTS:** 
```
client.FileExists($"{pathToFile}") in
{

bool directoryExists = client.DirectoryExists($"{pathToDirectory}");
bool fileExists = client.FileExists($"{pathToFile}");

} throws:

Exception has occurred: CLR/FluentFTP.FtpCommandException
Exception thrown: 'FluentFTP.FtpCommandException' in FluentFTP.dll: 'No files found.'
   at FluentFTP.FtpClient.CloseDataStream(FtpDataStream stream)
   at FluentFTP.FtpDataStream.Close()
   at FluentFTP.FtpClient.GetNameListing(String path)
   at FluentFTP.FtpClient.FileExists(String path)
```

**Logs :**
```
# Connect()
Status:   Connecting to ***:21
Response: 220 Serv-U FTP Server v15.1 ready...
Command:  USER ***
Response: 331 User name okay, need password.
Command:  PASS ***
The thread 10111 has exited with code 0 (0x0).
Response: 230 User logged in, proceed.
Command:  FEAT
Response: 211 Extensions supported
Status:   Text encoding: System.Text.ASCIIEncoding+ASCIIEncodingSealed
Command:  SYST
Response: 215 UNIX Type: L8
Status:   Auto-detected UNIX listing parser
[09:48:56 DBG] Connected to ftp.com...
# DirectoryExists("TarResults\")
# GetWorkingDirectory()
Command:  PWD
Response: 257 "/" is current directory.
Command:  CWD TarResults
Response: 250 Directory changed to /TarResults
Command:  CWD /
Response: 250 Directory changed to /
# FileExists("TarResults\FOXNEWS_20160414_03.tqz")
# GetWorkingDirectory()
Command:  PWD
Response: 257 "/" is current directory.
# GetNameListing("/TarResults")
Command:  TYPE I
Response: 200 Type set to I.
# OpenPassiveDataStream(PASVEX, "NLST /TarResults", 0)
Command:  PASV
Response: 227 Entering Passive Mode (10,10,1,31,225,76)
Status:   Connecting to ***:57676
Command:  NLST /TarResults
Response: 150 Opening ASCII mode data connection for /bin/ls.
Status:   Disposing FtpSocketStream...
# CloseDataStream()
Response: 550 No files found.
```

**Comment by haggerty-william** [comment]
The work around is easy for the time being:
```
bool directoryExists = false;
try { directoryExists = client.DirectoryExists(path); } catch { }
bool fileExists = false;
try { directoryExists = client.FileExists(job.RemoteFile); } catch { }
```

**Comment by haggerty-william** [comment]
I think the underlying issue is also preventing me from using UploadFile() with anything besides existsMode: FtpExists.NoCheck

**Comment by robinrodricks** [comment]
I will fix this soon. I know the fault.

**Comment by haggerty-william** [comment]
Is there another version of the library that isn't affected?

**Comment by robinrodricks** [comment]
I'm working on a fix. Let you know.

**Comment by robinrodricks** [comment]
Released on nuget as https://www.nuget.org/packages/FluentFTP/19.1.2

Can you check that and let me know if it works?

**Comment by haggerty-william** [comment]
Yes, that particular bug seems to be fixed. Although client.UploadFile with createRemoteDir: true seems to be broken, should I submit a different bug report?

**Comment by robinrodricks** [comment]
Please, if you can understand what's going on... Createremotedir has been
reported by many users... Can't quite wrap my head around it, the code
looks solid....
