### ISSUE TITLE
Timed out trying to read data from the socket stream!

### ISSUE THREAD

**Issue by yuguohua** [robinrodricks/FluentFTP#245]
**FTP OS:** HP UNIX

**FTP Server:** wuftpd

**Computer OS:** Windows 7

Get this error on uploading file when no any file in target folder.
There is no error if target folder has file.

**Logs :**
```
target folder is empty and get error

# Connect()
Status:   Connecting to ***:21
Response: 220 FTP server (Revision 9.0 Version wuftpd-2.6.1 Mon Jun 30 09:28:28 GMT 2014) ready.
Command:  USER ***
Response: 331 Password required for xxxx.
Command:  PASS ***
Response: 230 User xxxxlogged in.
Command:  FEAT
Response: 500 'FEAT': command not understood.
Status:   Text encoding: System.Text.ASCIIEncoding
Command:  SYST
Response: 215 UNIX Type: L8
Status:   Auto-detected UNIX listing parser

# UploadFile("xxxxx", "xxxxx", Overwrite, False, None)

# FileExists("xxxxx")

# GetNameListing("xxxxx")
Command:  TYPE I
Response: 200 Type set to I.

# OpenPassiveDataStream(AutoPassive, "NLST xxxxx", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||40240|)
Status:   Connecting to ***:40240
Command:  NLST xxxxx
Response: 226 Transfer complete
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...

# CloseDataStream()
Status:   Disposing FtpSocketStream...

# Dispose()
Status:   Disposing FtpClient object...
Status:   Testing connectivity using Socket.Poll()...
Status:   Testing connectivity using Socket.Poll()...
Status:   Testing connectivity using Socket.Poll()...
Command:  QUIT
Response: 221 Goodbye.
Response: 221-You have transferred 0 bytes in 0 files.
Response: 221-Total traffic for this session was 457 bytes in 0 transfers.
Response: 221-Thank you for using the FTP service on .
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...


Message : "Timed out trying to read data from the socket stream!"	
StackTrace : at FluentFTP.FtpSocketStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at FluentFTP.FtpDataStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at FluentFTP.FtpSocketStream.ReadLine(Encoding encoding)
   at FluentFTP.FtpClient.GetNameListing(String path)
   at FluentFTP.FtpClient.FileExists(String path)
   at FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress)

================
target folder has file and without error

# Connect()
Status:   Connecting to ***:21
Response: 220 FTP server (Revision 9.0 Version wuftpd-2.6.1 Mon Jun 30 09:28:28 GMT 2014) ready.
Command:  USER ***
Response: 331 Password required for xxxx.
Command:  PASS ***
Response: 230 User xxxxlogged in.
Command:  FEAT
Response: 500 'FEAT': command not understood.
Status:   Text encoding: System.Text.ASCIIEncoding
Command:  SYST
Response: 215 UNIX Type: L8
Status:   Auto-detected UNIX listing parser

# UploadFile("xxxx", "xxxxx", Overwrite, False, None)

# FileExists("xxxxx")

# GetNameListing("xxxxx")
Command:  TYPE I
Response: 200 Type set to I.

# OpenPassiveDataStream(AutoPassive, "NLST xxxxx", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||61436|)
Status:   Connecting to ***:61436
Command:  NLST xxxxx
Response: 150 Opening BINARY mode data connection for file list.
Status:   Disposing FtpSocketStream...

# CloseDataStream()
Response: 226 Transfer complete.
Status:   Disposing FtpSocketStream...

# OpenWrite("xxxxx", Binary)
Command:  TYPE I
Response: 200 Type set to I.

# OpenPassiveDataStream(AutoPassive, "STOR xxxxx", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||57719|)
Status:   Connecting to ***:57719
Command:  STOR xxxxx
Response: 150 Opening BINARY mode data connection for xxxxx.
Status:   Disposing FtpSocketStream...
Response: 226 Transfer complete.
Command:  QUIT
Response: 221 Goodbye.
Response: 221-You have transferred 12717 bytes in 1 files.
Response: 221-Total traffic for this session was 13562 bytes in 2 transfers.
Response: 221-Thank you for using the FTP service on .
Status:   Disposing FtpSocketStream...

# Dispose()
Status:   Disposing FtpClient object...
Status:   Disposing FtpSocketStream...

```

**Comment by robinrodricks** [comment]
Same as #122 #244. This ghost bug keeps coming back.

**Comment by franzvalo1** [comment]
I was having this trouble in a machine running Windows Server 2008 r2 and I resolved it by upgrading the Filezilla Server version from 0.9.41 to 0.9.60.
The messages from TimedOut were almost always accompained by a 426 Could Not create Socket, if you have been looking for the root problem maybe you should try upgrading before wasting time in your implementation.

**Comment by robinrodricks** [comment]
Discussion will continue in #122
