### ISSUE TITLE
Exception when verifying after upload

### ISSUE THREAD

**Issue by nskerl** [robinrodricks/FluentFTP#292]
**FTP OS:** Unix 

**FTP Server:** Apache FTP Server

**Computer OS:** Windows

When calling `client.UploadFile` with `FtpVerify.Retry` I sometimes get an error if the destination server decides to move the file prior to FluentFTP getting the checksum. The exception is then interpreted as a transfer error, when in fact the transfer was OK but the checksum failed (due to the file not being accessible shortly after upload completed).

The exception `2018-04-25 14:14:38.989 -07:00 [Error] Exception while sending to ftp target
FluentFTP.FtpCommandException: Command Not Implemented for the Specified Argument`

Is there a combination of flags I can use to mean _verify if the file is still present after upload, otherwise move on (and do not throw)_ ?

**Logs :**

```
2018-04-25 14:14:38.490 -07:00 [Debug] # Connect()
2018-04-25 14:14:38.490 -07:00 [Debug] Status:   Connecting to xxx.xxx.xxx.xxx
2018-04-25 14:14:38.537 -07:00 [Debug] Response: 220 Service ready for new user.
2018-04-25 14:14:38.537 -07:00 [Debug] Command:  USER ftp_xxxxx
2018-04-25 14:14:38.552 -07:00 [Debug] Response: 331 User name okay, need password for ftp_xxxxx
2018-04-25 14:14:38.552 -07:00 [Debug] Command:  PASS ***
2018-04-25 14:14:38.568 -07:00 [Debug] Response: 230 User logged in, proceed.
2018-04-25 14:14:38.568 -07:00 [Debug] Command:  FEAT
2018-04-25 14:14:38.583 -07:00 [Debug] Response: 211 End
2018-04-25 14:14:38.583 -07:00 [Debug] Response: 211-Extensions supported
Response: SIZE
Response: MDTM
Response: REST STREAM
Response: LANG en;zh-tw;ja;is
Response: MLST Size;Modify;Type;Perm
Response: MODE Z
Response: UTF8
Response: TVFS
Response: MD5
Response: MMD5
Response: MFMT
2018-04-25 14:14:38.583 -07:00 [Debug] Status:   Text encoding: System.Text.UTF8Encoding
2018-04-25 14:14:38.583 -07:00 [Debug] Command:  OPTS UTF8 ON
2018-04-25 14:14:38.599 -07:00 [Debug] Response: 200 Command OPTS okay.
2018-04-25 14:14:38.599 -07:00 [Debug] Command:  SYST
2018-04-25 14:14:38.615 -07:00 [Debug] Response: 215 UNIX Type: Apache FtpServer
2018-04-25 14:14:38.615 -07:00 [Debug] Status:   Auto-detected UNIX listing parser
2018-04-25 14:14:38.615 -07:00 [Debug] 
2018-04-25 14:14:38.615 -07:00 [Debug] # SetWorkingDirectory("/")
2018-04-25 14:14:38.615 -07:00 [Debug] Command:  CWD /
2018-04-25 14:14:38.630 -07:00 [Debug] Response: 250 Directory changed to /
2018-04-25 14:14:38.630 -07:00 [Debug] 
2018-04-25 14:14:38.630 -07:00 [Debug] # UploadFile("yak.txt", "yak.txt", Overwrite, False, Retry)
2018-04-25 14:14:38.630 -07:00 [Debug] 
2018-04-25 14:14:38.630 -07:00 [Debug] # FileExists("yak.txt")
2018-04-25 14:14:38.630 -07:00 [Debug] 
2018-04-25 14:14:38.630 -07:00 [Debug] # GetWorkingDirectory()
2018-04-25 14:14:38.630 -07:00 [Debug] Command:  PWD
2018-04-25 14:14:38.646 -07:00 [Debug] Response: 257 "/" is current directory.
2018-04-25 14:14:38.646 -07:00 [Debug] Command:  SIZE /yak.txt
2018-04-25 14:14:38.677 -07:00 [Debug] Response: 550 /yak.txt: No such file or directory.
2018-04-25 14:14:38.677 -07:00 [Debug] 
2018-04-25 14:14:38.677 -07:00 [Debug] # OpenWrite("yak.txt", ASCII)
2018-04-25 14:14:38.677 -07:00 [Debug] Command:  TYPE A
2018-04-25 14:14:38.693 -07:00 [Debug] Response: 200 Command TYPE okay.
2018-04-25 14:14:38.693 -07:00 [Debug] 
2018-04-25 14:14:38.693 -07:00 [Debug] # OpenPassiveDataStream(AutoPassive, "STOR yak.txt", 0)
2018-04-25 14:14:38.693 -07:00 [Debug] Command:  EPSV
2018-04-25 14:14:38.708 -07:00 [Debug] Response: 229 Entering Extended Passive Mode (|||99999|)
2018-04-25 14:14:38.708 -07:00 [Debug] Status:   Connecting to xxx.xxx.xxx.xxx:99999
2018-04-25 14:14:38.724 -07:00 [Debug] Command:  STOR yak.txt
2018-04-25 14:14:38.739 -07:00 [Debug] Response: 150 File status okay; about to open data connection.
2018-04-25 14:14:38.739 -07:00 [Debug] Status:   Disposing FtpSocketStream...
2018-04-25 14:14:38.942 -07:00 [Debug] Response: 226 Transfer complete.
2018-04-25 14:14:38.958 -07:00 [Debug] Command:  MD5 yak.txt
2018-04-25 14:14:38.973 -07:00 [Debug] Response: 504 Command Not Implemented for the Specified Argument
2018-04-25 14:14:38.973 -07:00 [Debug] 
2018-04-25 14:14:38.973 -07:00 [Debug] # Dispose()
2018-04-25 14:14:38.973 -07:00 [Debug] Status:   Disposing FtpClient object...
2018-04-25 14:14:38.973 -07:00 [Debug] Command:  QUIT
2018-04-25 14:14:38.989 -07:00 [Debug] Response: 221 Goodbye.
2018-04-25 14:14:38.989 -07:00 [Debug] Status:   Disposing FtpSocketStream...
2018-04-25 14:14:38.989 -07:00 [Debug] Status:   Disposing FtpSocketStream...

FluentFTP.FtpCommandException: Command Not Implemented for the Specified Argument
   at FluentFTP.FtpClient.GetMD5(String path)
   at FluentFTP.FtpClient.GetChecksum(String path)
   at FluentFTP.FtpClient.VerifyTransfer(String localPath, String remotePath)
   at FluentFTP.FtpClient.UploadFileFromFile(String localPath, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown, FtpVerify verifyOptions, IProgress`1 progress)
   at FluentFTP.FtpClient.UploadFile(String localPath, String remotePath, FtpExists existsMode, Boolean createRemoteDir, FtpVerify verifyOptions, IProgress`1 progress)
   ...

```

**Comment by robinrodricks** [comment]
I'm not sure if this is a bug or a feature request. And as to the flags, I'm not sure how any library should detect if the transfer was successful if the server decided to immediately move the file. If you could contribute another mode of verification it would be appreciated, but again, I'm not sure what that mode would do or check. If you feel there is a fix here, reply and I'll reopen.
