### ISSUE TITLE
GetListing - Cannot create a file when that file already exists. Exception

### ISSUE THREAD

**Issue by grahamehorner** [robinrodricks/FluentFTP#323]
{FluentFTP.FtpCommandException: Cannot create a file when that file already exists. 
   at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at FluentFTP.FtpClient.OpenDataStream(String command, Int64 restart)
   at FluentFTP.FtpClient.GetListing(String path, FtpListOption options)

**Comment by grahamehorner** [comment]
Why has this issue been closed? the issues exists when using the GetListing command, and this is not in anyway creating a file; so as a result the exception is incorrect and very poor; IMHO the exception should NOT hide the details of the command that caused the exception and/or the raw server response.  Please investigate and correct or make the exception more intuitive
