### ISSUE TITLE
Win32Exception : The message or signature supplied for verification has been altered

### ISSUE THREAD

**Issue by rducom** [robinrodricks/FluentFTP#330]
**FTP OS:** Windows

**FTP Server:** Syncplify

**Computer OS:** Windows 10, Windows Server 2016, both up2date
FluentFTP consumed from a netcore2.1 project

While listing with recursion, we have very frequent Win32Exception while using the GetListingAsync method.
`System.ComponentModel.Win32Exception : The message or signature supplied for verification has been altered`

We use a retry policy with 10 retries, and an exponential back-off. Even with that, this issue happens in 50% of our CI builds. (and sometimes in local)

The calling method : 

``` csharp
private async Task<FtpListItem[]> GetListingRecursiveAsync(string directory)
{
	var stack = new Stack<string>();
	stack.Push(directory);
	var totalItems = new List<FtpListItem>();
	while (stack.Count > 0)
	{
		var remotePath = stack.Pop();
		if (!remotePath.EndsWith("/"))
		{
			remotePath += "/";
		}
		FtpListItem[] items = await _ftpClient.GetListingAsync(remotePath, FtpListOption.AllFiles | FtpListOption.Size);
		totalItems.AddRange(items);
		foreach (FtpListItem item in items.Where(i => i.Type == FtpFileSystemObjectType.Directory))
		{
			stack.Push(item.FullName);
		}
	}
	return totalItems.ToArray();
}
```

**Logs :**

```
---- System.ComponentModel.Win32Exception : The message or signature supplied for verification has been altered
Stack Trace:
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__46_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at FluentFTP.FtpSocketStream.ActivateEncryptionAsync(String targethost, X509CertificateCollection clientCerts, SslProtocols sslProtocols)
   at FluentFTP.FtpClient.OpenPassiveDataStreamAsync(FtpDataConnectionType type, String command, Int64 restart)
   at FluentFTP.FtpClient.OpenDataStreamAsync(String command, Int64 restart)
   at FluentFTP.FtpClient.GetListingAsync(String path, FtpListOption options)
   at Infra.Clients.FtpAdapter.GetListingRecursiveAsync(String directory)
```

**Comment by rducom** [comment]
I managed to "fix" this by creating a new `FtpClient` instance (so login / connect / exec command / disconnect / dispose) for *each* call I need to make, by encapsulating this in a Polly retry strategy handling the related exception. Sad but seems to work...

**Comment by robinrodricks** [comment]
Can you show your logs?

**Comment by robinrodricks** [comment]
If you help us debug this maybe we can fix it. Otherwise there's nothing we can do.
