### ISSUE TITLE
Problem with multiple instances - Authentication failed because the remote party has closed the transport stream

### ISSUE THREAD

**Issue by sullivanets1** [robinrodricks/FluentFTP#335]
**FTP OS:**  Windows 

**FTP Server:** filezilla

**Computer OS:**  windows

Any advice for how I can sort the below problem is appreciated.  I have code inside of an httphandler which I am using the serve files on a website. Basically this is used as a dynamic replacement instead of linking directly to a file. It takes an ID as input, checks database & permissions then responds back with the associated file. The file itself is stored off site on a different location. I have been instructed to use ftp to bring the file back to the our server. Our server environment is using .net 3.5.

The code I have is working without error when only a single ftp action is happening at one time.

However when the httphandler is being called multiple times simultaneously (e.g. if 4 people are using it once or one person executes 4 times at once) then some of the executions fail, with exception noted below.

the relevant piece of code for this is as follows

```
            // Prepare ftp details.
            FluentFTP.FtpTrace.AddListener(new System.Diagnostics.TextWriterTraceListener(traceFileAddress));
            FluentFTP.FtpClient client = new FluentFTP.FtpClient(hostAddress, ftpUSername, ftpPassword); 
            client.EncryptionMode = FluentFTP.FtpEncryptionMode.Implicit;  
            client.SslProtocols = System.Security.Authentication.SslProtocols.Tls;
            client.DataConnectionType = FluentFTP.FtpDataConnectionType.EPSV;
            client.ValidateCertificate += new FluentFTP.FtpSslValidation(OnValidateCertificate);


            try
            {
                //Actually connect to ftp server.
                client.Connect();

                client.RetryAttempts = 3;
                client.DownloadFile(downloadByFtpDestination, downloadByFtpSource, true, FtpVerify.Retry | FtpVerify.Throw);

                client.Disconnect();
                result = true;
            }
            catch (Exception ex)
            {
                result = false;
                SsFile.writeToLog("ftp download error", ex.Message + ex.InnerException, procesIdentifier);
            }
```

In the below example in the logs, file 002.zip.zip was successfully downloaded, 001.rar.zip failed.

.net exception
```
Error while downloading the file from the server. See InnerException for more info.System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at FluentFTP.FtpSocketStream.ActivateEncryption(String targethost, X509CertificateCollection clientCerts, SslProtocols sslProtocols)
   at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at FluentFTP.FtpClient.OpenDataStream(String command, Int64 restart)
   at FluentFTP.FtpClient.OpenRead(String path, FtpDataType type, Int64 restart, Boolean checkIfFileExists)
   at FluentFTP.FtpClient.DownloadFileInternal(String remotePath, Stream outStream, IProgress`1 progress)
```

**Logs :**

```

# Connect()
Status:   Connecting to **Debug-IP-Address*:990

# Connect()
Status:   Connecting to **Debug-IP-Address*:990
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.1130339.
Response: 220 Please visit https://filezilla-project.org/
Response: 220-FileZilla Server 0.9.60 beta
Response: 220-written by Tim Kosse (tim.kosse@filezilla-project.org)
Command:  USER debugUser
Response: 331 Password required for debugUser
Command:  PASS ***
Response: 230 Logged on
Command:  PBSZ 0
Response: 200 PBSZ=0
Command:  PROT P
Response: 200 Protection level set to P
Command:  FEAT
Response: 211 End
Response: 211-Features:
Response: MDTM
Response: REST STREAM
Response: SIZE
Response: MLST type*;size*;modify*;
Response: MLSD
Response: AUTH SSL
Response: AUTH TLS
Response: PROT
Response: PBSZ
Response: UTF8
Response: CLNT
Response: MFMT
Response: EPSV
Response: EPRT
Status:   Text encoding: System.Text.UTF8Encoding
Command:  OPTS UTF8 ON
Response: 202 UTF8 mode is always enabled. No need to send this command.
Command:  SYST
Status:   FTPS Authentication Successful
Response: 215 UNIX emulated by FileZilla
Status:   Auto-detected UNIX listing parser
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.1160348.

# DownloadFile("c:\debug\encrypted\001.rar.zip", "/debug/001.rar.zip", True, Retry, Throw)
Response: 220 Please visit https://filezilla-project.org/
Response: 220-FileZilla Server 0.9.60 beta
Response: 220-written by Tim Kosse (tim.kosse@filezilla-project.org)
Command:  USER debugUser
Response: 331 Password required for debugUser
Command:  PASS ***

Response: 230 Logged on
Command:  PBSZ 0
# OpenRead("/debug/001.rar.zip", Binary, 0)
Command:  TYPE I
Response: 200 PBSZ=0
Command:  PROT P
Response: 200 Type set to I
Response: 200 Protection level set to P
Command:  FEAT

# OpenPassiveDataStream(EPSV, "RETR /debug/001.rar.zip", 0)
Command:  EPSV
Response: 211 End
Response: 211-Features:
Response: MDTM
Response: REST STREAM
Response: SIZE
Response: MLST type*;size*;modify*;
Response: MLSD
Response: AUTH SSL
Response: AUTH TLS
Response: PROT
Response: PBSZ
Response: UTF8
Response: CLNT
Response: MFMT
Response: EPSV
Response: EPRT

# Dispose()
Status:   Disposing FtpClient object...
Status:   Testing connectivity using Socket.Poll()...
Status:   Text encoding: System.Text.UTF8Encoding
Command:  OPTS UTF8 ON
Response: 229 Entering Extended Passive Mode (|||50508|)
Response: 202 UTF8 mode is always enabled. No need to send this command.
Command:  SYST
Response: 215 UNIX emulated by FileZilla
Status:   Auto-detected UNIX listing parser

Status:   Connecting to **Debug-IP-Address*:50508
# DownloadFile("c:\debug\encrypted\002.zip.zip", "/debug/002.zip.zip", True, Retry, Throw)
Command:  RETR /debug/001.rar.zip

# OpenRead("/debug/002.zip.zip", Binary, 0)
Command:  TYPE I
Response: 150 Opening data channel for file download from server of "/debug/001.rar.zip"
Response: 200 Type set to I

# OpenPassiveDataStream(EPSV, "RETR /debug/002.zip.zip", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||50272|)
Status:   Connecting to **Debug-IP-Address*:50272
Command:  RETR /debug/002.zip.zip
Response: 150 Opening data channel for file download from server of "/debug/002.zip.zip"
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.0080024.
Command:  QUIT
Response: 221 Goodbye
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
Response: 226 Successfully transferred "/debug/002.zip.zip"
File Verification: PASS
Command:  QUIT
Response: 221 Goodbye
Status:   Disposing FtpSocketStream...

# Dispose()
Status:   Disposing FtpClient object...
Status:   There is stale data on the socket, maybe our connection timed out or you did not call GetReply(). Re-connecting...
Status:   Disposing FtpSocketStream...
Status:   Not sending QUIT because the connection has already been closed.
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...

# Dispose()
Status:   Disposing FtpClient object...
Status:   Disposing FtpSocketStream...

```

**Comment by grahamehorner** [comment]
also seeing this on a regular basis

**Comment by grahamehorner** [comment]
FileZilla is the issue here; the TLS session resumption needs to be turned on

**Comment by frankvl76** [comment]
I had the same issue in a production environment. Turning that feature off was not an option. I've put a lock around the part where you actually create the client and transfer data. 

So something like 

lock(lockObject)
{
                client.Connect();

                client.RetryAttempts = 3;
                client.DownloadFile(downloadByFtpDestination, downloadByFtpSource, true, FtpVerify.Retry | FtpVerify.Throw);

                client.Disconnect();
}

Even though this is sub-optimal, it works.

**Comment by CyberMist2** [comment]
> I had the same issue in a production environment. Turning that feature off was not an option. I've put a lock around the part where you actually create the client and transfer data.
> 
> So something like
> 
> lock(lockObject)
> {
> client.Connect();
> 
> ```
>             client.RetryAttempts = 3;
>             client.DownloadFile(downloadByFtpDestination, downloadByFtpSource, true, FtpVerify.Retry | FtpVerify.Throw);
> 
>             client.Disconnect();
> ```
> 
> }
> 
> Even though this is sub-optimal, it works.

Thanks this worked for me

**Comment by starquake** [comment]
I have the same issue but with upload. Somehow the workaround doesn't work. Any other ideas on how to work around this?

**Comment by pmarangoni** [comment]
> I have the same issue but with upload. Somehow the workaround doesn't work. Any other ideas on how to work around this?

Same here. In my case, it's running in a legacy ASP.NET 4.6.1 Web Forms application.
