### ISSUE TITLE
FTPS+TLS exception: An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by ww898** [robinrodricks/FluentFTP#397]
**Client:** FluentFTP 23.1.0
**FTP Server:** vsftpd 2.2.2
**Computer OS:** Windows 10 Pro x64

**Exception:**
```
--- EXCEPTION #1/3 [SocketException]
Message = “An established connection was aborted by the software in your host machine”
ExceptionPath = Root.InnerException.InnerException
NativeErrorCode = 10053
ClassName = System.Net.Sockets.SocketException
HResult = E_FAIL=EFail=80004005
Source = System
StackTraceString = “
  at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
     at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
”

--- Outer ---

--- EXCEPTION #2/3 [IOException]
Message = “Unable to write data to the transport connection: An established connection was aborted by the software in your host machine.”
ExceptionPath = Root.InnerException
ClassName = System.IO.IOException
Data.id = xxx.pdb\yyy\xxx.pdb
Data.length = 7344
Data.overwrite = False
InnerException = “Exception #1 at Root.InnerException.InnerException”
HResult = COR_E_IO=80131620
Source = System
StackTraceString = “
  at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
     at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
     at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
     at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
     at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
     at System.IO.BufferedStream.<FlushWriteAsync>d__42.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.IO.BufferedStream.<ReadFromUnderlyingStreamAsync>d__51.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Threading.Tasks.TaskToApm.End[TResult](IAsyncResult asyncResult)
     at System.Net.FixedSizeReader.StartReading()
     at System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
     at System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
     at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
     at System.Net.Security._SslStream.BeginRead(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
     at FluentFTP.FtpSocketStream.Read(Byte[] buffer, Int32 offset, Int32 count)
     at FluentFTP.FtpSocketStream.ReadLine(Encoding encoding)
     at FluentFTP.FtpClient.GetReply()
     at FluentFTP.FtpClient.Execute(String command)
     at FluentFTP.FtpClient.DirectoryExists(String path)
...
”
```

**Logs :**
```
[V] >         Connect()
[ ] Status:   Connecting to 172.mm.tt.zz:21
[ ] Response: 220 (vsFTPd 2.2.2)
[ ] Status:   Detected FTP server: VsFTPd
[ ] Command:  AUTH TLS
[ ] Response: 234 Proceed with negotiation.
[ ] Status:   FTPS Authentication Successful
[V] Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.0020831.
[ ] Command:  USER pdb
[ ] Response: 331 Please specify the password.
[ ] Command:  PASS ***
[ ] Response: 230 Login successful.
[ ] Command:  PBSZ 0
[ ] Response: 200 PBSZ set to 0.
[ ] Command:  PROT P
[ ] Response: 200 PROT now Private.
[ ] Command:  FEAT
[ ] Response: 211 End
[V] Response: 211-Features:
Response: AUTH SSL
Response: AUTH TLS
Response: EPRT
Response: EPSV
Response: MDTM
Response: PASV
Response: PBSZ
Response: PROT
Response: REST STREAM
Response: SIZE
Response: TVFS
Response: UTF8
[ ] Status:   Text encoding: System.Text.UTF8Encoding
[ ] Command:  OPTS UTF8 ON
[ ] Response: 200 Always in UTF8 mode.
[ ] Command:  SYST
[ ] Response: 215 UNIX Type: L8
[ ] Status:   Auto-detected UNIX listing parser
[V] >         DirectoryExists("/content_lowercase")
[V] >         GetWorkingDirectory()
[ ] Command:  PWD
[ ] Response: 257 "/"
[ ] Command:  CWD /content_lowercase
[ ] Response: 250 Directory successfully changed.
[ ] Command:  CWD /
[ ] Response: 250 Directory successfully changed.
[V] >         FileExists("/content_lowercase/pingme.txt")
[ ] Command:  SIZE /content_lowercase/pingme.txt
[ ] Response: 213 0
[V] >         GetFileSize("/content_lowercase/pingme.txt")
[ ] Command:  TYPE I
[ ] Response: 200 Switching to Binary mode.
[ ] Command:  SIZE /content_lowercase/pingme.txt
[ ] Response: 213 0
[ ] Command:  TYPE A
[ ] Response: 200 Switching to ASCII mode.
[V] >         GetModifiedTime("/content_lowercase/pingme.txt", Original)
[ ] Command:  MDTM /content_lowercase/pingme.txt
[ ] Response: 213 20171112131421
... <<<<<<<<<<<<<<A lot of operation here>>>>>>>>>>>
[ ] Command:  PWD
[ ] Response: 257 "/"
[ ] Command:  CWD /content_lowercase/xxx.pdb
```

**Comment by robinrodricks** [comment]
Fixed in 25.0.0.

**Comment by robinrodricks** [comment]
@ww898 please check if it works with the latest version, so I can close this issue.

**Comment by robinrodricks** [comment]
If you have issues reply here and I'll reopen this issue.

**Comment by ww898** [comment]
The bug is alive! I got it on v25.0.5

**Comment by robinrodricks** [comment]
Oh god.

**Comment by robinrodricks** [comment]
Do you have a firewall or something interfering with network traffic? This may not be a bug in FluentFTP.

See https://stackoverflow.com/a/14305484

**Comment by ww898** [comment]
Windows Defender is disabled. No additional antiviruses are installed. Everything work properly when TLS mode is disabled, but fail with TLS.

**Comment by wfurt** [comment]
This can be also upstream firewall. If there is any signature based IDS there is always chance for false positives with SSL/binary. From the trace it seems like the connection just dies in the middle.
