### ISSUE TITLE
Thread was being aborted.

### ISSUE THREAD

**Issue by NimishDavid** [robinrodricks/FluentFTP#403]
I am using the following code:

```
FtpClient client = new FtpClient("ftp://ftp.mims.com.au")
{
    // if you don't specify login credentials, we use the "anonymous" user account
    Credentials = credentials,
    DataConnectionType = FtpDataConnectionType.EPSV,
    DataConnectionReadTimeout = Int32.MaxValue,
    ReadTimeout = Int32.MaxValue,
    DataConnectionConnectTimeout = Int32.MaxValue
};
CreateFiles(client, "", basePath);

private void CreateFiles(FtpClient client, string ftpPath, string filePath)
{
    client.Connect();

    if (!_storageProvider.FolderExists(filePath))
        _storageProvider.CreateFolder(filePath);


    var listing = client.GetListing(ftpPath);
    // get a list of files and directories in the "/htdocs" folder
    foreach (FtpListItem item in listing)
    {
        // if this is a file
        if (item.Type == FtpFileSystemObjectType.File)
        {
            // get the file size
            long size = client.GetFileSize(item.FullName);

            // download the file
            using (var stream = new MemoryStream())
            {
                // download to stream
                client.Download(stream, item.FullName);
                // save stream to file path
                stream.Position = 0;
                _storageProvider.SaveStream(_storageProvider.Combine(filePath, item.Name), stream);
            }
        }
        else
        {
            var currentLocalPath = _storageProvider.Combine(filePath, item.Name);
            var currentFtpPath = _storageProvider.Combine(ftpPath, item.FullName);
            CreateFiles(client, currentFtpPath, currentLocalPath);
        }
    }

    client.Disconnect();
}
```

This works fine for downloading the folders and files from the FTP server. But when it reaches a big file, say, 300 MB in size, it throws this exception after a few minutes:

`Exception: Error while downloading the file from the server. See InnerException for more info.`

```
Stack Trace:    at FluentFTP.FtpClient.DownloadFileInternal(String remotePath, Stream outStream, Int64 restartPosition, IProgress`1 progress)
   at MasterCare.MIMS.Australia.Services.MimsFtpService.CreateFiles(FtpClient client, String ftpPath, String filePath) in E:\Master Care\mastercare-mims-australia\Modules\MasterCare.MIMS.Australia\Services\MimsFtpService.cs:line 115
   at MasterCare.MIMS.Australia.Services.MimsFtpService.CreateFiles(FtpClient client, String ftpPath, String filePath) in E:\Master Care\mastercare-mims-australia\Modules\MasterCare.MIMS.Australia\Services\MimsFtpService.cs:line 126
   at MasterCare.MIMS.Australia.Services.MimsFtpService.CreateFiles(FtpClient client, String ftpPath, String filePath) in E:\Master Care\mastercare-mims-australia\Modules\MasterCare.MIMS.Australia\Services\MimsFtpService.cs:line 126
   at MasterCare.MIMS.Australia.Services.MimsFtpService.UpdateMimsDataset(NetworkCredential credentials) in E:\Master Care\mastercare-mims-australia\Modules\MasterCare.MIMS.Australia\Services\MimsFtpService.cs:line 80
   at MasterCare.MIMS.Australia.Events.MIMSEventHandler.DownloadMIMSZipFile(Object data, IWorkContextScope orchardWorkContext, ILogger logger) in E:\Master Care\mastercare-mims-australia\Modules\MasterCare.MIMS.Australia\Events\MIMSEventHandler.cs:line 130
   at MasterCare.BackgroundJobs.Services.BackgroundJobRunner.Run(Context context, IWorkContextScope workContextScope)
```

`Inner Exception: Thread was being aborted.`

```
Inner Exception Stack Trace:    at System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle, UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   at FluentFTP.FtpSocketStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at FluentFTP.FtpDataStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at FluentFTP.FtpClient.DownloadFileInternal(String remotePath, Stream outStream, Int64 restartPosition, IProgress`1 progress)
```

**Comment by robinrodricks** [comment]
Can you check with recent versions, it might be fixed.

If you respond I will reopen this.
