### ISSUE TITLE
Support "STAT -l" listing

### ISSUE THREAD

**Issue by Hidend** [robinrodricks/FluentFTP#440]
**FTP OS:** Unix / Windows / Embedded
Windows
**FTP Server:** Pure-FTPd / DrFTPD / Vsftpd / ProFTPD / Vax / VMS / OpenVMS / Tandem / HP NonStop Guardian / IBM OS400 / AS400 / Windows CE
DrFTPD

**Computer OS:** ?
Windows

STAT -l is not supported for listing, my FTP Server just does support that for listing so I'm not able to basically list. I tried to implement it myself but I failed to do so, it tries to use OpenPassiveDataStream from [FtpClient_Listing](https://github.com/robinrodricks/FluentFTP/blob/master/FluentFTP/Client/FtpClient_Listing.cs#L416) when I think it shouldn't at all. Since I tried to do it myself I can't really post anything useful I think...

**Logs :**

```
# Connect()
Status:   Connecting to X
Response: 220 ProFTPD 1.2.11 Server (GNU/Linux)
Status:   Detected FTP server: ProFTPD
Command:  USER X
Response: 331 Password required for X.
Command:  PASS ***
Response: 230 user logged in successfully.
Response: 230-
Response: 230-
Response: 230-
Command:  FEAT
Response: 211 End
Response: 211-Extensions supported:
Response: MLST type*,x.crc32*,size*,modify*,unix.owner*,unix.group*,x.slaves*,x.xfertime*
Response: PRET
Response: CPSV
Response: NOOP
Response: CLNT
Response: AUTH TLS
Response: PBSZ
Response: SITE XDUPE
Response: SSCN
Status:   Text encoding: System.Text.ASCIIEncoding
Command:  SYST
Response: 215 UNIX system type.

# GetListing("/", UseSTAT)
Command:  TYPE I
Response: 200 Command okay

# OpenPassiveDataStream(AutoPassive, "STAT -l /", 0)
Command:  EPSV
Response: 502 Command not implemented.

# OpenPassiveDataStream(PASV, "STAT -l /", 0)
Command:  STAT -l /
Response: 213 End of STAT
Response: 213-STAT
Response: total 0
Response: drwxrwxrwx 3  drftpd3  drftpd3 99583753142 Aug  8 03:51 TEST-FOLDER
Response: drwxrwxrwx 3  drftpd3  drftpd3 260256382636 Aug  9 07:36 TEST-FOLDER2
Command:  PASV
Response: 500 You need to use a client supporting PRET (PRE Transfer) to use PASV
Exception thrown: 'FluentFTP.FtpCommandException' in FluentFTP.dll
An unhandled exception of type 'FluentFTP.FtpCommandException' occurred in FluentFTP.dll
You need to use a client supporting PRET (PRE Transfer) to use PASV
```

**Comment by robinrodricks** [comment]
Hi

Just use `client.Execute("STAT -l");` and then tell me what response the server gives (copy paste the logs).

**Comment by robinrodricks** [comment]
Can you try this and see if it works?

The usage syntax is `client.GetListing("your directory path here", FtpListOption.UseStat)`

[Release.zip](https://github.com/robinrodricks/FluentFTP/files/3495603/Release.zip)

**Comment by Hidend** [comment]
I'm getting this:
```
# Connect()
Status:   Connecting to X
Response: 220 ProFTPD 1.2.11 Server (GNU/Linux)
Status:   Detected FTP server: ProFTPD
Command:  USER X
Response: 331 Password required for X.
Command:  PASS ***
Response: 230 user logged in successfully.
Response: 230-
Response: 230-
Response: 230-
Command:  FEAT
Response: 211 End
Response: 211-Extensions supported:
Response: MLST type*,x.crc32*,size*,modify*,unix.owner*,unix.group*,x.slaves*,x.xfertime*
Response: PRET
Response: CPSV
Response: NOOP
Response: CLNT
Response: AUTH TLS
Response: PBSZ
Response: SITE XDUPE
Response: SSCN
Status:   Text encoding: System.Text.ASCIIEncoding
Command:  SYST
Response: 215 UNIX system type.

# GetListing("/", UseStat)
Command:  TYPE I
Response: 200 Command okay
Command:  STAT -l /
Response: 213 End of STAT
Response: 213-STAT
Response: total 0
Response: drwxrwxrwx 3  drftpd3  drftpd3 99583753142 Aug  8 03:51 TEST-FOLDER
Response: drwxrwxrwx 3  drftpd3  drftpd3 260256382636 Aug  9 07:36 TEST-FOLDER2
+---------------------------------------+
Listing:  213-STAT
Listing:  total 0
Response: drwxrwxrwx 3  drftpd3  drftpd3 99583753142 Aug  8 03:51 TEST-FOLDER
Response: drwxrwxrwx 3  drftpd3  drftpd3 260256382636 Aug  9 07:36 TEST-FOLDER2
-----------------------------------------
Status:   Not in UNIX format
Status:   Not in UNIX format
Status:   Not in Windows format
Status:   Not in OS/400 format
Status:   Not in VMS format
Status:   Could not detect format. Using default Unix
Warning:  Failed to parse file listing: 213-STAT
Status:   Not in UNIX format
Status:   Not in UNIX format
Status:   Not in Windows format
Status:   Not in OS/400 format
Status:   Not in VMS format
Status:   Could not detect format. Using default Unix
Warning:  Failed to parse file listing: total 0
Status:   Confirmed format Unix

# Dispose()
Status:   Disposing FtpClient object...
Command:  QUIT
Exception thrown: 'System.ObjectDisposedException' in System.dll
Warning:  FtpClient.Disconnect(): Exception caught and discarded while closing control connection: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at FluentFTP.FtpSocketStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at FluentFTP.FtpSocketStream.WriteLine(Encoding encoding, String buf)
   at FluentFTP.FtpClient.Execute(String command)
   at FluentFTP.FtpClient.Disconnect()
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
```

**Comment by robinrodricks** [comment]
I have no idea hows those Response lines are getting printed within the Listing block (between the separators). Did you change the code perhaps?

**Comment by robinrodricks** [comment]
Can you try this:

[Release.zip](https://github.com/robinrodricks/FluentFTP/files/3520106/Release.zip)

**Comment by robinrodricks** [comment]
Hello, can you try the release? I have been providing support and you just ghosted halfway through. As of now there's a half-baked implementation of `STAT -l` maybe if you help we can complete it..

**Comment by robinrodricks** [comment]
Until you respond we cannot continue to develop this. Its a pity because I put a lot of effort into Stat listings.
