### ISSUE TITLE
Cannot upload files to portable ftp server wunning on netcoreapp.

### ISSUE THREAD

**Issue by Maciejszuchta** [robinrodricks/FluentFTP#445]
**FTP OS:** Unix 

**FTP Server:** https://github.com/FubarDevelopment/FtpServer

**Computer OS: Windows

Unix server is hosting netcoreapp2.2 which has portable ftp server https://github.com/FubarDevelopment/FtpServer
When running locally I can connect with this server, upload and download files without issues.
However, when I deployed this application on AWS (Unix) machine that is behind Nginx reverse Proxy I cannot upload the files
```
Error while uploading the file to the server. See InnerException for more info.
   at FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress)
   at FluentFTP.FtpClient.UploadFileFromFile(String localPath, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown, FtpVerify verifyOptions, IProgress`1 progress)
   at FluentFTP.FtpClient.UploadFile(String localPath, String remotePath, FtpExists existsMode, Boolean createRemoteDir, FtpVerify verifyOptions, IProgress`1 progress)
   at DelegatorModule.Controllers.FileTransferController.<UploadBuild>d__11.MoveNext() in D:\work\AITeF\DelegatorModule\DelegatorModule\Controllers\FileTransferController.cs:line 195
-------------------------------------------------------------
InnerException
Timed out trying to connect!
   at FluentFTP.FtpSocketStream.Connect(String host, Int32 port, FtpIpVersion ipVersions)
   at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at FluentFTP.FtpClient.OpenDataStream(String command, Int64 restart)
   at FluentFTP.FtpClient.OpenWrite(String path, FtpDataType type, Boolean checkIfFileExists)
   at FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress)
```
I can succesfully change the working directory or create new folder. But uploading doesnt work.

```

# Connect()
Status:   Connecting to ***:27021
Response: 220 FTP Server Ready
Command:  USER ***
Response: 331 User admin logged in, needs password
Command:  PASS ***
Response: 230 Password ok, FTP server ready
Command:  FEAT
Response: 211 END
Response: 211-Extensions supported:
Response: EPRT
Response: EPSV
Response: HOST
Response: LANG en*
Response: MDTM
Response: MFCT
Response: MFF modify;create;
Response: MFMT
Response: MLST type*;size*;perm*;modify*;create*;
Response: REST STREAM
Response: SITE BLST
Response: SIZE
Response: UTF8
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Response: 200 Command okay.
Command:  SYST
Response: 215 UNIX Type: A

# SetWorkingDirectory("ExampleGame")
Command:  CWD ExampleGame
Response: 250 Successful (/ExampleGame/)

# UploadFile("C:/AitefUploads\ExampleGameProject.zip", "Windows/ExampleGameProject.zip", NoCheck, False, None)

# OpenWrite("Windows/ExampleGameProject.zip", Binary)
Command:  TYPE I
Response: 200 Binary transfer mode active.

# OpenPassiveDataStream(EPSV, "STOR Windows/ExampleGameProject.zip", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||36927|).
Status:   Connecting to ***:36927
Status:   Disposing FtpSocketStream...

# Dispose()
Status:   Disposing FtpClient object...
Status:   Testing connectivity using Socket.Poll()...
Command:  QUIT
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
```

Any ideas what is wrong here?

**Comment by robinrodricks** [comment]
Try AutoConnect() and see if it works...

Or try some other connection modes - Passive/Active is more reliable than Enhanced modes...

**Comment by robinrodricks** [comment]
I'll reopen this when you get back..
