### ISSUE TITLE
Can work with Load Balancing FTP?

### ISSUE THREAD

**Issue by momo898989** [robinrodricks/FluentFTP#495]
**FTP OS:** Unix / Windows / Embedded

**FTP Server:** Pure-FTPd / DrFTPD / Vsftpd / ProFTPD / Vax / VMS / OpenVMS / Tandem / HP NonStop Guardian / IBM OS400 / AS400 / Windows CE

**Computer OS:** ?

My client is using FTP with Network Load Balancing.
https://developer.veevavault.com/docs/#performance-and-enhancements  

client.Connect() call is OK, 
After then, when I upload a file to the ftp, it throws an exception "Timed out trying to connect!".

   at FluentFTP.FtpSocketStream.Connect(String host, Int32 port, FtpIpVersion ipVersions)
   at FluentFTP.FtpClient.Connect(FtpSocketStream stream, String host, Int32 port, FtpIpVersion ipVersions)
   at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at FluentFTP.FtpClient.OpenDataStream(String command, Int64 restart)
   at FluentFTP.FtpClient.OpenWrite(String path, FtpDataType type, Boolean checkIfFileExists)
   at FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown)

It looks like IP address was changed due to Load Balancing.
My client recommend to set ftpsClient.setRemoteVerificationEnabled to false for java ftp client library.
FluentFTP has such an option to work with FTP on Network Load Balancing?

Just note that FileZilla works fine that ftp server.

**Logs :**

```
<paste logs here but DO NOT delete the lines above and below this line>
```

**Comment by robinrodricks** [comment]
I'm not sure what apache means by remote verification. If you can be more technically specific maybe we can implement such a thing. Check these properties (https://github.com/robinrodricks/FluentFTP#ftps) and see if any are of use to you.

**Comment by robinrodricks** [comment]
When you respond I'll reopen.
