### ISSUE TITLE
FluentFTP.FtpCommandException: Access is denied.

### ISSUE THREAD

**Issue by bcireddu** [robinrodricks/FluentFTP#556]
**FTP OS:**  Windows 

**FTP Server:** WindowsServerIIS

**Computer OS:** Windows 10

**FluentFTP Version:** 32.3.0

I am able to download when connecting to the server using Core from the same machine and I am able to download when connecting with a legacy program I developed close to 10 years ago using AlexFTP.  This isn't a permissions issue.

Error while downloading the file from the server. See InnerException for more info.

FluentFTP.FtpCommandException: Access is denied.
   at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at FluentFTP.FtpClient.OpenDataStream(String command, Int64 restart)
   at FluentFTP.FtpClient.OpenRead(String path, FtpDataType type, Int64 restart, Boolean checkIfFileExists)
   at FluentFTP.FtpClient.DownloadFileInternal(String localPath, String remotePath, Stream outStream, Int64 restartPosition, Action`1 progress, FtpProgress metaProgress, Int64 knownFileSize, Boolean isAppend)

**Logs :**

```


# Connect()
Status:   Connecting to ***:990
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.4662975.
Response: 220-Microsoft FTP Service
Response: -~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-
Response: ##############
Response: Unauthorized use prohibited.
Response: 220 -~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-
Status:   Detected FTP server: WindowsServerIIS
Command:  USER ***
Response: 331 Password required for classicoptical.
Command:  PASS ***
Response: 230 User logged in.
Command:  PBSZ 0
Response: 200 PBSZ command successful.
Command:  PROT P
Response: 200 PROT command successful.
Command:  FEAT
Response: 211-Extended features supported:
Response: LANG EN*
Response: UTF8
Response: AUTH TLS;TLS-C;SSL;TLS-P;
Response: PBSZ
Response: PROT C;P;
Response: CCC
Response: HOST
Response: SIZE
Response: MDTM
Response: REST STREAM
Response: 211 END
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Response: 200 OPTS UTF8 command successful - UTF8 encoding now ON.
Command:  SYST
Response: 215 Windows_NT

# GetListing("/Outbound/Test", Auto)
Command:  TYPE I
Response: 200 Type set to I.

# OpenPassiveDataStream(AutoPassive, "LIST /Outbound/Test", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||50001|)
Status:   Connecting to ***:50001
Command:  LIST /Outbound/Test
Response: 125 Data connection already open; Transfer starting.
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.0914045.
+---------------------------------------+
Listing:  03-29-20  07:15PM                 2851 Classic_20200329_130716.xml
Listing:  03-29-20  07:15PM                 2946 Classic_20200329_153730.xml
Listing:  03-30-20  01:40PM                 2850 Classic_20200329_203802.xml
-----------------------------------------
Status:   Disposing FtpSocketStream...

# CloseDataStream()
Response: 226 Transfer complete.
Status:   Disposing FtpSocketStream...
Status:   Confirmed format Windows

# GetFileSize("/Outbound/Test/Classic_20200329_130716.xml")
Command:  SIZE /Outbound/Test/Classic_20200329_130716.xml
Response: 213 2851

# GetModifiedTime("/Outbound/Test/Classic_20200329_130716.xml", Original)
Command:  MDTM /Outbound/Test/Classic_20200329_130716.xml
Response: 213 20200330021503

# GetFilePermissions("/Outbound/Test/Classic_20200329_130716.xml")

# GetObjectInfo("/Outbound/Test/Classic_20200329_130716.xml", False)

# GetListing("/Outbound/Test", Auto)
Command:  TYPE I
Response: 200 Type set to I.

# OpenPassiveDataStream(AutoPassive, "LIST /Outbound/Test", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||50002|)
Status:   Connecting to ***:50002
Command:  LIST /Outbound/Test
Response: 125 Data connection already open; Transfer starting.
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.0924472.
+---------------------------------------+
Listing:  03-29-20  07:15PM                 2851 Classic_20200329_130716.xml
Listing:  03-29-20  07:15PM                 2946 Classic_20200329_153730.xml
Listing:  03-30-20  01:40PM                 2850 Classic_20200329_203802.xml
-----------------------------------------
Status:   Disposing FtpSocketStream...

# CloseDataStream()
Response: 226 Transfer complete.
Status:   Disposing FtpSocketStream...
Warning:  Failed to get object info for path /Outbound/Test/Classic_20200329_130716.xml since MLST not supported and GetListing() fails to list file/folder.

# GetFileSize("/Outbound/Test/Classic_20200329_153730.xml")
Command:  SIZE /Outbound/Test/Classic_20200329_153730.xml
Response: 213 2946

# GetModifiedTime("/Outbound/Test/Classic_20200329_153730.xml", Original)
Command:  MDTM /Outbound/Test/Classic_20200329_153730.xml
Response: 213 20200330021506

# GetFilePermissions("/Outbound/Test/Classic_20200329_153730.xml")

# GetObjectInfo("/Outbound/Test/Classic_20200329_153730.xml", False)

# GetListing("/Outbound/Test", Auto)
Command:  TYPE I
Response: 200 Type set to I.

# OpenPassiveDataStream(AutoPassive, "LIST /Outbound/Test", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||50004|)
Status:   Connecting to ***:50004
Command:  LIST /Outbound/Test
Response: 125 Data connection already open; Transfer starting.
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.0846633.
+---------------------------------------+
Listing:  03-29-20  07:15PM                 2851 Classic_20200329_130716.xml
Listing:  03-29-20  07:15PM                 2946 Classic_20200329_153730.xml
Listing:  03-30-20  01:40PM                 2850 Classic_20200329_203802.xml
-----------------------------------------
Status:   Disposing FtpSocketStream...

# CloseDataStream()
Response: 226 Transfer complete.
Status:   Disposing FtpSocketStream...
Warning:  Failed to get object info for path /Outbound/Test/Classic_20200329_153730.xml since MLST not supported and GetListing() fails to list file/folder.

# GetFileSize("/Outbound/Test/Classic_20200329_203802.xml")
Command:  SIZE /Outbound/Test/Classic_20200329_203802.xml
Response: 213 2850

# GetModifiedTime("/Outbound/Test/Classic_20200329_203802.xml", Original)
Command:  MDTM /Outbound/Test/Classic_20200329_203802.xml
Response: 213 20200330204024

# GetFilePermissions("/Outbound/Test/Classic_20200329_203802.xml")

# GetObjectInfo("/Outbound/Test/Classic_20200329_203802.xml", False)

# GetListing("/Outbound/Test", Auto)
Command:  TYPE I
Response: 200 Type set to I.

# OpenPassiveDataStream(AutoPassive, "LIST /Outbound/Test", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||50003|)
Status:   Connecting to ***:50003
Command:  LIST /Outbound/Test
Response: 125 Data connection already open; Transfer starting.
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.0869878.
+---------------------------------------+
Listing:  03-29-20  07:15PM                 2851 Classic_20200329_130716.xml
Listing:  03-29-20  07:15PM                 2946 Classic_20200329_153730.xml
Listing:  03-30-20  01:40PM                 2850 Classic_20200329_203802.xml
-----------------------------------------
Status:   Disposing FtpSocketStream...

# CloseDataStream()
Response: 226 Transfer complete.
Status:   Disposing FtpSocketStream...
Warning:  Failed to get object info for path /Outbound/Test/Classic_20200329_203802.xml since MLST not supported and GetListing() fails to list file/folder.

# DownloadFile("C:\Sites\.DataFiles\Classic\March\Classic_20200329_203802.xml", "/Outbound/Test", Skip, Retry)

# OpenRead("/Outbound/Test", Binary, 0)
Command:  TYPE I
Response: 200 Type set to I.

# OpenPassiveDataStream(AutoPassive, "RETR /Outbound/Test", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||50005|)
Status:   Connecting to ***:50005
Command:  RETR /Outbound/Test
Response: 550 Access is denied. 
Status:   Disposing FtpSocketStream...

# CloseDataStream()


```

**Comment by robinrodricks** [comment]
550 Access is denied means your FTP account does not have permissions to access the file. Can you try with filezilla and see if it works by using the same FTP account?

**Comment by robinrodricks** [comment]
When you respond I will reopen this.
