### ISSUE TITLE
Can't Cancel Downloading when Listing Directories

### ISSUE THREAD

**Issue by 263613093** [robinrodricks/FluentFTP#565]
**FTP OS:** Unix / Windows / Embedded

**FTP Server:** Pure-FTPd / DrFTPD / Vsftpd / ProFTPD / Vax / VMS / OpenVMS / Tandem / HP NonStop Guardian / IBM OS400 / AS400 / Windows CE

**Computer OS:** ? Windows 10

**FluentFTP Version:** 32.3.1

Can't cancel downloading when listing directories on GetListingRecursiveAsync method

**Logs :**

<paste logs here>

```

my be need a CancelTokenSource parameter in this method
and break loop in this method when cancelled

**Comment by robinrodricks** [comment]
Thanks for finding this.

**Comment by robinrodricks** [comment]
#### 32.3.4

  - Fix: Implement proper cancellation support in `UploadDirectory` (once file transfer begins it cannot be cancelled)
  - Fix: Implement proper cancellation support in `DownloadDirectory` (once file transfer begins it cannot be cancelled)
  - Fix: Implement proper cancellation support in FXP `TransferDirectory`
  - Fix: Implement proper cancellation support in recursive `GetListing`


Try this.

[FluentFTP.32.3.4.zip](https://github.com/robinrodricks/FluentFTP/files/4516938/FluentFTP.32.3.4.zip)

**Comment by robinrodricks** [comment]
Please inform me if it works?

**Comment by robinrodricks** [comment]
Released in [32.4.0](https://www.nuget.org/packages/FluentFTP/32.4.0)

#### 32.4.0
  - New: `UploadDirectoryDeleteExcluded` property to control if excluded files are deleted during Upload (thanks [philippjenni](/philippjenni))
  - New: `DownloadDirectoryDeleteExcluded` property to control if excluded files are deleted during Download (thanks [philippjenni](/philippjenni))
  - Fix: Dispose AsyncWaitHandles to stop handle leak in .NET Framework 4.5 (thanks [sdiaman1](/sdiaman1))
  - Fix: Implement proper cancellation support in `UploadDirectory` (once file transfer begins it cannot be cancelled)
  - Fix: Implement proper cancellation support in `DownloadDirectory` (once file transfer begins it cannot be cancelled)
  - Fix: Implement proper cancellation support in FXP `TransferDirectory`
  - Fix: Implement proper cancellation support in recursive `GetListing`
  - Fix: Correctly resume when unexpectedEOF error received during uploading a file (thanks [mrcopperbeard](/mrcopperbeard))
  - Fix: Hide internal properties in `FtpClient` that are not meant to be exposed
  - Fix: Update `IFtpClient` with the latest set of public properties that are meant to be exposed

**Comment by 263613093** [comment]
yes,it works!
but,it often throw an exception as bellow:

at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__275_0(IAsyncResult iar)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpSocketStream.<EnableCancellation>d__64.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at FluentFTP.FtpSocketStream.<ConnectAsync>d__81.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpClient.<OpenPassiveDataStreamAsync>d__481.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at FluentFTP.FtpClient.<OpenDataStreamAsync>d__488.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpClient.<GetListingInternalAsync>d__207.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpClient.<GetListingAsync>d__206.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by robinrodricks** [comment]
How to fix this?

**Comment by robinrodricks** [comment]
And can you add another issue? its a new bug.
