### ISSUE TITLE
Is upload limited to a few MB/s or am I doing something wrong?

### ISSUE THREAD

**Issue by mortenmoulder** [robinrodricks/FluentFTP#593]
**FTP OS:** UNIX

**FTP Server:** ProFTPD

**Computer OS:** Windows 10

**FluentFTP Version:** 32.4.1

I am trying to upload files directly from the stream, so my server running the code isn't wasting lots and lots of resources, because it has to temporarily cache the files either on disk or in memory. For that I am using the low level OpenWriteAsync that returns a stream.

When I upload via WinSCP or Filezilla, the speed is ~30-40 MB/s whereas I am getting close to 10% of that with FluentFTP.

```
public async Task<FileManagerResponse> Upload(string path)
{
    var request = _httpContextAccessor.HttpContext.Request;

    var boundary = request.GetMultipartBoundary();
    var reader = new MultipartReader(boundary, request.Body);
    var section = await reader.ReadNextSectionAsync();

    var sw = new Stopwatch();
    sw.Start();

    using (var client = await _ftpHelper.GetFtpClient()) //this returns the FluentFTP client
    {
        while (section != null)
        {
            Console.WriteLine($"Found new section with type: {section.ContentType}");

            var fileSection = section.AsFileSection();

            if (fileSection != null)
            {
                var fileName = fileSection.FileName;

                var uploadPath = Path.Combine(path, fileName);

                Console.WriteLine($"Starting file upload: {fileName}");

                var stream = await client.OpenWriteAsync(uploadPath);
                await section.Body.CopyToAsync(stream);

                Console.WriteLine($"Upload done. It took {sw.ElapsedMilliseconds / 1000} seconds.");
            }

            section = await reader.ReadNextSectionAsync();
        }
    }

    sw.Stop();

    return new FileManagerResponse();
}
```

FTP client stuff:
```
public async Task<FtpClient> GetFtpClient(int chunkSize = 262144)
{
    var client = new FtpClient("SERVER")
    {
        Credentials = new NetworkCredential("USERNAME", "PASSWORD"),
        TransferChunkSize = chunkSize,
        UploadRateLimit = 0,
        DataConnectionType = FtpDataConnectionType.PASV
    };

    await client.ConnectAsync();

    return client;
}
```

**Logs :**

Console output:
```
Found new section with type: application/octet-stream
Starting file upload: 100MB.bin
Upload done. It took 27 seconds.
```

Commands log:
```
>         ConnectAsync()
Status:   Connecting to 123.123.123.123:21
Response: 220 ProFTPD Server HOSTNAME [123.123.123.123]
Status:   Detected FTP server: ProFTPD
Command:  USER USERNAME
Response: 331 Password required for USERNAME
Command:  PASS ***
Response: 230 User USERNAME logged in
Command:  FEAT
Response: 211-Features:
Response: AUTH TLS
Response: CCC
Response: CLNT
Response: EPRT
Response: EPSV
Response: HOST
Response: LANG en-US
Response: MDTM
Response: MFF modify;UNIX.group;UNIX.mode;
Response: MFMT
Response: MLST modify*;perm*;size*;type*;unique*;UNIX.group*;UNIX.groupname*;UNIX.mode*;UNIX.owner*;UNIX.ownername*;
Response: PBSZ
Response: PROT
Response: REST STREAM
Response: SIZE
Response: SSCN
Response: TVFS
Response: UTF8
Response: 211 End
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Response: 200 UTF8 set to on
Command:  SYST
Response: 215 UNIX Type: L8
Found new section with type: application/octet-stream
Starting file upload: 100MB.bin
>         OpenWriteAsync("/test/100MB.bin", Binary)
Command:  TYPE I
Response: 200 Type set to I
>         GetFileSizeAsync("/test/100MB.bin")
Command:  SIZE /test/100MB.bin
Response: 550 /test/100MB.bin: No such file or directory
>         OpenPassiveDataStreamAsync(PASV, "STOR /test/100MB.bin", 0)
Command:  PASV
Response: 227 Entering Passive Mode (123.123.123.123,25,219).
Status:   Connecting to 123.123.123.123:6619
Command:  STOR /test/100MB.bin
Response: 150 Opening BINARY mode data connection for /test/100MB.bin
Upload done. It took 33 seconds.
Found new section with type:
Found new section with type:
Found new section with type:
Found new section with type:
>         Dispose()
Status:   Disposing FtpClient object...
Status:   Testing connectivity using Socket.Poll()...
Command:  QUIT
Warning:  FtpClient.Disconnect(): Exception caught and discarded while closing control connection: System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond..
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at FluentFTP.FtpSocketStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at FluentFTP.FtpSocketStream.ReadLine(Encoding encoding)
   at FluentFTP.FtpClient.GetReply()
   at FluentFTP.FtpClient.Execute(String command)
   at FluentFTP.FtpClient.Disconnect()
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
```

Why I am getting that exception, I'm not sure. Calling GetReplyAsync (as recommended [here](https://github.com/robinrodricks/FluentFTP/wiki/File-Transfer) under OpenWrite) doesn't help it. It only hangs after uploading, for some reason.

I looked through the code for FluentFTP, but I haven't found anything that could explain why it's that slow.

**Comment by mortenmoulder** [comment]
I was doing something wrong. The `CopyToAsync` buffer size was default way too high. Set it to 8KB instead of 80KB and now it works.
