### ISSUE TITLE
OpenWrite opens too many connections, resulting in error. Do I need to close something?

### ISSUE THREAD

**Issue by mortenmoulder** [robinrodricks/FluentFTP#595]
**FTP OS:** Unix

**FTP Server:** ProFTPD

**Computer OS:** Windows 10

**FluentFTP Version:** 32.4.3

I am trying to unzip over FTP, without consuming any memory or disk. So far I've managed to do it the opposite way (download many files -> zip on the fly). The code is farely simple. I use the FtpClient to create a directory, but I use OpenWrite to copy the ZipArchive's stream to. CreateDirectory can be called as many times as I want, but OpenWrite fails pretty quickly.

```
public async Task Unzip(DownloadItem item)
{
    using (var client = await _ftpHelper.GetFtpClient()) //returns a FluentFTP FtpClient
    {
        var path = Path.Combine(item.Path, item.Name);

        var file = await client.OpenReadAsync(path);

        using (var archive = new ZipArchive(file, ZipArchiveMode.Read))
        {
            foreach (var entry in archive.Entries)
            {
                if (entry.FullName.EndsWith("/"))
                {
                    await CreateDirectoryFromZip(item, entry, client);
                }
                else
                {
                    await CreateFileFromZip(item, entry, client);
                }
            }
        }
    }
}

private async Task CreateDirectoryFromZip(DownloadItem item, ZipArchiveEntry directory, FtpClient client)
{
    var dirPath = Path.Combine(item.Path, directory.FullName);
    if (!dirPath.EndsWith("/"))
        dirPath = dirPath + "/";

    await client.CreateDirectoryAsync(dirPath);
}

private async Task CreateFileFromZip(DownloadItem item, ZipArchiveEntry entry, FtpClient client)
{
    var itemPath = Path.Combine(item.Path, entry.FullName);

    var stream = await client.OpenWriteAsync(itemPath);

    await entry.Open().CopyToAsync(stream);
}
```

```
public async Task<FtpClient> GetFtpClient(int chunkSize = 262144)
{
    var client = new FtpClient("server")
    {
        Credentials = new NetworkCredential("username", "password"),
        TransferChunkSize = chunkSize,
        UploadRateLimit = 0,
        DataConnectionType = FtpDataConnectionType.PASV,
        EnableThreadSafeDataConnections = true
    };

    await client.ConnectAsync();

    return client;
}
```

**Logs :**

```
>         ConnectAsync()
Status:   Connecting to 123.123.123.123:21
Response: 220 ProFTPD Server (ftp.hostname.com) [123.123.123.123]
Status:   Detected FTP server: ProFTPD
Command:  USER USERNAME
Response: 331 Password required for USERNAME
Command:  PASS ***
Response: 230 User USERNAME logged in
Command:  FEAT
Response: 211-Features:
Response: AUTH TLS
Response: CCC
Response: CLNT
Response: EPRT
Response: EPSV
Response: HOST
Response: LANG en-US
Response: MDTM
Response: MFF modify;UNIX.group;UNIX.mode;
Response: MFMT
Response: MLST modify*;perm*;size*;type*;unique*;UNIX.group*;UNIX.groupname*;UNIX.mode*;UNIX.owner*;UNIX.ownername*;
Response: PBSZ
Response: PROT
Response: REST STREAM
Response: SIZE
Response: SSCN
Response: TVFS
Response: UTF8
Response: 211 End
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Response: 200 UTF8 set to on
Command:  SYST
Response: 215 UNIX Type: L8
>         OpenReadAsync("/test/wordpress-5.4.2-da_DK.zip", Binary, 0)
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
>         CreateDirectoryAsync("/test/wordpress/", True)
>         DirectoryExistsAsync("/test")
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
Command:  CWD /test
Response: 250 CWD command successful
Command:  CWD /
Response: 250 CWD command successful
Status:   CreateDirectory /test/wordpress
Command:  MKD /test/wordpress
Response: 257 "/test/wordpress" - Directory successfully created
>         OpenWriteAsync("/test/wordpress/wp-login.php", Binary)
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
>         OpenWriteAsync("/test/wordpress/wp-cron.php", Binary)
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
>         OpenWriteAsync("/test/wordpress/xmlrpc.php", Binary)
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
>         OpenWriteAsync("/test/wordpress/wp-load.php", Binary)
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
>         CreateDirectoryAsync("/test/wordpress/wp-admin/", True)
>         DirectoryExistsAsync("/test/wordpress")
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
Command:  CWD /test/wordpress
Response: 250 CWD command successful
Command:  CWD /
Response: 250 CWD command successful
Status:   CreateDirectory /test/wordpress/wp-admin
Command:  MKD /test/wordpress/wp-admin
Response: 257 "/test/wordpress/wp-admin" - Directory successfully created
>         OpenWriteAsync("/test/wordpress/wp-admin/credits.php", Binary)
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
>         OpenWriteAsync("/test/wordpress/wp-admin/admin-functions.php", Binary)
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
>         OpenWriteAsync("/test/wordpress/wp-admin/options-reading.php", Binary)
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
>         OpenWriteAsync("/test/wordpress/wp-admin/edit-tags.php", Binary)
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
>         OpenWriteAsync("/test/wordpress/wp-admin/link-manager.php", Binary)
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
>         OpenWriteAsync("/test/wordpress/wp-admin/options-writing.php", Binary)
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
>         OpenWriteAsync("/test/wordpress/wp-admin/network.php", Binary)
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
>         CreateDirectoryAsync("/test/wordpress/wp-admin/includes/", True)
>         DirectoryExistsAsync("/test/wordpress/wp-admin")
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
Command:  CWD /test/wordpress/wp-admin
Response: 250 CWD command successful
Command:  CWD /
Response: 250 CWD command successful
Status:   CreateDirectory /test/wordpress/wp-admin/includes
Command:  MKD /test/wordpress/wp-admin/includes
Response: 257 "/test/wordpress/wp-admin/includes" - Directory successfully created
>         OpenWriteAsync("/test/wordpress/wp-admin/includes/privacy-tools.php", Binary)
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
>         OpenWriteAsync("/test/wordpress/wp-admin/includes/class-wp-links-list-table.php", Binary)
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
>         OpenWriteAsync("/test/wordpress/wp-admin/includes/class-wp-filesystem-ftpsockets.php", Binary)
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
>         OpenWriteAsync("/test/wordpress/wp-admin/includes/class-wp-debug-data.php", Binary)
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
>         OpenWriteAsync("/test/wordpress/wp-admin/includes/credits.php", Binary)
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
>         OpenWriteAsync("/test/wordpress/wp-admin/includes/class-plugin-upgrader.php", Binary)
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
>         OpenWriteAsync("/test/wordpress/wp-admin/includes/class-wp-site-icon.php", Binary)
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
>         OpenWriteAsync("/test/wordpress/wp-admin/includes/class-wp-themes-list-table.php", Binary)
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
>         OpenWriteAsync("/test/wordpress/wp-admin/includes/class-custom-background.php", Binary)
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
>         OpenWriteAsync("/test/wordpress/wp-admin/includes/class-wp-ajax-upgrader-skin.php", Binary)
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
>         OpenWriteAsync("/test/wordpress/wp-admin/includes/class-wp-list-table-compat.php", Binary)
>         Dispose()
Status:   Disposing FtpClient object...
Command:  QUIT
Response: 221 Goodbye.
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...

FluentFTP.FtpAuthenticationException: Sorry, the maximum number of clients (20) for this user are already connected.
   at FluentFTP.FtpClient.AuthenticateAsync(String userName, String password, CancellationToken token)
   at FluentFTP.FtpClient.AuthenticateAsync(CancellationToken token)
   at FluentFTP.FtpClient.ConnectAsync(CancellationToken token)
   at FluentFTP.FtpClient.OpenWriteAsync(String path, FtpDataType type, Boolean checkIfFileExists, CancellationToken token)
```

**Comment by yustonefish** [comment]
try sync operation, using OpenWrite.

**Comment by mortenmoulder** [comment]
I ended up setting `EnableThreadSafeDataConnections = false` in my FtpClient. Then it sends the GetListing command, waits for 2-3 seconds, and then starts writing the files using OpenWriteAsync. Works quite well, just a shame it takes a few seconds to return the output of GetListing (or whatever it's doing before writing the files).

**Comment by yustonefish** [comment]
GetListing for what?

**Comment by mortenmoulder** [comment]
Sorry, I'm confusing myself here. This is how it looks:

```
>         OpenReadAsync("/test/wordpress-5.4.2-da_DK.zip", Binary, 0)
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory

NOTHING HAPPENS HERE FOR A FEW SECONDS
THEN THE BELOW HAPPENS INSANELY FAST

>         CreateDirectoryAsync("/test/wordpress/", True)
>         DirectoryExistsAsync("/test")
>         GetWorkingDirectoryAsync()
Command:  PWD
Response: 257 "/" is the current directory
Command:  CWD /test
Response: 250 CWD command successful
Command:  CWD /
Response: 250 CWD command successful
Status:   CreateDirectory /test/wordpress
```

**Comment by robinrodricks** [comment]
You need to close the stream. You also need to call GetReply. Read the docs:

https://github.com/robinrodricks/FluentFTP/wiki/File-Transfer
