### ISSUE TITLE
Uncatchable NullReferenceException is occasionally thrown from FtpClient.ConnectAsync()

### ISSUE THREAD

**Issue by RedwoodForest** [robinrodricks/FluentFTP#617]
**FTP OS:** None (localhost with no FTP server set up).

**FTP Server:** None (localhost with no FTP server set up).

**Computer OS:** Windows 10

**FluentFTP Version:** 32.4.4

We are seeing occasional uncatchable NullReferenceExceptions being thrown from FtpClient.ConnectAsync() that crash our program. I've been able to create a minimal reproduction for this issue that should help locate the issue.

In our app we have also seen what looks like a similar issue in FtpClint.GetNameListingAsync() so this problem may not be limited to ConnectAsync().

I haven't analysed the code and stack trace too deeply but it looks like FtpClient.m_socket is being set to null and then the CancellationToken times out and calls m_socket.Close() resulting in the NRE, and since the NRE is happening on the CancellationToken's background thread it crashes the program.

This is a major issue for us since the exception can't be caught and always crashes our program when it occurs.

**Logs :**

Here are the logs from reproducing the issue using the attached code [FluentFTPNullReferenceException.zip](https://github.com/robinrodricks/FluentFTP/files/5211618/FluentFTPNullReferenceException.zip):

```
[...prior successful runs omitted...]
2020-09-11 14:37:19,237 [5] DEBUG FluentFTPNullReferenceException.Program - Run number: 81749
2020-09-11 14:37:19,237 [5] INFO  FluentFTP.FtpClient - Level: Info; Message: Status:   Connecting to 127.0.0.1:21
2020-09-11 14:37:19,237 [5] INFO  FluentFTP.FtpClient - Level: Verbose; Message: Status:   Disposing FtpSocketStream...
2020-09-11 14:37:19,237 [5] INFO  FluentFTP.FtpClient - Level: Verbose; Message: >         Dispose()
2020-09-11 14:37:19,238 [5] INFO  FluentFTP.FtpClient - Level: Verbose; Message: Status:   Disposing FtpClient object...
2020-09-11 14:37:19,238 [5] DEBUG FluentFTPNullReferenceException.Program - Run number: 81750
2020-09-11 14:37:19,238 [5] INFO  FluentFTP.FtpClient - Level: Info; Message: Status:   Connecting to 127.0.0.1:21
2020-09-11 14:37:19,238 [7] INFO  FluentFTP.FtpClient - Level: Verbose; Message: Status:   Disposing FtpSocketStream...
2020-09-11 14:37:19,239 [9] FATAL FluentFTPNullReferenceException.Program - CurrentDomain.UnhandledException: Uncatchable exception was thrown. IsTerminating: True.
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at FluentFTP.FtpSocketStream.<ConnectAsync>b__80_0()
   at System.Threading.CancellationToken.ActionToActionObjShunt(Object obj)
   at System.Threading.CancellationCallbackInfo.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationCallbackInfo.ExecuteCallback()
   at System.Threading.CancellationTokenSource.CancellationCallbackCoreWork(CancellationCallbackCoreWorkArguments args)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.TimerCallbackLogic(Object obj)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at FluentFTP.FtpSocketStream.<ConnectAsync>b__80_0()
   at System.Threading.CancellationToken.ActionToActionObjShunt(Object obj)
   at System.Threading.CancellationCallbackInfo.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationCallbackInfo.ExecuteCallback()
   at System.Threading.CancellationTokenSource.CancellationCallbackCoreWork(CancellationCallbackCoreWorkArguments args)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)<---

2020-09-11 14:37:19,239 [7] INFO  FluentFTP.FtpClient - Level: Verbose; Message: >         Dispose()
2020-09-11 14:37:19,263 [7] INFO  FluentFTP.FtpClient - Level: Verbose; Message: Status:   Disposing FtpClient object...
2020-09-11 14:37:19,263 [7] DEBUG FluentFTPNullReferenceException.Program - Run number: 81751
2020-09-11 14:37:19,264 [7] INFO  FluentFTP.FtpClient - Level: Info; Message: Status:   Connecting to 127.0.0.1:21
2020-09-11 14:37:19,264 [5] INFO  FluentFTP.FtpClient - Level: Verbose; Message: Status:   Disposing FtpSocketStream...
2020-09-11 14:37:19,265 [5] INFO  FluentFTP.FtpClient - Level: Verbose; Message: >         Dispose()
```

**Comment by robinrodricks** [comment]
Good find, I'll look into this.

**Comment by robinrodricks** [comment]
Can you try this build:

[FluentFTP_32.4.5_Beta.zip](https://github.com/robinrodricks/FluentFTP/files/5230300/FluentFTP_32.4.5_Beta.zip)

**Comment by RedwoodForest** [comment]
The beta seems to fix the issue for us.

Using the 32.4.5 beta I am no longer able to reproduce this issue. If I switch back to 32.4.4 I am able to reproduce this issue again.

**Comment by robinrodricks** [comment]
Awesome, Ill release it now then.

**Comment by robinrodricks** [comment]
Released in https://www.nuget.org/packages/FluentFTP/32.4.5
