### ISSUE TITLE
DowloadFileAsync only downloads the file partially

### ISSUE THREAD

**Issue by mabead** [robinrodricks/FluentFTP#618]
**FTP OS:** Unix / Windows / Embedded

**FTP Server:** VsFTPd

**Computer OS:** Windows

**FluentFTP Version:** 32.4.4

I have the following program:

```csharp
using (var client = new FtpClient("hostname"))
{
    client.RetryAttempts = 3;
    client.SocketKeepAlive = false;
    client.Credentials = new System.Net.NetworkCredential("myUsername", "myPassword");
    client.Port = 0;
    client.EncryptionMode = FtpEncryptionMode.Explicit;

    client.Connect();

    var localPath = @"c:/tmp/myLocalPath.txt";
    var remotePath = @"/some/remoteFile.txt";

    if (File.Exists(localPath))
    {
        File.Delete(localPath);
    }

    var remoteInfo = await client.GetObjectInfoAsync(remotePath);

    var result = await client.DownloadFileAsync(localPath, remotePath);
    result.Should().Be(FtpStatus.Success);

    var localInfo = new FileInfo(localPath);

    remoteInfo.Size.Should().Be(localInfo.Length);
}
```

This program fails with:
```
Expected remoteInfo.Size to be 950272L, but found 973737L
```

This means that the file was not fully downloaded. I also confirm that:

- if I download the file from Filezilla, I get a complete file (973737 bytes long)
- if I download using FluentFTP and compare with the file retrieved from Filezilla, the file retrieved from FluentFTP is partial. It is only 950272 bytes long).

Note that I ran this code about a dozen times and there was a single run where the file was fully downloaded.

This code was running fine with older versions of FluentFTP. I recently upgrade to 32.4.4 and I then started to see this issue.

**Logs :**

```
# Connect()
Status:   Connecting to ***:21
Response: 220 (vsFTPd 3.0.2)
Status:   Detected FTP server: VsFTPd
Command:  AUTH TLS
Response: 234 Proceed with negotiation.
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.251869.
Command:  USER ***
Response: 331 Please specify the password.
Command:  PASS ***
Response: 230 Login successful.
Command:  PBSZ 0
Response: 200 PBSZ set to 0.
Command:  PROT P
Response: 200 PROT now Private.
Command:  FEAT
Response: 211-Features:
Response: AUTH TLS
Response: EPRT
Response: EPSV
Response: MDTM
Response: PASV
Response: PBSZ
Response: PROT
Response: REST STREAM
Response: SIZE
Response: TVFS
Response: UTF8
Response: 211 End
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Response: 200 Always in UTF8 mode.
Command:  SYST
Response: 215 UNIX Type: L8

# GetObjectInfo("/some/remoteFile.txt", False)

# GetListingAsync("/some", Auto)
Command:  TYPE I
Response: 200 Switching to Binary mode.

# OpenPassiveDataStreamAsync(AutoPassive, "LIST /some", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||11775|).
Status:   Connecting to ***:11775
Command:  LIST /some
Response: 150 Here comes the directory listing.
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.1836309.
+---------------------------------------+
Listing:  -rw-rw-r--    1 ftp      ftp       4807825 Sep 11 15:23 otherRemoteFile.txt.zip
Listing:  -rwxr-xr-x    1 ftp      ftp        973737 Sep 11 15:20 remoteFile.txt
-----------------------------------------
Status:   Disposing FtpSocketStream...

# CloseDataStream()
Response: 226 Directory send OK.
Status:   Disposing FtpSocketStream...
Status:   Confirmed format Unix
Warning:  Failed to get object info for path /some/remoteFile.txt since MLST not supported and GetListing() fails to list file/folder.

# DownloadFileAsync("c:/tmp/myLocalPath.txt", "/some/remoteFile.txt", Append, None)

# OpenReadAsync("/some/remoteFile.txt", Binary, 0)
Command:  TYPE I
Response: 200 Switching to Binary mode.

# OpenPassiveDataStreamAsync(AutoPassive, "RETR /some/remoteFile.txt", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||11342|).
Status:   Connecting to ***:11342
Command:  RETR /some/remoteFile.txt
Response: 150 Opening BINARY mode data connection for /some/remoteFile.txt (973737 bytes).
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.1972702.
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
Status:   Testing connectivity using Socket.Poll()...
Status:   Disposing FtpSocketStream...

# Dispose()
Status:   Disposing FtpClient object...
Status:   Disposing FtpSocketStream...
Unhandled exception. FluentAssertions.Execution.AssertionFailedException: Expected remoteInfo.Size to be 950272L, but found 973737L.
   at FluentAssertions.Execution.FallbackTestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Numeric.NumericAssertions`1.Be(T expected, String because, Object[] becauseArgs)
   at ConsoleApp2.Program.Main(String[] args) in C:\Users\mbeaudry\source\repos\ConsoleApp2\Program.cs:line 44
   at ConsoleApp2.Program.<Main>(String[] args)```

**Comment by mabead** [comment]
I also tried to verify the download with a checksum but the result was still `Success`:

```csharp
var result = await client.DownloadFileAsync(localPath, remotePath, FtpLocalExists.Overwrite, FtpVerify.OnlyChecksum);
result.Should().Be(FtpStatus.Success);
```

**Comment by mabead** [comment]
I have revert to FluentFTP 19.2.2 and I see this:

* the program downloads the file as expected with 19.2.2
* the programs runs much faster (around 5 seconds with 19.2.2 and 35 seconds with 32.4.4)

I will revert back to 19.2.2.

**Comment by mabead** [comment]
And note that I was also able to have a few successful run with 32.4.4. When it worked, the program completed in around 5 seconds, just like with 19.2.2.

**Comment by mrcopperbeard** [comment]
Same things on version 32.4.3.  Reproducing on FTPS connection

**Comment by mrcopperbeard** [comment]
Spent a few hours to find out the problem. Results are:
* Problem reproducing with .NET Core 3.1. Same code works fine under net472
* [Here](https://github.com/robinrodricks/FluentFTP/blob/a03eab04d7f72328c1f0a2242c1b43d8aad7ccb8/FluentFTP/Client/FtpClient_FileDownload.cs#L981) we have `TimeoutException` which silently absorbing, I logged `fileLen` at this point, and it equals 0
* `filelen` calculates [here](https://github.com/robinrodricks/FluentFTP/blob/a03eab04d7f72328c1f0a2242c1b43d8aad7ccb8/FluentFTP/Client/FtpClient_FileDownload.cs#L879) only for `DownloadDataType = FtpDataType.Binary`

So I set my `IFtpClient.DownloadDataType` to  `FtpDataType.Binary`, and files download correctly for now. @mabead maybe you should try it too

**Comment by robinrodricks** [comment]
@mabead can you try setting SslBuffering to Off?

**Comment by mabead** [comment]
@robinrodricks I should be able to try it out in the next few weeks.

**Comment by mabead** [comment]
@robinrodricks I tried version 33.0.3 of FluentFtp with `SllBuffering = Off` and I confirm that it worked correctly. 

Here's what I did:
- I downloaded the complete content (333 files) of a FTP server locally with version 19.2.2.
- I downloaded the complete content of the same FTP server locally with version 33.0.3 with `SslBuffering = Off`.
- I compared the two set of files downloaded
- they were 100% equal

Also note that the download took 76 seconds with 33.0.3 and 158 seconds with 19.2.2 👍 

@mrcopperbeard, thanks for the suggested fix!

You can go ahead and close that issue.

**Comment by robinrodricks** [comment]
Thanks!
