### ISSUE TITLE
NullReferenceException from GetListingInternalAsync

### ISSUE THREAD

**Issue by jnyrup** [robinrodricks/FluentFTP#619]
**FTP OS:** 
Unix (based on vsFTPd being for unix-like systems)

**FTP Server:** 
vsFTPd 2.2.2 (based on STAT)
Url: ftp://tgftp.nws.noaa.gov

**Computer OS:** 
Windows Server 2019

**FluentFTP Version:** 
32.4.3

I'm occasionally getting `NullReferenceException`s from `GetListingInternalAsync`.
To put some numbers on it I've seen the exception 10 times in total for the past 30 days on two separate VMs, that each calls `GetListingAsync` approximately once every 5 minute.

My code looks like

```cs
private async Task<FtpListItem[]> GetListOfFiles(string ftpFolder, CancellationToken token)
{
    using (var client = GetClient())
    {
        await client.ConnectAsync(token).ConfigureAwait(false);

        var files = await client.GetListingAsync(ftpFolder, token).ConfigureAwait(false);
        await client.DisconnectAsync(token).ConfigureAwait(false);
        return files;
    }
}

private IFtpClient GetClient()
{
    return new FtpClient(ftpAddress)
    {
        RetryAttempts = 3
    };
}
```

**Logs :**

Stacktrace
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at FluentFTP.FtpClient.<GetListingInternalAsync>d__207.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpClient.<GetListingAsync>d__206.MoveNext()
```

I'll add extra logging to my code and add them here once the exception happens again.

```
20-09-20 05:07:34.674 - >         ConnectAsync()
20-09-20 05:07:47.981 - Status:   Connecting to 140.90.101.79:21
20-09-20 05:07:48.772 - Response: 220
20-09-20 05:07:48.772 - Command:  USER anonymous
20-09-20 05:07:48.776 - Response: 331 Please specify the password.
20-09-20 05:07:48.776 - Command:  PASS ***
20-09-20 05:07:48.783 - Response: 230 Login successful.
20-09-20 05:07:48.783 - Command:  FEAT
20-09-20 05:07:48.787 - Response: 211-Features:
Response: EPSV
Response: MDTM
Response: PASV
Response: REST STREAM
Response: SIZE
Response: TVFS
Response: UTF8
20-09-20 05:07:48.787 - Response: 211 End
20-09-20 05:07:48.788 - Status:   Text encoding: System.Text.UTF8Encoding
20-09-20 05:07:48.788 - Command:  OPTS UTF8 ON
20-09-20 05:07:48.791 - Response: 200 Always in UTF8 mode.
20-09-20 05:07:48.791 - Command:  SYST
20-09-20 05:07:48.794 - Response: 215 UNIX Type: L8
20-09-20 05:07:48.794 - >         GetListingAsync("SL.us008001/DC.avspt/DS.gtggb/PT.grid_DF.gr2", Auto)
20-09-20 05:07:48.794 - >         GetWorkingDirectoryAsync()
20-09-20 05:07:48.794 - Command:  PWD
20-09-20 05:07:48.798 - Response: 257 "/"
20-09-20 05:07:48.798 - Command:  TYPE I
20-09-20 05:07:48.801 - Response: 200 Switching to Binary mode.
20-09-20 05:07:48.801 - >         OpenPassiveDataStreamAsync(AutoPassive, "LIST /SL.us008001/DC.avspt/DS.gtggb/PT.grid_DF.gr2", 0)
20-09-20 05:07:48.801 - Command:  EPSV
20-09-20 05:08:06.140 - Status:   Disposing FtpSocketStream...
20-09-20 05:08:06.157 - >         Dispose()
20-09-20 05:08:06.157 - Status:   Disposing FtpClient object...
20-09-20 05:08:06.157 - Status:   Disposing FtpSocketStream...
20-09-20 05:08:06.450 
System.NullReferenceException: Object reference not set to an instance of an object.
   at FluentFTP.FtpClient.<GetListingInternalAsync>d__207.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpClient.<GetListingAsync>d__206.MoveNext()
```

**Comment by robinrodricks** [comment]
Can you try this build:

[FluentFTP_32.4.5_Beta.zip](https://github.com/robinrodricks/FluentFTP/files/5230300/FluentFTP_32.4.5_Beta.zip)

**Comment by jnyrup** [comment]
Thanks, I'll try out the new build.
I've updated the issue description with more detailed logs.

Looking at the logs, the cause _looks_ to be identical to #617

Reconstruction of stack trace from logs
```cs
ConnectAsync
GetListingAsync
    GetAbsolutePathAsync
        GetWorkingDirectoryAsync
GetListingInternalAsync
    SetDataTypeNoLockAsync
    OpenDataStreamAsync
        OpenPassiveDataStreamAsync
            ExecuteAsync
                FtpClient.IsConnected
                    FtpSocketStream.IsConnected
                        Stream.Close() // https://referencesource.microsoft.com/#mscorlib/system/io/stream.cs,dc4ffe046b847b84
                            FtpSocketStream.Dispose(true)
                                m_socket = null // nulled
                ConnectAsync(token)
                    ConnectAsync(m_stream, token)
                        stream.ConnectAsync(Host, Port, InternetProtocolVersions, token)
                            m_socket.Close() // invoked
```

**Comment by jnyrup** [comment]
Got the `NullReferenceException` again after upgrading to 32.4.5.

```cs
System.NullReferenceException: Object reference not set to an instance of an object.
   at FluentFTP.FtpClient.<GetListingInternalAsync>d__207.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentFTP.FtpClient.<GetListingAsync>d__206.MoveNext()
```

**Comment by jnyrup** [comment]
After upgrading to one of the later versions, I haven't seen the exception for a longer time.
