### ISSUE TITLE
Disconnect method throws: Cannot access a disposed object ('System.Net.Sockets.NetworkStream') exception

### ISSUE THREAD

**Issue by elkondzik** [robinrodricks/FluentFTP#670]
**FTP OS:** zOS
**FTP Server:** IBM OS400 / Mvs / zOS
**Computer OS:** Windows
**FluentFTP Version:** 33.0.2.0

When ftp client disconnects, it always throws the exception as below.
Files are transferred/uploaded sucessfully, nevertheless disconnects method doesn't end nicely ;)
Here are the logs from upload but it happens also for download. 
It ialso does not matter if operation is async or not.

**Logs :**

```

UploadFile("XXX.jcl", "'XXX(YYY)'", Overwrite, False, None)

FileExists("'XXX(YYY)'")

# Connect() *
Status:   Connecting to XXX 
Response: 220-FTPD1 IBM FTP CS V2R4 at XXX, 10:54:44 on 2021-01-25.
Response: 220 Connection will close if idle for more than 5 minutes.
Status:   Detected FTP server: IBMzOSFTP
Command:  USER XXX
Response: 331 Send password please.
Command:  PASS XXX
Response: 230 XXX is logged on.  Working directory is "XXX.".
Command:  FEAT
Response: 211 no Extensions supported
Status:   Text encoding: System.Text.ASCIIEncoding
Command:  SYST
Response: 215 MVS is the operating system of this server. FTP Server is running on z/OS.

# GetNameListing(".")
Command:  TYPE I
Response: 200 Representation type is Image

# OpenPassiveDataStream(AutoPassive, "NLST .", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||26294|)
Status:   Connecting to XXX
Command:  NLST .
Response: 550 No data sets found.
Status:   Disposing FtpSocketStream...

# CloseDataStream()

# OpenWrite("'XXX(YYY)'", ASCII)
Command:  TYPE A
Response: 200 Representation type is Ascii NonPrint

# OpenPassiveDataStream(AutoPassive, "STOR 'XXX(YYY)'", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||26295|)
Status:   Connecting to XXXX
Command:  STOR 'XXX(YYY)'
Response: 125 Storing data set XXX(YYY)
Status:   Disposing FtpSocketStream...
Response: 250-Statistics have been updated for the PDS member that was transferred
Response: 250 Transfer completed successfully.

# Dispose()
Status:   Disposing FtpClient object...
Command:  QUIT
Warning:  FtpClient.Disconnect(): Exception caught and discarded while closing control connection: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at FluentFTP.FtpSocketStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at FluentFTP.FtpSocketStream.WriteLine(Encoding encoding, String buf)
   at FluentFTP.FtpClient.Execute(String command)
   at FluentFTP.FtpClient.Disconnect()
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...

```

**Comment by robinrodricks** [comment]
Due to the dozens of FTP servers, disconnect method never ends cleanly. Thus I ended up in frustration just absorbing all exceptions during dispose. If you have some ideas, perhaps you can improve the handling and contribute a PR, if not, I'm not sure how to fix this with your server.

**Comment by elkondzik** [comment]
Hi!
Thanks for the reply. I'd like to contrubute - of course only for this particular server.
I'll analyze the code and try to propose something
