### ISSUE TITLE
Client Disconnecting while connecting over implicit FTP with TLS 1.2

### ISSUE THREAD

**Issue by joeyabouharb** [robinrodricks/FluentFTP#678]
**FTP OS:** Windows

**FTP Server:** Unkwown (Moveit DMZ most likely)

**Computer OS:** ? Windows Server 2012 standard (VM)

**FluentFTP Version:** ? FluentFTP.32.4.3 and tested with 33.0.3.0

This Most Likely is an issue with windows server 2012 since it works fine while testing in windows 10. TLS support was checked and enabled in this machine, returning the same error messages.

``` 
var client = new FtpClient
            {
                Credentials = new NetworkCredential(userName, ""),
                Host = ftpHost,
                Port = ftpPort,
                EncryptionMode = FtpEncryptionMode.Implicit,
                DataConnectionType = FtpDataConnectionType.PASV,
                DataConnectionEncryption = true,
                SslProtocols = (SslProtocols)3072
            };
            
            client.OnLogEvent = OnFTPLogEvent;
            // Password isn't required it's covered by TLS client certificates
            client.ClientCertificates.Add(certificate);
///
client.connect();
```

**Logs :**
```
2021-02-12 09:26:51-985 || >         Connect() | 
2021-02-12 09:26:52-001 |  | Status:   Connecting to *:991 | 
2021-02-12 09:26:52-063 |  | D14169C7614960747F4AB1F5F832FD526EF6F861 | 
2021-02-12 09:26:52-063 |  | None | 
2021-02-12 09:26:52-063 |  | Status:   FTPS Authentication Successful | 
2021-02-12 09:26:52-063 | | Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.0468011. | 
2021-02-12 09:26:52-063 |  | >         Dispose() | 
2021-02-12 09:26:52-063 |  | Status:   Disposing FtpClient object... | 
2021-02-12 09:26:52-063 |  | Command:  QUIT | 
2021-02-12 09:26:52-063 |  | Status:   Disposing FtpSocketStream... | 
2021-02-12 09:26:52-079 | | Status:   Disposing FtpSocketStream... | 
2021-02-12 09:26:52-079 | Error | Unable to connect to FTPS server.
  Exception Message: The connection was terminated before a greeting could be read.,
  StackTrace:    at FluentFTP.FtpClient.Handshake()
   at FluentFTP.FtpClient.Connect()
```

**Comment by joeyabouharb** [comment]
These are the logs upon success on a win 10 machine
```
2021-02-12 09:24:20-255 |  | >         Connect() | 
2021-02-12 09:24:23-273 |  | Status:   *:991 | 
2021-02-12 09:24:41-353 |  | D14169C7614960747F4AB1F5F832FD526EF6F861 | 
2021-02-12 09:24:41-359 |  | None | 
2021-02-12 09:24:44-465 |  | Status:   FTPS Authentication Successful | 
2021-02-12 09:24:46-704 |  | Status:   Time to activate encryption: 0h 0m 15s.  Total Seconds: 15.1410788. | 
2021-02-12 09:24:48-870 |  | Status:   Testing connectivity using Socket.Poll()... | 
2021-02-12 09:24:52-650 | | Response: 220-This is the DIU Organisation of MOVEit DMZ
...
Response: 220-reserves the right to monitor and/or limit access to this resource at | 
2021-02-12 09:24:54-123 | Error | Response: 220 any time. | 
....
Response: 230-for important messages. | 
...
2021-02-12 09:24:55-636 | | Command:  PBSZ 0 | 
2021-02-12 09:24:55-636 | | Response: 200 PBSZ command successful | 
2021-02-12 09:24:55-651 |  | Command:  PROT P | 
2021-02-12 09:24:55-651 | | Response: 200 PROT command successful | 
2021-02-12 09:24:55-651 |  | Command:  FEAT | 
2021-02-12 09:24:55-715 |  | Response: 211-Extensions supported:
Response: AUTH SSL
Response: AUTH TLS-P
Response: AUTH TLS
Response: AUTH TLS-C
Response: PROT
Response: PBSZ
Response: SIZE
Response: REST STREAM
Response: MODE Z
Response: XSHA1
Response: INTEGRITY
Response: HASH
Response: CLNT
Response: UTF8 | 
2021-02-12 09:24:55-715 | | Response: 211 End of list | 
2021-02-12 09:24:55-730 |  | Status:   Text encoding: System.Text.UTF8Encoding | 
2021-02-12 09:24:55-730 |  | Command:  OPTS UTF8 ON | 
2021-02-12 09:24:55-730 | | Response: 200 OPTS command successful | 
2021-02-12 09:24:55-746 |  | Command:  SYST | 
2021-02-12 09:24:55-746 |  | Response: 215 Windows_NT version 5.0 (MOVEit DMZ FTP 11.0.0.0) | 
2021-02-12 09:24:55-763 |  | >         GetWorkingDirectory() | 
2021-02-12 09:24:55-763 |  | Command:  PWD | 
...
2021-02-12 09:24:56-917 | | Response: 221 Goodbye | 
2021-02-12 09:24:56-917 | | Status:   Disposing FtpSocketStream... | 
2021-02-12 09:24:59-319 |  | >         Dispose() | 
2021-02-12 09:24:59-323 |  | Status:   Disposing FtpClient object... | 
2021-02-12 09:24:59-323 |  | Status:   Disposing FtpSocketStream... | 
```

**Comment by joeyabouharb** [comment]
Can Anyone Help with this?

**Comment by robinrodricks** [comment]
I'm not sure how to help you. Closing since its impossible to debug remote private servers.

I would recommend you try with `AutoConnect` and see if it is able to find a working connection profile. Wiki covers usage of it.
