### ISSUE TITLE
from 35.0.0 AutoConnect/AutoConnectAsync work wrong

### ISSUE THREAD

**Issue by borgez** [robinrodricks/FluentFTP#756]
new version
https://github.com/robinrodricks/FluentFTP/blob/a3663d990ba8c1a2008e3beb91eb54f2fcb88dbc/FluentFTP/Client/FtpClient_AutoConnection.cs#L32

old version

https://github.com/robinrodricks/FluentFTP/commit/40a8e9e0d4a6970b4dba3a58fa88b9e153548b97#diff-eb7b54a7f327aecddd33b46e8e85ee2ac8232c020456e763cf97eff3dcc10a90L32

if we do, it work:
```
await client.AutoConnectAsync();
client.EncryptionMode = FtpEncryptionMode.None;
```

if not:
```
>         AutoConnectAsync()
>         AutoDetectAsync(True, False)
>         ConnectAsync()
Status:   Connecting to 95.167.245.94:21
Response: 220 (vsFTPd 3.0.2)
Status:   Detected FTP server: VsFTPd
Command:  AUTH TLS
Response: 530 Please login with USER and PASS.
Command:  USER fz223free
Response: 331 Please specify the password.
Command:  PASS ***
Response: 230 Login successful.
Command:  FEAT
Response: 211-Features:
Response: EPRT
Response: EPSV
Response: MDTM
Response: PASV
Response: REST STREAM
Response: SIZE
Response: TVFS
Response: UTF8
Response: 211 End
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Response: 200 Always in UTF8 mode.
Command:  SYST
Response: 215 UNIX Type: L8
Default
True
>         DownloadAsync("/out/published/Belgorodskaya_obl/purchaseNotice/purchaseNotice_Belgorodskaya_obl_20210801_000000_20210831_235959_011.xml.zip")
>         OpenReadAsync("/out/published/Belgorodskaya_obl/purchaseNotice/purchaseNotice_Belgorodskaya_obl_20210801_000000_20210831_235959_011.xml.zip", Binary, 0)
Command:  TYPE I
Response: 200 Switching to Binary mode.
>         OpenPassiveDataStreamAsync(AutoPassive, "RETR /out/published/Belgorodskaya_obl/purchaseNotice/purchaseNotice_Belgorodskaya_obl_20210801_000000_20210831_235959_011.xml.zip", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||33950|)
Status:   Connecting to 95.167.245.94:33950
Command:  RETR /out/published/Belgorodskaya_obl/purchaseNotice/purchaseNotice_Belgorodskaya_obl_20210801_000000_20210831_235959_011.xml.zip
Response: 150 Opening BINARY mode data connection for /out/published/Belgorodskaya_obl/purchaseNotice/purchaseNotice_Belgorodskaya_obl_20210801_000000_20210831_235959_011.xml.zip (39295 bytes).
Status:   Disposing FtpSocketStream...
Error:    FTPS Authentication Failed
```

```
The token supplied to the function is invalid
---
  at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at FluentFTP.FtpSocketStream.ActivateEncryptionAsync(String targethost, X509CertificateCollection clientCerts, SslProtocols sslProtocols)
   at FluentFTP.FtpClient.OpenPassiveDataStreamAsync(FtpDataConnectionType type, String command, Int64 restart, CancellationToken token)
   at FluentFTP.FtpClient.OpenDataStreamAsync(String command, Int64 restart, CancellationToken token)
   at FluentFTP.FtpClient.OpenReadAsync(String path, FtpDataType type, Int64 restart, Boolean checkIfFileExists, CancellationToken token)
   at FluentFTP.FtpClient.DownloadFileInternalAsync(String localPath, String remotePath, Stream outStream, Int64 restartPosition, IProgress`1 progress, CancellationToken token, FtpProgress metaProgress, Int64 knownFileSize, Boolean isAppend)
---
at FluentFTP.FtpClient.DownloadFileInternalAsync(String localPath, String remotePath, Stream outStream, Int64 restartPosition, IProgress`1 progress, CancellationToken token, FtpProgress metaProgress, Int64 knownFileSize, Boolean isAppend)
   at FluentFTP.FtpClient.DownloadAsync(String remotePath, Int64 restartPosition, IProgress`1 progress, CancellationToken token)
   at FluentFTP.FtpClient.DownloadAsync(String remotePath, CancellationToken token)
   at UserQuery.Main(), line 39
```

**Comment by robinrodricks** [comment]
Thanks, I'll check it out.

**Comment by robinrodricks** [comment]
Please check if this works:

[FluentFTP.35.0.3.zip](https://github.com/robinrodricks/FluentFTP/files/7109366/FluentFTP.35.0.3.zip)

**Comment by robinrodricks** [comment]
Released.

https://www.nuget.org/packages/FluentFTP/35.0.3

**Comment by borgez** [comment]
> Please check if this works:
> 
> [FluentFTP.35.0.3.zip](https://github.com/robinrodricks/FluentFTP/files/7109366/FluentFTP.35.0.3.zip)

no it not works =(

var client = new FtpClient
{
	Host = "95.167.245.94",
	Credentials = new NetworkCredential("fz223free", "fz223free"),
	RetryAttempts = 10,
};
client.OnLogEvent += (level, s) => Console.WriteLine($"{level}: {s}");

client.AutoConnect();
// linqpad
//client.Dump(1);
//client.EncryptionMode = FtpEncryptionMode.None;

await client.DownloadAsync("/out/published/Belgorodskaya_obl/purchaseNotice/purchaseNotice_Belgorodskaya_obl_20210801_000000_20210831_235959_011.xml.zip", CancellationToken.None);

**Comment by robinrodricks** [comment]
Are you getting the same error?

**Comment by robinrodricks** [comment]
Can you first run `AutoDetect[0].ToCode()` and tell me what you get?

**Comment by borgez** [comment]
```
// add this above your namespace declaration
using FluentFTP;
using System.Text;
using System.Net;
using System.Security.Authentication;

// add this to create and configure the FTP client
var client = new FtpClient();
client.LoadProfile(new FtpProfile {
  Host = "95.167.245.94",
  Credentials = new NetworkCredential("fz223free", "fz223free"),
  Encryption = FtpEncryptionMode.None,
  Protocols = SslProtocols.Tls11, Tls12,
  DataConnection = FtpDataConnectionType.PASV,
  Encoding = System.Text.UTF8Encoding,
});
client.Connect();
```

**Comment by robinrodricks** [comment]
It looks good to me. If these settings are wrong, then what settings work for you?

**Comment by borgez** [comment]
this looks like different behavior with Connect and AutoConnect

```
Verbose: >         Connect()
Info: Status:   Connecting to 95.167.245.94:21
Info: Response: 220 (vsFTPd 3.0.2)
Info: Status:   Detected FTP server: VsFTPd
Info: Command:  USER fz223free
Info: Response: 331 Please specify the password.
Info: Command:  PASS ***
Info: Response: 230 Login successful.
Info: Command:  FEAT
Verbose: Response: 211-Features:
Response: EPRT
Response: EPSV
Response: MDTM
Response: PASV
Response: REST STREAM
Response: SIZE
Response: TVFS
Response: UTF8
Info: Response: 211 End
Info: Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Info: Command:  OPTS UTF8 ON
Info: Response: 200 Always in UTF8 mode.
Info: Command:  SYST
Info: Response: 215 UNIX Type: L8
Verbose: >         DownloadAsync("/out/published/Belgorodskaya_obl/purchaseNotice/purchaseNotice_Belgorodskaya_obl_20210801_000000_20210831_235959_011.xml.zip")
Verbose: >         OpenReadAsync("/out/published/Belgorodskaya_obl/purchaseNotice/purchaseNotice_Belgorodskaya_obl_20210801_000000_20210831_235959_011.xml.zip", Binary, 0)
Info: Command:  TYPE I
Info: Response: 200 Switching to Binary mode.
Verbose: >         OpenPassiveDataStreamAsync(PASV, "RETR /out/published/Belgorodskaya_obl/purchaseNotice/purchaseNotice_Belgorodskaya_obl_20210801_000000_20210831_235959_011.xml.zip", 0)
Info: Command:  PASV
Info: Response: 227 Entering Passive Mode (95,167,245,94,129,168)
Info: Status:   Connecting to 95.167.245.94:33192
Info: Command:  RETR /out/published/Belgorodskaya_obl/purchaseNotice/purchaseNotice_Belgorodskaya_obl_20210801_000000_20210831_235959_011.xml.zip
Info: Response: 150 Opening BINARY mode data connection for /out/published/Belgorodskaya_obl/purchaseNotice/purchaseNotice_Belgorodskaya_obl_20210801_000000_20210831_235959_011.xml.zip (39295 bytes).
Verbose: Status:   Disposing FtpSocketStream...
Info: Response: 226 Transfer complete.
39295
Verbose: >         Dispose()
Verbose: Status:   Disposing FtpClient object...
Verbose: Status:   Disposing FtpSocketStream...
Verbose: Status:   Disposing FtpSocketStream...
```

```
Verbose: >         AutoConnect()
Verbose: >         AutoDetect(True, False)
Verbose: >         Connect()
Info: Status:   Connecting to 95.167.245.94:21
Info: Response: 220 (vsFTPd 3.0.2)
Info: Status:   Detected FTP server: VsFTPd
Info: Command:  AUTH TLS
Info: Response: 530 Please login with USER and PASS.
Info: Command:  USER fz223free
Info: Response: 331 Please specify the password.
Info: Command:  PASS ***
Info: Response: 230 Login successful.
Info: Command:  FEAT
Verbose: Response: 211-Features:
Response: EPRT
Response: EPSV
Response: MDTM
Response: PASV
Response: REST STREAM
Response: SIZE
Response: TVFS
Response: UTF8
Info: Response: 211 End
Info: Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Info: Command:  OPTS UTF8 ON
Info: Response: 200 Always in UTF8 mode.
Info: Command:  SYST
Info: Response: 215 UNIX Type: L8
Verbose: >         DownloadAsync("/out/published/Belgorodskaya_obl/purchaseNotice/purchaseNotice_Belgorodskaya_obl_20210801_000000_20210831_235959_011.xml.zip")
Verbose: >         OpenReadAsync("/out/published/Belgorodskaya_obl/purchaseNotice/purchaseNotice_Belgorodskaya_obl_20210801_000000_20210831_235959_011.xml.zip", Binary, 0)
Info: Command:  TYPE I
Info: Response: 200 Switching to Binary mode.
Verbose: >         OpenPassiveDataStreamAsync(AutoPassive, "RETR /out/published/Belgorodskaya_obl/purchaseNotice/purchaseNotice_Belgorodskaya_obl_20210801_000000_20210831_235959_011.xml.zip", 0)
Info: Command:  EPSV
Info: Response: 229 Entering Extended Passive Mode (|||30667|)
Info: Status:   Connecting to 95.167.245.94:30667
Info: Command:  RETR /out/published/Belgorodskaya_obl/purchaseNotice/purchaseNotice_Belgorodskaya_obl_20210801_000000_20210831_235959_011.xml.zip
Info: Response: 150 Opening BINARY mode data connection for /out/published/Belgorodskaya_obl/purchaseNotice/purchaseNotice_Belgorodskaya_obl_20210801_000000_20210831_235959_011.xml.zip (39295 bytes).
Verbose: Status:   Disposing FtpSocketStream...
Error: Error:    FTPS Authentication Failed
```

![image](https://user-images.githubusercontent.com/2155999/132098642-118077f6-58bb-4c9d-a2ae-61adaf647d08.png)

![image](https://user-images.githubusercontent.com/2155999/132098676-bb60d46c-edad-4ba5-917b-4995aa922ef2.png)

**Comment by robinrodricks** [comment]
Thanks for this great info. I think I have solved it, please check:

[FluentFTP.35.0.5.zip](https://github.com/robinrodricks/FluentFTP/files/7110137/FluentFTP.35.0.5.zip)

**Comment by borgez** [comment]
> Thanks for this great info. I think I have solved it, please check:
> 
> [FluentFTP.35.0.5.zip](https://github.com/robinrodricks/FluentFTP/files/7110137/FluentFTP.35.0.5.zip)

Yep, now it works, great thanks...

**Comment by robinrodricks** [comment]
Perfect. Will release.

**Comment by robinrodricks** [comment]
Released.
https://www.nuget.org/packages/FluentFTP/35.0.4
