### ISSUE TITLE
Exception when using FluentFTP inside Docker Container

### ISSUE THREAD

**Issue by Akjo4712** [robinrodricks/FluentFTP#783]
**FTP OS:** Unix

**FTP Server:** Pure-FTPd

**Computer OS:** Unix Container

**FluentFTP Version:** 35.0.5

**Description:**
I have a Application written in NET Core 3.1, when I execute the Application on my Windows Machine, Files can be uploaded as expected. When I build a Docker Container from exectly the same Source Code, I am unable to upload Files correctly.

The first File seems to be uploaded when I read through the logs, but in fact it is just a 0 Byte File on the FTP Server. The second upload fails with an Exception.

As I am starting both the plain Windows Version and the Docker Version on my Windows Machine, the FTP Server in general is reachable and answering Requests from my Machine. Either there is a Bug in FlutenFTP when executed in a Docker Container, or I am having Issues with Passive FTP from my Docker Container.

Already spent various hours debugging this Problem, I am unable to find the Issue, any help on this Topic is highly appreciated.

**Dockerfile:**
```
FROM mcr.microsoft.com/dotnet/aspnet:3.1
COPY bin/Release/netcoreapp3.1/publish/ app/
WORKDIR /app
EXPOSE 80
ENTRYPOINT ["dotnet", "xxx-xxxxx.dll"]
```

**Code:**
```
public static void RunExport()
{
	FtpClient ftpClient = new FtpClient("xxx.xxx.xxx",xx,"xxx","xxx");
	ftpClient.AutoConnect();

	foreach (String Path in Directory.GetFiles(Path.GetDirectoryName(Path.Join(AppDomain.CurrentDomain.BaseDirectory,"Queries/"))).OrderBy(x => x))
	{
	  ParseAndExecuteSQL(Path, ftpClient);
	}
	ftpClient.Disconnect();
}

public static void ParseAndExecuteSQL(String SQLPath, FtpClient ftpClient)
{
	//Some other Code here

	DataTable CSVData = Generic.ExecuteSelectQuery(SQLQuery);
	byte[] FTPFile = Generic.GetCSV(CSVData);
	Console.WriteLine("Database Export | Path:" + FTPPath + " Rows:" + CSVData.Rows.Count + " Size:" + (FTPFile.Length/1024).ToString() + "kb");
	ftpClient.Upload(FTPFile,FTPPath);
	
	//Some other Code here
}

```

**Exception:**
```
FluentFTP.FtpException
Error while uploading the file to the server. See InnerException for more info.

FluentFTP.FtpException: Error while uploading the file to the server. See InnerException for more info.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at FluentFTP.FtpClient.CheckFileExistsBySize(FtpSizeReply sizeReply)
   at FluentFTP.FtpClient.FileExists(String path)
   at FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String localPath, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExistsKnown, Action`1 progress, FtpProgress metaProgress)
   --- End of inner exception stack trace ---
   at FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String localPath, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExistsKnown, Action`1 progress, FtpProgress metaProgress)
   at FluentFTP.FtpClient.Upload(Byte[] fileData, String remotePath, FtpRemoteExists existsMode, Boolean createRemoteDir, Action`1 progress)
```

**Logs:**
```

# AutoConnect()

# AutoDetect(True, False)

# Connect()

# AutoConnect()

# AutoDetect(True, False)

# Connect()
Status:   Connecting to ***:21
Response: 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
Response: 220-You are user number 2 of 100 allowed.
Response: 220-Local time is now 16:12. Server port: 21.
Response: 220-This is a private system - No anonymous login
Response: 220-IPv6 connections are also welcome on this server.
Response: 220 You will be disconnected after 15 minutes of inactivity.
Status:   Detected FTP server: PureFTPd
Command:  AUTH TLS
Response: 234 AUTH TLS OK.
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.2250653.
Command:  USER ***
Response: 331 User *** OK. Password required
Command:  PASS ***
Response: 230 OK. Current directory is /
Command:  PBSZ 0
Response: 200 PBSZ=0
Command:  PROT P
Response: 200 Data protection level set to "private"
Command:  FEAT
Response: 211-Extensions supported:
Response: EPRT
Response: IDLE
Response: MDTM
Response: SIZE
Response: MFMT
Response: REST STREAM
Response: MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;
Response: MLSD
Response: AUTH TLS
Response: PBSZ
Response: PROT
Response: UTF8
Response: TVFS
Response: ESTA
Response: PASV
Response: EPSV
Response: SPSV
Response: 211 End.
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Response: 200 OK, UTF-8 enabled
Command:  SYST
Response: 215 UNIX Type: L8

# Upload("/system/export/DailyPeak.csv", Overwrite, False)

# FileExists("/system/export/DailyPeak.csv")
Command:  SIZE /system/export/DailyPeak.csv
Response: 213 0

# DeleteFile("/system/export/DailyPeak.csv")
Command:  DELE /system/export/DailyPeak.csv
Response: 250 Deleted /system/export/DailyPeak.csv

# OpenWrite("/system/export/DailyPeak.csv", Binary)
Command:  TYPE I
Response: 200 TYPE is now 8-bit binary

# OpenPassiveDataStream(PASV, "STOR /system/export/DailyPeak.csv", 0)
Command:  PASV
Response: 227 Entering Passive Mode (138,68,96,224,117,201)
Status:   Connecting to ***:30153
Command:  STOR /system/export/DailyPeak.csv
Response: 150 Accepted data connection
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.0786551.
Status:   Disposing FtpSocketStream...

# Upload("/customer/export/DailyPeak.csv", Overwrite, False)

# FileExists("/customer/export/DailyPeak.csv")
Command:  SIZE /customer/export/DailyPeak.csv
```

**Comment by robinrodricks** [comment]
Just set the remoteExists mode to NoCheck or something and see if it works. If it works, its probably a bug inside FileExists. Best way to debug this is to download the source and add it to your project, so you can hit breakpoints and debug cleanly.

**Comment by Akjo4712** [comment]
We moved our application to Docker we can now interact directly with the Files on Disc, we have already removed FluentFTP from that application, uploading Files via FTP is currently not necessary anymore, 

We currently won't spend Time and Ressources debugging this Issue. If you need more details regarding our Environment or anything else, feel free and reach out to me. You might also close this Issue if you won't further investigagte.

Kind regards and thanks for your work on this Project!

**Comment by robinrodricks** [comment]
Thanks!
