### ISSUE TITLE
File uploading using a stream fails when length is unavailable

### ISSUE THREAD

**Issue by cjzzz** [robinrodricks/FluentFTP#798]
**FTP OS:** Windows

**FTP Server:** IIS

**Computer OS:** Windows

**FluentFTP Version:** 35.2.1

I'm passing a stream to `UploadAsync` which is of an unknown length and has `CanSeek` set to false. `UploadFileInternalAsync` tries to access the `Length` property of the stream, and causes the below exception:

```
FluentFTP.FtpException: Error while uploading the file to the server. See InnerException for more info.
 ---> System.NotSupportedException: This stream does not support seek operations.
   at System.Net.Sockets.NetworkStream.get_Length()
   at FluentFTP.FtpClient.UploadFileInternalAsync(Stream fileData, String localPath, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress, CancellationToken token, FtpProgress metaProgress)
   --- End of inner exception stack trace ---
   at FluentFTP.FtpClient.UploadFileInternalAsync(Stream fileData, String localPath, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress, CancellationToken token, FtpProgress metaProgress)
   at FluentFTP.FtpClient.UploadAsync(Stream fileStream, String remotePath, FtpRemoteExists existsMode, Boolean createRemoteDir, IProgress`1 progress, CancellationToken token)
```

**Comment by robinrodricks** [comment]
Thanks for reporting this.

**Comment by robinrodricks** [comment]
We have never tested uploading streams whose length cannot be known, as we have to calculate the upload blocks based on stream length. For now just convert your data into a memory stream with a known length and then try to upload it.
