### ISSUE TITLE
Reading stream fails with IOException after end of stream is reached

### ISSUE THREAD

**Issue by ykosbie** [robinrodricks/FluentFTP#801]
**FTP OS:** Ubuntu

**FTP Server:** Vsftpd

**Computer OS:** Windows 10

**FluentFTP Version:** 35.2.1

`ftpReadStream.Read(buffer, 0, anyNumber)` fails with `IOException` after the end of the stream is reached. Tried with timeout of up to 10 minutes.

**MCVE:**
```
using (var client = new FtpClient(HOST, new NetworkCredential(USER, PASS)))
{
    client.EncryptionMode = FtpEncryptionMode.Explicit;
    client.Connect();

    var stream = client.OpenRead(FILE_PATH);
    new StreamReader(stream).ReadToEnd();
    Console.WriteLine($"Read all stream data. Current position {stream.Position} of {stream.Length}. Attempting read operation");
    var buffer = new byte[100];
    stream.Read(buffer, 0, 100);
    Console.WriteLine("Read succeeded");
}
```

**Logs :**

```
# Connect()
Status:   Connecting to ***:21
Response: 220 (vsFTPd 3.0.3)
Status:   Detected FTP server: VsFTPd
Command:  AUTH TLS
Response: 234 Proceed with negotiation.
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.2022751.
Command:  USER ***
Response: 331 Please specify the password.
Command:  PASS ***
Response: 230 Login successful.
Command:  PBSZ 0
Response: 200 PBSZ set to 0.
Command:  PROT P
Response: 200 PROT now Private.
Command:  FEAT
Response: 211-Features:
Response: EPRT
Response: EPSV
Response: MDTM
Response: PASV
Response: PBSZ
Response: PROT
Response: REST STREAM
Response: SIZE
Response: TVFS
Response: 211 End
Status:   Text encoding: System.Text.ASCIIEncoding+ASCIIEncodingSealed
Command:  SYST
Response: 215 UNIX Type: L8
Status:   Listing parser set to: Unix

# OpenRead("/test-file.txt", Binary, 0)
Command:  TYPE I
Response: 200 Switching to Binary mode.

# GetFileSize("/test-file.txt")
Command:  SIZE /test-file.txt
Response: 213 241914

# OpenPassiveDataStream(AutoPassive, "RETR /test-file.txt", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||50006|)
Status:   Connecting to ***:50006
Command:  RETR /test-file.txt
Response: 150 Opening BINARY mode data connection for /test-file.txt (241914 bytes).
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.1462303.
Unhandled exception. System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond..
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at FluentFTP.FtpDataStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at FluentFtpReadMvce.Program.Main(String[] args) in C:\Users\ykosbie\source\repos\FluentFtpReadMvce\FluentFtpReadMvce\Program.cs:line 32

# Dispose()
Status:   Disposing FtpClient object...
Status:   Testing connectivity using Socket.Poll()...
Command:  QUIT
Warning:  FtpClient.Disconnect(): Exception caught and discarded while closing control connection: System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond..
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at FluentFTP.FtpSocketStream.ReadLine(Encoding encoding)
   at FluentFTP.FtpClient.GetReply()
   at FluentFTP.FtpClient.Execute(String command)
   at FluentFTP.FtpClient.Disconnect()
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
```

**Comment by robinrodricks** [comment]
We don't recommend using the low level `OpenRead`, can you try with `Download` or `DownloadFile` please?

**Comment by ykosbie** [comment]
@robinrodricks I'm handing the steam off to another library that reads it. I can't work with Download for that.

**Comment by FanDjango** [comment]
I can reproduce this error. It does not happen if I disable TLS in vsftp.
