### ISSUE TITLE
Message: The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by rajmondburgaj** [robinrodricks/FluentFTP#853]
Hi,

When I try to create more than one connection to the server and try to upload multiple files at once at some point I get this exception but I have no clue why it happens:

```
Message: An error occurred uploading file(s).  See inner exception for more info.
StackTrace:    at FluentFTP.FtpClient.UploadFilesAsync(IEnumerable`1 localPaths, String remoteDir, FtpRemoteExists existsMode, Boolean createRemoteDir, FtpVerify verifyOptions, FtpError errorHa
ndling, CancellationToken token, IProgress`1 progress)
   at Deploy.DeployUtils.UploadFilesAsync(String server, String username, String password, String serverLocation, IReadOnlyCollection`1 filePaths, CancellationToken token) in C:\Users\Rey\Proje
cts\Deploy\Deploy\DeployUtils.cs:line 64
   at Deploy.DeployUtils.UploadDirectoryAsync(String server, String username, String password, String serverLocation, CancellationToken token) in C:\Users\Rey\Projects\Deploy\Deploy\DeployUtils
.cs:line 41
   at Deploy.Interceptors.SimpleFtpDeployInterceptor.DeployAsync(IDictionary`2 payload, CancellationToken cancellationToken) in C:\Users\Rey\Projects\Deploy\Deploy\Interceptors\SimpleFtpDeployI
nterceptor.cs:line 13
   at Program.<Main>$(String[] args) in C:\Users\Rey\Projects\Deploy\Deploy\Program.cs:line 25
Data: System.Collections.ListDictionaryInternal
-------------------------------------------------------------------
Message: Error while uploading the file to the server. See InnerException for more info.
StackTrace:    at FluentFTP.FtpClient.UploadFileInternalAsync(Stream fileData, String localPath, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Bool
ean fileExistsKnown, IProgress`1 progress, CancellationToken token, FtpProgress metaProgress)
   at FluentFTP.FtpClient.UploadFileFromFileAsync(String localPath, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExistsKnown, FtpVerif
y verifyOptions, CancellationToken token, IProgress`1 progress, FtpProgress metaProgress)
   at FluentFTP.FtpClient.UploadFilesAsync(IEnumerable`1 localPaths, String remoteDir, FtpRemoteExists existsMode, Boolean createRemoteDir, FtpVerify verifyOptions, FtpError errorHandling, Canc
ellationToken token, IProgress`1 progress)
Data: System.Collections.ListDictionaryInternal
-------------------------------------------------------------------
Message: The process cannot access the file because it is being used by another process.
StackTrace:    at FluentFTP.FtpClient.OpenPassiveDataStreamAsync(FtpDataConnectionType type, String command, Int64 restart, CancellationToken token)
   at FluentFTP.FtpClient.OpenDataStreamAsync(String command, Int64 restart, CancellationToken token)
   at FluentFTP.FtpClient.OpenWriteAsync(String path, FtpDataType type, Int64 fileLen, CancellationToken token)
   at FluentFTP.FtpClient.UploadFileInternalAsync(Stream fileData, String localPath, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExis
tsKnown, IProgress`1 progress, CancellationToken token, FtpProgress metaProgress)
Data: System.Collections.ListDictionaryInternal
-------------------------------------------------------------------
```
Below is my code:

```c#
    public static async Task UploadDirectoryAsync(
        string server,
        string username,
        string password,
        string serverLocation,
        CancellationToken token)
    {
        using var ftp = new FtpClient(server, username, password);

        ftp.OnLogEvent += (level, s) =>
        {
            if (level is FtpTraceLevel.Warn or FtpTraceLevel.Error or FtpTraceLevel.Info)
                Console.WriteLine($"Log level: {level}, Message: {s}");
        };

        await ftp.ConnectAsync(token);
        
        await ftp.DeleteDirectoryAsync(serverLocation, token);

        await ftp.CreateDirectoryAsync(serverLocation, token);

        await ftp.DisconnectAsync(token);

        var tasks = new List<Task>();
        
        foreach (var fileChunk in Directory.GetFiles(@"C:\test", "*.*", SearchOption.AllDirectories)
                     .OrderBy(x => x)
                     .Chunk(100))
        { 
            tasks.Add(UploadFilesAsync(server, username, password, serverLocation, fileChunk, token));
        }

        await Task.WhenAll(tasks);
        
        Console.WriteLine("All files uploaded successfully!");
    }
    
    private static async Task UploadFilesAsync(
        string server,
        string username,
        string password,
        string serverLocation,
        IReadOnlyCollection<string> filePaths,
        CancellationToken token)
    {
        using var ftp = new FtpClient(server, username, password);
    
        ftp.OnLogEvent += (level, s) =>
        {
            if (level is FtpTraceLevel.Warn or FtpTraceLevel.Error or FtpTraceLevel.Info)
                Console.WriteLine($"Log level: {level}, Message: {s}");
        };
    
        await ftp.ConnectAsync(token);
    
        await ftp.UploadFilesAsync(
            filePaths,
            serverLocation,
            FtpRemoteExists.NoCheck,
            false,
            FtpVerify.Retry | FtpVerify.Delete,
            FtpError.Throw,
            token);
    
        await ftp.DisconnectAsync(token);
    
        Console.WriteLine($"List of files uploaded successfully! {string.Join(", ", filePaths)}");
    }
```

**Comment by robinrodricks** [comment]
2 FluentFTP clients cannot access the same file, or you will get this error.

**Comment by rajmondburgaj** [comment]
Hi @robinrodricks , how are two clients using the same file ? as you can see I split an array in half, and then process both halfes in two parallel tasks. Maybe I am missing something from your comment!

**Comment by robinrodricks** [comment]
`Message: The process cannot access the file because it is being used by another process.`

This is not a FluentFTP error, its a windows / OS level error. So you are trying to access the same file from 2 places is my guess.
