### ISSUE TITLE
You cannot modify the position of a FtpDataStream. This property is updated as data is read or written to the stream.

### ISSUE THREAD

**Issue by jheus** [robinrodricks/FluentFTP#859]
**FTP OS:** Unix , I think

**FTP Server:** Vsftpd 

**Computer OS:** Windows 10

**FluentFTP Version:** 37.0.2

When trying to upload a file I get the error "You cannot modify the position of a FtpDataStream. This property is updated as data is read or written to the stream.". I have tried client.Upload, client.Upload with bytes and client.UploadFile with file but both are not working, also some other options and properties but I had no luck so far. The code is very strait forward (in C# .net 6):

The file is placed there but no data is written at all

```
FtpClient client = new(hostname, username, password);
client.ValidateAnyCertificate = true;
FtpTrace.LogToConsole = true;

client.AutoConnect();
client.Upload(bytes, location, , FtpRemoteExists.Resume, false);
client.Disconnect();
``` 
When uploading the file via FileZilla I have no issue at all (Beside the certificate failure on the FTP side which I ignored via client.ValidateAnyCertificate = true;

If needed I also have the filezilla log when uploading the file

**Logs :**
```

# AutoConnect()

# AutoDetect(True, False)

# Connect()
Status:   Connecting to ipaddress:21
Response: 220 (vsFTPd 3.0.2)
Status:   Detected FTP server: VsFTPd
Command:  AUTH TLS
Response: 234 Proceed with negotiation.
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0,2057391.
Command:  USER eva-commerce-bv
Response: 331 Please specify the password.
Command:  PASS ***
Response: 230 Login successful.
Command:  PBSZ 0
Response: 200 PBSZ set to 0.
Command:  PROT P
Response: 200 PROT now Private.
Command:  FEAT
Response: 211-Features:
Response: AUTH TLS
Response: EPRT
Response: EPSV
Response: MDTM
Response: PASV
Response: PBSZ
Response: PROT
Response: REST STREAM
Response: SIZE
Response: TVFS
Response: UTF8
Response: 211 End
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Response: 200 Always in UTF8 mode.
Command:  SYST
Response: 215 UNIX Type: L8
Status:   Listing parser set to: Unix

# Upload("/products-feeds/inventory_2022-03-25-10.csv", Overwrite, False)

# FileExists("/products-feeds/inventory_2022-03-25-10.csv")
Command:  SIZE /products-feeds/inventory_2022-03-25-10.csv
Response: 550 Could not get file size.

# OpenWrite("/products-feeds/inventory_2022-03-25-10.csv", Binary)

# GetFileSize("/products-feeds/inventory_2022-03-25-10.csv")
Command:  SIZE /products-feeds/inventory_2022-03-25-10.csv
Response: 550 Could not get file size.
Command:  TYPE I
Response: 200 Switching to Binary mode.

# OpenPassiveDataStream(PASV, "STOR /products-feeds/inventory_2022-03-25-10.csv", 0)
Command:  PASV
Response: 227 Entering Passive Mode (ipaddress,82,108).
Status:   Connecting to ipaddress:21100
Command:  STOR /products-feeds/inventory_2022-03-25-10.csv
Response: 150 Ok to send data.
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0,0797315.
Status:   Disposing FtpSocketStream...

# OpenAppend("/products-feeds/inventory_2022-03-25-10.csv", Binary)

# GetFileSize("/products-feeds/inventory_2022-03-25-10.csv")
Status:   There is stale data on the socket, maybe our connection timed out or you did not call GetReply(). Re-connecting...
Status:   Disposing FtpSocketStream...

# Connect()
Status:   Connecting to ipaddress:21
Response: 220 (vsFTPd 3.0.2)
Status:   Detected FTP server: VsFTPd
Command:  AUTH TLS
Response: 234 Proceed with negotiation.
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0,0637352.
Command:  USER eva-commerce-bv
Response: 331 Please specify the password.
Command:  PASS ***
Response: 230 Login successful.
Command:  PBSZ 0
Response: 200 PBSZ set to 0.
Command:  PROT P
Response: 200 PROT now Private.
Command:  FEAT
Response: 211-Features:
Response: AUTH TLS
Response: EPRT
Response: EPSV
Response: MDTM
Response: PASV
Response: PBSZ
Response: PROT
Response: REST STREAM
Response: SIZE
Response: TVFS
Response: UTF8
Response: 211 End
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Response: 200 Always in UTF8 mode.
Command:  SYST
Response: 215 UNIX Type: L8
Status:   Listing parser set to: Unix
Command:  SIZE /products-feeds/inventory_2022-03-25-10.csv
Response: 213 0
Command:  TYPE I
Response: 200 Switching to Binary mode.

# OpenPassiveDataStream(PASV, "APPE /products-feeds/inventory_2022-03-25-10.csv", 0)
Command:  PASV
Response: 227 Entering Passive Mode (ipaddress,82,117).
Status:   Connecting to ipaddress:21109
Command:  APPE /products-feeds/inventory_2022-03-25-10.csv
Response: 150 Ok to send data.
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0,0689626.
Status:   Disposing FtpSocketStream...

```

**Comment by wallksharp** [comment]
I met the same problem on FluentFTP Version: 35.2.3.
The file was created on remote server, but it was failed to write data.

Code sample:
```
client.EncryptionMode = FtpEncryptionMode.Explicit;
client.ValidateCertificate += new FtpSslValidation(OnValidateCertificate);  // set Accept to true.
client.Connect();
client.UploadFile(localPath, fi.Name, remoteExist, true, progress: progress);
```

Excetpion catched by C# code: 
```
FluentFTP.FtpException: Error while uploading the file to the server. See InnerException for more info.
 ---> System.InvalidOperationException: You cannot modify the position of a FtpDataStream. This property is updated as data is read or written to the stream.
   at FluentFTP.FtpDataStream.set_Position(Int64 value)
   at FluentFTP.FtpClient.ResumeUpload(String remotePath, Stream& upStream, Int64 remotePosition, IOException ex)
   at FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String localPath, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExistsKnown, Action`1 progress, FtpProgress metaProgress)
   --- End of inner exception stack trace ---
   at FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String localPath, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExistsKnown, Action`1 progress, FtpProgress metaProgress)
   at FluentFTP.FtpClient.UploadFileFromFile(String localPath, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExistsKnown, FtpVerify verifyOptions, Action`1 progress, FtpProgress metaProgress)
   at FluentFTP.FtpClient.UploadFile(String localPath, String remotePath, FtpRemoteExists existsMode, Boolean createRemoteDir, FtpVerify verifyOptions, Action`1 progress)
```

The detail log is the same to what jheus's posted.

**Comment by FanDjango** [comment]
The initial upload fails. 

You don't see a message why (**fixed**)

Thus FluenFTP will attempt a retry by using APPE and the offset reached (zero in this case)

You can see the "stale data" error message in the log. FluentFTP closes the connection and re-connects to the host, without telling you very much (**fixed**)

The subsequent retry (using APPE) fails for other reasons (**fixed**).

**fixed** means: Try the newest version of FluentFTP to get much more information about what caused the initial upload to fail. If I may voice a suspicion: This is a "SSL Session Resume" problem and vsftpd is complaining immediately on getting the STOR command. Wouldn't it be nice to see that stale data, which would show the vsftpd error message to you?

**Comment by dlopatin-v** [comment]
I had the same error on version 37, now I updated FluentFTP to the version 51 and got new error: **"Additional error occurred while trying to resume uploading the file <filename> at position <position number>"**.
No more details...

**Comment by FanDjango** [comment]
> No more details...

That makes things difficult to resolve... but I would like you to open a new issue with full logs and sample code to document that problem. V51 has much better and detailed logging to allow debugging and **I cannot understand why you simply report** "I got the same problem" with no further info.

**Comment by dlopatin-v** [comment]
I am not sure it is a FluentFTP bug.
Logs looks like: 
`2024-04-25 08:32:35 10.212.211.126 57295 - - 10.0.100.109 21 ControlChannelOpened - - 0 0 0 0 0 7b32f555-1ecf-458e-9d0f-85da244bcaff - -
2024-04-25 08:32:35 10.212.211.126 57295 - - 10.0.100.109 21 USER vsuclient 331 0 0 23 16 0 7b32f555-1ecf-458e-9d0f-85da244bcaff - -
2024-04-25 08:32:36 10.212.211.126 57295 DKRDSVSUP01\VSUClient - 10.0.100.109 21 PASS *** 230 0 0 21 15 0 7b32f555-1ecf-458e-9d0f-85da244bcaff / -
2024-04-25 08:32:36 10.212.211.126 57295 DKRDSVSUP01\VSUClient - 10.0.100.109 21 FEAT - 211 0 0 149 6 0 7b32f555-1ecf-458e-9d0f-85da244bcaff - -
2024-04-25 08:32:36 10.212.211.126 57295 DKRDSVSUP01\VSUClient - 10.0.100.109 21 OPTS UTF8+ON 200 0 0 58 14 0 7b32f555-1ecf-458e-9d0f-85da244bcaff - -
2024-04-25 08:32:36 10.212.211.126 57295 DKRDSVSUP01\VSUClient - 10.0.100.109 21 SYST - 215 0 0 16 6 0 7b32f555-1ecf-458e-9d0f-85da244bcaff - -
2024-04-25 08:32:36 10.212.211.126 57295 DKRDSVSUP01\VSUClient - 10.0.100.109 21 PWD - 257 0 0 31 5 0 7b32f555-1ecf-458e-9d0f-85da244bcaff - -
2024-04-25 08:32:37 10.212.211.126 57295 DKRDSVSUP01\VSUClient - 10.0.100.109 21 SIZE /Uploads/6f33dac6-519b-401b-8a83-ecd5d74a027f.vsu 550 2 3 49 56 0 7b32f555-1ecf-458e-9d0f-85da244bcaff /Uploads/6f33dac6-519b-401b-8a83-ecd5d74a027f.vsu File+system+returned+an+error.
2024-04-25 08:32:37 10.212.211.126 57295 DKRDSVSUP01\VSUClient - 10.0.100.109 21 TYPE I 200 0 0 20 8 0 7b32f555-1ecf-458e-9d0f-85da244bcaff - -
2024-04-25 08:32:37 10.212.211.126 57295 DKRDSVSUP01\VSUClient - 10.0.100.109 21 EPSV - 229 0 0 48 6 0 7b32f555-1ecf-458e-9d0f-85da244bcaff - -
2024-04-25 08:32:38 10.212.211.126 57296 DKRDSVSUP01\VSUClient - 10.0.100.109 41850 DataChannelOpened - - 0 0 0 0 0 7b32f555-1ecf-458e-9d0f-85da244bcaff - -`

**File+system+returned+an+error** this is what I only see from logs. The problem happens from time to time, the system transfer many files and most of them completed successful. I notice the issue happens for big files and when the transferring process was frozen (user closed laptop and after some time open it and transfer trying to resume process)
