### ISSUE TITLE
Connect result in : Safe handle has been closed. Object name: 'SafeHandle'. In .net 4.8

### ISSUE THREAD

**Issue by peans99** [robinrodricks/FluentFTP#865]
**FTP OS:** Windows

**FTP Server:** Filezilla server

**Computer OS:** Windows 10 1909 Enterprise

**FluentFTP Version:** 37.0.2

            using (var conn = new FtpClient())
            {

                conn.Host = ftpPayload.Host;
                conn.Credentials = ftpPayload.Credential;
                conn.Port = ftpPayload.Port;
                conn.Connect();
           result in Safe handle has been closed . This work on older version (32.3.3).
**Logs :**
Connect result in : Safe handle has been closed. Object name: 'SafeHandle'.
   at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout)
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout)
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   at FluentFTP.FtpSocketStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at FluentFTP.FtpSocketStream.ReadLine(Encoding encoding)
   at FluentFTP.FtpClient.GetReply()
   at FluentFTP.FtpClient.Handshake()
   at FluentFTP.FtpClient.Connect()

```

<paste logs here>


```

**Comment by peans99** [comment]
I found a work around the Async works fine on .net 4.8
                conn.Host = ftpPayload.Host;
                conn.Credentials = ftpPayload.Credential;
                conn.Port = ftpPayload.Port;
                conn.ConnectAsync().Wait();

**Comment by FanDjango** [comment]
@peans99 Is this still an issue for you?
